export default {
    "check": "تحقق",
    "detail": "تفاصيل",
    "dns": "DNS",
    "renew": "تجديد",
    "renewDomain": "تجديد النطاق",
    "listTitle": "قائمة النطاقات",
    "newOrder": "شراء نطاق",
    "transferDomain": "نقل نطاق",
    "registerTitle": "تسجيل حساب النطاق",
    "administrationData": "بيانات الإدارة",
    "addressData": "بيانات العنوان",
    "address": "العنوان",
    "address1": "العنوان (السطر 1)",
    "address2": "العنوان (السطر 2)",
    "address3": "العنوان (السطر 3)",
    "city": "المدينة",
    "state": "الولاية",
    "country": "الدولة",
    "zipCode": "الرمز البريدي",
    "company": "الشركة",
    "companyName": "اسم الشركة / المؤسسة",
    "domainName": "اسم النطاق",
    "domainStatus": "حالة النطاق",
    "enterContact": "أدخل بيانات الاتصال بالنطاق",
    "contactEntered": "تم إدخال بيانات الاتصال بالنطاق",
    "myOwn": "النطاق الذي طلبته هو ملكي",
    "enterBio": "أدخل بيانات الاتصال",
    "publicBio": "اتصال عام / مالك النطاق",
    "personalBio": "اتصال شخصي / مسؤول عن النطاق",
    "domainPrice": "سعر النطاق",
    "emptyList": "لا توجد نطاقات مدرجة",
    "registrationDate": "تاريخ التسجيل",
    "expirationDate": "تاريخ الانتهاء",
    "transferLock": "قفل النقل",
    "privacyLock": "قفل الخصوصية",
    "nameServers": "خوادم الأسماء",
    "checkHint": "انقر على زر التحقق",
    "checkFail": "فشل في التحقق من توفر النطاق",
    "findDomain": "ابحث عن نطاق",
    "findWait": "جاري التحقق ...",
    "findUnavailable": "النطاق غير متوفر حاليا.",
    "findNeedData": "لا يمكننا معالجة شراء النطاقات حتى تقوم بتعبئة البيانات المطلوبة.",
    "findNeedDataAction": "تعبئة الآن",
    "verifyHint": "يجب عليك التحقق من بريدك الإلكتروني خلال 15 يوما بعد الشراء وإلا سيقوم المسجل بتعليق نطاقك!",
    "verifyBtn": "إعادة إرسال رسالة التحقق إلى {0}",
    "transferCode": "رمز EPP / النقل",
    "showTransferCode": "عرض رمز EPP",
}
