<?php return [
	'emailAlreadyExist' => 'هذا البريد الإلكتروني موجود بالفعل',
	'passwordNotLongEnough' => 'كلمة المرور هذه ليست طويلة بما يكفي',
	'passwordNotMatch' => 'كلمة المرور الحالية غير متطابقة',
	'invalidCountry' => 'رمز الدولة غير صالح',
	
	'accountAlreadyAttached' => 'عذرًا، هذا الحساب الاجتماعي مرتبط بحساب آخر.',
	'accountCreationExpired' => 'عذرًا، يبدو أننا نحاول تأكيد إنشاء حسابك ولكن انتهت صلاحية الجلسة. حاول تسجيل الدخول مرة أخرى.',
	'accountPasswordlessRecovery' => 'للأسف، لا يمكنك استعادة حساب بدون كلمة مرور. يرجى محاولة استخدام طرف ثالث (Google أو GitHub) بدلاً من ذلك.',
	'accountDeleteLastMethod' => 'لا يمكنك حذف الطريقة الوحيدة لتسجيل الدخول',
	'accountRecountTooFast' => 'يرجى الانتظار قليلاً قبل إعادة العد',
	'accountDeleteNotDangling' => 'يرجى حذف جميع المضيفين، النطاقات، والنسخ الاحتياطية أولاً',

	'inviteUserNotFound' => 'لم يتم العثور على هذا المستخدم',
	'inviteQuotaFull' => 'عدد أعضاء الفريق بلغ الحد الأقصى، يرجى الترقية',
	'inviteNewFail' => 'فشل في الدعوة، ربما تمت إضافتهم بالفعل؟',
	'inviteRemoveFail' => 'فشل في إزالة العضو، ربما تم إزالته بالفعل؟',

	'inviteCodeInvalid' => 'رمز الدعوة غير صالح',
	'inviteCodeExpired' => 'انتهت صلاحية رمز الدعوة',

	'unknownAction' => 'إجراء غير معروف',
	'hostIsNotActive' => 'غير قادر على تطبيق المهمة بينما هذا المضيف غير نشط',
	'needVerifyEmail' => 'يرجى التحقق من بريدك الإلكتروني أولاً',
	'hostQuotaLimit' => 'عذرًا، تحتاج إلى ترقية خطتك لإنشاء المزيد من المضيفين. إذا كنت قد فعلت، فتحقق من رصيدك أو اتصل بالدعم.',
	'usingInternalDomain' => 'عذرًا، لا يمكنك استخدام نطاقنا هنا',
	'usingSubscibingDomain' => 'عذرًا، تحتاج إلى ترقية خطتك لاستخدام هذا النطاق',
	'invalidUsername' => 'اسم المستخدم غير صالح',
	'invalidDomainname' => 'اسم النطاق غير صالح',
	'unchangedUsername' => 'اسم المستخدم لم يتغير',
	'unchangedDomainname' => 'اسم النطاق لم يتغير',
	'domainAlreadyExist' => 'اسم النطاق موجود بالفعل',
	'tooShortUsername' => 'اسم المستخدم قصير جدًا',
	'parentNotFound' => 'النطاق الأساسي غير موجود',
	'invalidDeployYaml' => 'برنامج النشر الخاص بك ليس YAML صالحًا: {0}',
	'deploymentFailedToReach' => 'فشلنا في الاتصال بالخادم {0} لهذا النشر: {1}',
	'hostRunnerProgressing' => 'بسرعة كبيرة! لا يمكن التطبيق بينما عمليات النشر تعمل حاليًا! يرجى الانتظار قليلاً.',
	'backupNeedSubscribe' => 'عذرًا، تحتاج إلى ترقية خطتك لإنشاء نسخ احتياطية',
	'backupIsNotActive' => 'حالة النسخ الاحتياطي غير نشطة، ربما انتهت صلاحيتها بالفعل',
];
