export default {
    'invoiceDomainPurchaseOf': 'شراء النطاق لـ {0}',
    'invoiceDomainExtendOf': 'تمديد النطاق لـ {0}',
    'invoiceDomainTransferOf': 'نقل النطاق لـ {0}',
    'invoiceTeamPurchaseOf': 'شراء الخطة لـ {0} فريق',
    'invoiceTeamAddons': 'إضافات الفريق',
    'invoiceForMonths': ' لـ {0, plural, =1{# شهر} other{# أشهر}}',
    'invoiceForYears': ' لـ {0, plural, =1{# سنة} other{# سنوات}}',
    'invoiceForYearsAndMonths': ' لـ {0, plural, =1{# سنة} other{# سنوات}} و {1, plural, =1{# شهر} other{# أشهر}}',
    'invoiceDataTransferAddonsFor': 'نقل البيانات الإضافية لـ {0} جيجابايت',
    'invoiceTip': 'رسوم الراحة',
    "listTitle": "قائمة المواقع الإلكترونية",
    "newOrder": "إضافة موقع إلكتروني",
    "tabDetail": "معلومات",
    "tabSetup": "الإعداد",
    "tabManage": "إدارة",
    "tabRunner": "نشر",
    "tabWebhook": "الويب هوك",
    "tabCheck": "فحص",
    "tabConnection": "فحص الاتصال",
    "tabFirewall": "فحص الجدار الناري",
    "tabNginx": "فحص NGINX",
    "tabDns": "فحص DNS",
    "tabLog": "فحص السجلات",
    "tabAdmin": "الإدارة",
    "tabRename": "تغيير اسم المستخدم",
    "tabCname": "تغيير النطاق",
    "tabPasswd": "تغيير كلمة المرور",
    "tabTransfer": "نقل الموقع",
    "tabDelete": "حذف الموقع",
    "startFromTemplate": "البدء من قالب",
    "uploadOrClone": "رفع أو استنساخ من الإنترنت",
    "seeMoreTemplates": "عرض المزيد من قوالب المواقع",
    "customTemplate": "قالب مخصص",
    "customDomain": "نطاق مخصص",
    "mergeToParentDomain": "دمج مع النطاق الرئيسي",
    "fetchingDomains": "...جاري جلب النطاقات",
    "moreTemplates": "المزيد من القوالب",
    "portalUsername": "اسم المستخدم",
    "portalUsernameHint": "أحرف وأرقام وشرطة فقط",
    "portalPassword": "كلمة المرور",
    "slaveServer": "المنطقة",
    "scheme": "الخطة",
    "usage": "الاستخدام",
    "month": "أشهر",
    "year": "سنة/سنوات",
    "free": "مجاني",
    "database": "قاعدة البيانات",
    "additionalServices": "خدمات إضافية",
    "softwareCompilers": "مترجم البرمجيات",
    "enableNewFeatures": "تمكين الميزات الجديدة",
    "addHost": "إضافة موقع إلكتروني",
    "emptyList": "لا توجد مواقع إلكترونية مدرجة",
    "waitForDataHint": "سيظهر استخدام الموارد هنا. عد في اليوم التالي لظهور البيانات.",
    "slaveID": "معرف الخادم الفرعي",
    "IPAddress": "عنوان IP",
    "openWebsite": "فتح الموقع",
    "openPortal": "فتح البوابة",
    "hostStatus": "حالة الاستضافة",
    "creationDate": "تاريخ الإنشاء",
    "usernameHost": "اسم المستخدم للمضيف",
    "domainHost": "نطاق المضيف",
    "manageHostLogin": "إدارة تسجيل دخول المضيف",
    "total": "الإجمالي",
    "used": "المستخدم",
    "remainingMonthlyPlan": "الخطة الشهرية المتبقية",
    "remainingAddons": "الإضافات المتبقية",
    "planDetail": "خطة {0}، مساحة القرص {1}، النطاق الترددي الشهري {2}.",
    "emptyForDefaultCname": "اتركه فارغًا للإعداد الافتراضي ({0})",
    "redeploy": "إعادة النشر",
    "debugManually": "التصحيح يدويًا",
    "startOver": "البدء من جديد",
    "deployScript": "نشر السكربت",
    "deployAdd": "إضافة مهمة نشر",
    "deployNow": "نفذ الآن!",
    "deployClearHint": "هل تريد مسح جميع السجلات؟",
    "websiteReadyHint": "موقعك جاهز. هل ترغب في زيارته الآن؟",
    "deployByAdmin": "تم التشغيل بواسطة نظام المشرف",
    "deployOverwriteBanner": "سيتم استبدال جميع الملفات في هذا الموقع بهذا السكربت!",
    "deployOverwriteWarn": "لقد ذكرت معلمة المصدر، مما يعني أن ملف HOME الخاص بك سيتم استبداله بشكل دائم. لا يمكن عكس هذا الإجراء. هل أنت متأكد؟",
    "deployHelpBtn": "مرجع إعدادات النشر",
    "githubWebhook": "إعداد الويب هوك",
    "githubWebhookTitle": "إعداد GitHub Action",
    "githubWebhookHelp": "يمكنك استخدام هذا الويب هوك لنشر موقعك تلقائيًا عند الدفع إلى GitHub.",
    "githubWebhookHelpBtn": "مساعدة ويب هوك GitHub Action",
    "noWebhook": "لم يتم تكوين أي ويب هوك لهذا المضيف.",
    "noGitHubApi": "واجهة برمجة تطبيقات GitHub غير متاحة",
    "noGitHubApiToken": "لم يتم العثور على رمز واجهة برمجة تطبيقات GitHub",
    "noGitHubApiHint": "تحتاج إلى ربط حساب GitHub أولاً بالوصول الكامل إلى المستودع.",
    "noGitHubApiLink": "ربط GitHub الآن",
    "noRepo": "لم يتم العثور على مستودع",
    "noRepoHint": "حاول تضييق نطاق البحث الخاص بك",
}
