export default {
    "status": {
        "active": "Active",
        "starting": "Starting",
        "suspended": "Suspended",
        "moving": "Moving",
        "removing": "Removing",
        "removed": "Removed"
    },
    "listTitle": "Website List",
    "newOrder": "Add a website",
    "tabDetail": "Info",
    "tabSetup": "Setup",
    "tabManage": "Manage",
    "tabRunner": "Deploy",
    "tabDatabase": "Database",
    "tabSubdomain": "Subdomain",
    "tabSoftware": "Software",
    "tabWebhook": "Webhook",
    "tabCheck": "Check",
    "tabConnection": "Check Connection",
    "tabFirewall": "Check Firewall",
    "tabNginx": "Check NGINX",
    "tabDns": "Check DNS",
    "tabLog": "Check Logs",
    "tabUser": "Check User",
    "tabAdmin": "Admin",
    "tabRename": "Change Username",
    "tabCname": "Change Domain",
    "tabPasswd": "Change Password",
    "tabServer": "Change Server",
    "tabTransfer": "Transfer Website",
    "tabDelete": "Delete Website",
    "startFromTemplate": "Start from a template",
    "uploadOrClone": "Upload or clone from the Internet",
    "seeMoreTemplates": "See more web templates",
    "customTemplate": "Custom template",
    "customDomain": "Custom domain",
    "mergeToParentDomain": "Merge to parent domain",
    "fetchingDomains": "...Fetching domains",
    "moreTemplates": "More templates",
    "portalUsername": "Username",
    "portalUsernameHint": "Only alphanumeric and hyphen",
    "portalPassword": "Password",
    "serverName": "Server Name",
    "scheme": "Plan",
    "usage": "Usage",
    "month": "Months",
    "year": "Years",
    "free": "Free",
    "database": "Database",
    "additionalServices": "Additional Services",
    "softwareCompilers": "Software Compilers",
    "enableNewFeatures": "Enable New Features",
    "addHost": "Add a Website",
    "emptyList": "No website listed",
    "waitForDataHint": "Resources usage will appear here",
    "IPAddress": "IP Address",
    "openWebsite": "Open Website",
    "openPortal": "Open Portal",
    "creationDate": "Creation Date",
    "websiteStatus": "Website Status",
    "websiteUsername": "Website Username",
    "websiteDomain": "Website Domain",
    "manageHostLogin": "Manage Host Login",
    "manageDatabase": "Manage Database",
    "total": "Total",
    "used": "Used",
    "remainingMonthlyPlan": "Remaining Monthly Plan",
    "remainingAddons": "Remaining Add-Ons",
    "createDatabase": "Create {0} Database",
    "createDatabaseHint": "Enter the new {0} database name",
    "createDatabaseConfirm": "Will create \"{0}\", continue?",
    "dropDatabase": "Drop {0} Database",
    "dropDatabaseConfirm": "Will drop \"{0}\", continue?",
    "dropDatabaseConfirm2": "Are you really want to execute \"{0}\"? This can't be undone.",
    "tables": "{0} {0, plural, one {table} other {tables}}",
    "noSubdomain": "Please use custom domain to create subdomains",
    "createSubdomain": "Create a new subdomain",
    "deleteSubdomain": "Delete {0} subdomain",
    "deleteSubdomainConfirm": "Will delete subdomain \"{0}\", continue?",
    "deleteSubdomainConfirm2": "Are you really want to execute \"{0}\"? This can't be undone.",
    "enterFullDomainName": "Enter full domain name",
    "useDefaultCname": "Use default domain name ({0})",
    "useDifferentPassword": " Use different password for {0}",
    "redeploy": "Redeploy",
    "debugManually": "Debug Manually",
    "startOver": "Start Over",
    "deployScript": "Deploy Script",
    "deployAdd": "Add a deployment task",
    "deployNow": "Execute!",
    "deployClearHint": "Clear all logs?",
    "websiteReadyHint": "Your site is ready. Try to visit now?",
    "deployByAdmin": "Ran By System Mod",
    "deployOverwriteBanner": "This script will replace all files from this website!",
    "deployOverwriteWarn": "You mentioned the source parameter, which means your HOME file will be PERMANENTLY OVERWRITTEN. This action cannot be reversed. Are you sure?",
    "deployHelpBtn": "Deploy Config Reference",
    "githubWebhook": "Setup Webhook",
    "githubWebhookTitle": "Setup GitHub Action",
    "githubWebhookHelp": "You can use this webhook to automatically deploy your website when you push to GitHub.",
    "githubWebhookHelpBtn": "GitHub Action Webhook Help",
    "noWebhook": "There's no webhooks configured for this host.",
    "noGitHubApi": "GitHub API is not available",
    "noGitHubApiToken": "GitHub API token not found",
    "noGitHubApiHint": "You need to link a GitHub account first with full repo access.",
    "noGitHubApiLink": "Link GitHub Now",
    "noRepo": "No repository found",
    "noRepoHint": "Try narrowing your search",
}
