export default {
    'invoiceDomainPurchaseOf': 'Domain Purchase of {0}',
    'invoiceDomainExtendOf': 'Domain Extend of {0}',
    'invoiceDomainTransferOf': 'Domain Transfer of {0}',
    'invoiceTeamPurchaseOf': 'Team Purchase of {0} plan',
    'invoiceTeamAddons': 'Team Add-ons',
    'invoiceForMonths': ' for {0, plural, =1{# month} other{# months}}',
    'invoiceForYears': ' for {0, plural, =1{# year} other{# years}}',
    'invoiceForYearsAndMonths': ' for {0, plural, =1{# year} other{# years}} and {1, plural, =1{# month} other{# months}}',
    'invoiceDataTransferAddonsFor': 'Additional Data transfer for {0} GB',
    'invoiceTip': 'Convenience Fee',
    "listTitle": "Website List",
    "newOrder": "Add a website",
    "tabDetail": "Info",
    "tabSetup": "Setup",
    "tabManage": "Manage",
    "tabRunner": "Deploy",
    "tabWebhook": "Webhook",
    "tabCheck": "Check",
    "tabConnection": "Check Connection",
    "tabFirewall": "Check Firewall",
    "tabNginx": "Check NGINX",
    "tabDns": "Check DNS",
    "tabLog": "Check Logs",
    "tabAdmin": "Admin",
    "tabRename": "Change Username",
    "tabCname": "Change Domain",
    "tabPasswd": "Change Password",
    "tabTransfer": "Transfer Website",
    "tabDelete": "Delete Website",
    "startFromTemplate": "Start from a template",
    "uploadOrClone": "Upload or clone from the Internet",
    "customTemplate": "Custom template",
    "customDomain": "Custom domain",
    "mergeToParentDomain": "Merge to parent domain",
    "fetchingDomains": "...Fetching domains",
    "moreTemplates": "More templates",
    "portalUsername": "Username",
    "portalUsernameHint": "Only alphanumeric and hyphen",
    "portalPassword": "Password",
    "slaveServer": "Region",
    "scheme": "Plan",
    "usage": "Usage",
    "month": "Months",
    "year": "Year(s)",
    "free": "Free",
    "addHost": "Add a Website",
    "emptyList": "No website listed",
    "waitForDataHint": "Resources usage will appear here. Come back in next day for the data to appear.",
    "slaveID": "Slave ID",
    "IPAddress": "IP Address",
    "openWebsite": "Open Website",
    "openPortal": "Open Portal",
    "hostStatus": "Host Status",
    "creationDate": "Creation Date",
    "usernameHost": "Host Username",
    "domainHost": "Host Domain",
    "manageHostLogin": "Manage Host Login",
    "total": "Total",
    "used": "Used",
    "remainingMonthlyPlan": "Remaining Monthly Plan",
    "remainingAddons": "Remaining Add-Ons",
    "planDetail": "{0} Plan, {1} disk space, {2} monthly bandwidth.",
    "emptyForDefaultCname": "Leave blank for default ({0})",
    "redeploy": "Redeploy",
    "deployAdd": "Add a deployment task",
    "deployNow": "Execute!",
    "deployClearHint": "Clear all logs?",
    "deployOverwriteWarn": "You mentioned the source parameter, which means your HOME file will be PERMANENTLY OVERWRITTEN. This action cannot be reversed. Are you sure?",
    "deployHelpBtn": "Deploy Config Reference",
    "githubWebhook": "Setup Webhook",
    "githubWebhookTitle": "Setup GitHub Action",
    "githubWebhookHelp": "You can use this webhook to automatically deploy your website when you push to GitHub.",
    "githubWebhookHelpBtn": "GitHub Action Webhook Help",
    "noWebhook": "There's no webhooks configured for this host.",
    "noGitHubApi": "GitHub API is not available",
    "noGitHubApiToken": "GitHub API token not found",
    "noGitHubApiHint": "You need to link a GitHub account first with full repo access.",
    "noGitHubApiLink": "Link GitHub Now",
    "noRepo": "No repository found",
    "noRepoHint": "Try narrowing your search",
}
