export default {
    "logout": "Sign out",
    "profile": "Profile",
    "status": "Status",
    "verifyStatus": "Verification status",
    "bannedHint": "Your account is banned, sorry.",
    "hosting": "Website",
    "domain": "Domain",
    "backup": "Backup",
    "owner": "Owner",
    "admin": "Admin",
    "member": "Member",
    "team": "Team",
    "email": "Email",
    "storage": "Storage",
    "bandwidth": "Bandwidth",
    "instances": "Instances",
    "users": "Users",
    "details": "Details",
    "members": "Members",
    "upgrade": "Upgrade",
    "otherTeams": "Other Teams",
    "inviteCode": "Invite Code",
    "hostname": "Hostname",
    "port": "Port",
    "username": "Username",
    "password": "Password",
    "server": "Server",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "redis": "Redis",
    "mysql2": "MySQL (MariaDB)",
    "redis2": "Redis (Valkey)",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "phprdadmin": "phpRdAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    "help": "Help",
    "helpDocs": "Docs",
    "helpEmail": "Email",
    "helpForum": "Forum",
    "helpChat": "Chat",
    "helpUpdates": "Updates",
    "country": "Country",
    "chooseCountry": "Choose a country",
    "expiration": "Expiration",
    "resendConfirmationEmail": "Resend Confirmation Email",
    "learnMore": "Learn more",
    "passwordNotice": "You don't need to remember this password",
    "lastUpdatedAt": "Last updated at",
    "language": "Language",
    "theme": "Theme",
    "themeDark": "Always Dark",
    "themeLight": "Always Light",
    "themeSystem": "System Default",
    "role": "Role",
    "action": "Action",
    "currencyInput": "Currency",
    "invoiceNoteInput": "Invoice Contact",
    "defaultServerInput": "Default Server",
    "defaultServerInputNone": "None (ask me)",
    "name": "Name",
    "phone": "Phone Number",
    "phoneHint": "Fully Qualified Phone Number (starts with +)",
    "phoneAlt": "Alternative Phone Number",
    "fullName": "Full Name",
    "companyName": "Company Name",
    "activeEmail": "Active Email",
    "newPassword": "New Password",
    "editProfile": "Edit Profile",
    "saveProfile": "Save Profile",
    "deleteAccount": "Delete Account",
    "loginMethods": "Login Methods",
    "loginRemoveConfirm": "Are you sure you want to remove this login method?",
    "loginAdd": "Add or replace a login method",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "Email + Password",
    "loginVia": "via {0}",
    "passwordConfirm": "Enter current account password (if present)",
    "passwordSetInput": "Enter new password, must at least 8 characters",
    "passwordSetCancel": "Setting password for this account has been cancelled",
    "passwordSetCancelLength": "Setting password cancelled, must be at least 8 characters",
    "yearDuration": "Duration in years",
    "monthDuration": "Duration in months",
    "annualSaving": "Save 16%",
    "totalPayment": "Total Payment",
    "expirationDate": "Expiration Date",
    "orderNow": "Order Now",
    "invoice": "Invoice",
    "pendingInvoices": "Pending Invoices",
    "noPendingInvoices": "You have no pending invoices currently.",
    "mixedCurrency": "Selected invoices have mixed currencies",
    "currentPlan": "Current Plan",
    "currentPlanDescription": "With cost <b>{0}</b> per month with expiry <b>{1}</b>",
    "priceDescription": "{0} / month",
    "monthlyLimits": "Monthly Limits",
    "storageLimit": "{0} GB Storage",
    "networkLimit": "{0} GB Network",
    "instanceLimit": "{0} {0, plural, one {Instance} other {Instances}}",
    "userLimit": "{0} {0, plural, one {User} other {Users}}",
    "autoStop": "Auto stop at limits",
    "noFreeDomain": "No *.domcloud.dev domain",
    "withFreeDomain": "Free *.domcloud.dev domain",
    "withBackup": "Automatic server-level backup",
    "withDocker": "Docker and long-running apps",
    "storageUsage": "Storage Usage",
    "storageUsageCap": "of {0} total",
    "bandwidthUsed": "Bandwidth Used",
    "bandwidthUsedCap": "of {0} monthly",
    "instancesActive": "Instances Active",
    "instancesActiveCap": "of {0} websites",
    "teamUsers": "Team Users",
    "teamUsersCap": "of {0} users maximum",
    "remainingAvailable": "Remaining Available",
    "remainingStorage": "Free Storage",
    "remainingNetwork": "Network Data",
    "remainingInstance": "Remaining Instance",
    "dataTransfer": "Data Transfer",
    "copy": "Copy",
    "copied": "Copied!",
    "reloading": "Reloading {0}",
    "expires": "Expires {0}",
    "expiresAt": "Expires at {0}",
    "expireFreeHint": `
  Expiration dates are automatically renewed (extending for 3 months) 
  each time you login or your websites has enough network traffic (>50 MB)
  at the end of the month.
  `,
    "discountedAt": "Discount of {0} placed",
    "paymentFeeAt": "Payment fees of {0} placed",
    "extendingCurrentExpiryDate": "Extending current expiry date",
    "usersLimitHint": "{0} {0, plural, one {user} other {users}} in this team, {1} {1, plural, one {user} other {users}} can be added more",
    "emailToInvite": "Email to invite",
    "selectRole": "Select role",
    "info": "Info",
    "total": "Total",
    "back": "Back",
    "add": "Add",
    "addMember": "Add Member",
    "confirmRemoveMember": "Are you sure you want to remove this member?",
    "edit": "Edit",
    "apply": "Apply",
    "save": "Save",
    "clear": "Clear",
    "update": "Update",
    "updateUsage": "Update Usage",
    "change": "Change",
    "archives": "Archives",
    "renew": "Renew",
    "extend": "Extend",
    "topup": "Topup",
    "processing": "Processing",
    "cancel": "Cancel",
    "print": "Print",
    "delete": "Delete",
    "why": "Why?",
    "pay": "Pay",
    "payAccept": "We accept payments through",
    "loading": "Gathering data...",
    "fetchError": "Error fetching data! try again later",
    "notFound": "Not Found",
    "notFoundDescription": "The page you are looking for does not exist.",
    "notFoundLink": "Go back to the homepage",
}
