<?php return [
	'code' => 'en',
	'codename' => 'English',
	'codeI8LN' => 'en-US',
	'currency' => 'usd',
	'login' => 'Sign In',
	'register' => 'Register',
	'email' => 'Email',
	'enterToPortal' => 'Enter to Portal',
	'registerToPortal' => 'Register to Portal',
	'registerWithEmail' => 'Register with Email',
	'forgotPrompt' => 'Forgot Password?',
	'recoverYourPassword' => 'Recover Your Password',
	'recoverYourPasswordHint' => 'Enter a new password to change',
	"report" => "Report",
	"reportPrompt" => "Report suspicious activity within DOM Cloud Network. Content will be immediately removed if reported website fulfills our criteria.",
	"reportAbuse" => "Report Abuse Content",
	"reportDomain" => "Domain to report",

	'ok' => 'OK',
	'back' => 'Back',
	'or' => 'Or',
	'signInWith' => 'Sign in with',
	'wrongLogin' => 'Wrong email or password',
	'registerAgreement' => 'By registering you agree to our <a href="//domcloud.co/service">Terms of Service</a>.',
	'emailSent' => 'The email for verification has been sent, please check your inbox (and spam box) before login.',
	'oAuthFail' => 'It seems that your attempt with third-party login is failed. This is commonly caused by timeout or primary email tied with that account is not verified yet.',
	'passReset' => 'Your password has been successfully reset. Please login with your new password.',
	'thanksForVerify' => 'Thank you, your email has been verified',

	'password' => 'Password',
	'passwordAgain' => 'Password (Again)',
	'fullName' => 'Full Name',
	'activeEmail' => 'Active Email',

];
