export default {
    "listTitle": "Invite Code",
    "startingHint": "Have a friend want to tryout our service? Send your friend an invite code! You might get rewarded when your friend upgraded.", 
    "freePlanHint": "Sorry! Free users can't create a new code. Please upgrade or ask an invite code from our Discord Community Forum.", 
    "newOrder": "Create a new Invite Code",
    "code": "Invite Code",
    "credit": "Current Credit",
    "quota": "Signup Left",
    "totalRedeem": "Total Credit",
    "totalSignup": "Total Signups",
    "expiry": "Invite Code Expiration",
    "cooldown": "Renew Code Cooldown",
    "editQuota": "Edit Quota",
    "editQuotaTitle": "Edit Quota and Set a New Code",
    "editQuotaHint": "Select the Invite Code Limit for a new code",
    "noInvitees": "No recorded signups yet",
    "inviteeCode": "Signup Code",
    "inviteeJoinTime": "Join Time",
    "cooldownIn": "Cooldown: {0}",
    "quotaOffHint": "Turn off invite code",
    "quotaSmallHint": "For inviting a friend or someone at a public chat",
    "quotaLargeHint": "For creating events and private online tutorials",
}
