export default {
    "listTitle": "Self-Hosted Server List",
    "newOrder": "Add a server",
    "startingHint": "Read about creating your own self-hosted instance",
    "name": "Server Domain Name",
    "nameHint": "The domain name of your self-hosted bridge website",
    "description": "Server Nice Name",
    "descriptionHint": "The nice description of this server",
    "secret": "Bridge Secret",
    "secretHint": "The secret that set on bridge .env file",
    "openHost": "Open Host Settings",
    "emptyList": "No servers listed",
    "createTitle": "Create a new server",
    "createTitleHint": "Please fill in your server information",
}
