export default {
    "check": "Überprüfen",
    "detail": "Detail",
    "dns": "DNS",
    "renew": "Erneuern",
    "renewDomain": "Domain erneuern",
    "listTitle": "Domainliste",
    "newOrder": "Domain kaufen",
    "transferDomain": "Domain übertragen",
    "registerTitle": "Domainkontoregistrierung",
    "administrationData": "Verwaltungsdaten",
    "addressData": "Adressdaten",
    "address": "Adresse",
    "address1": "Adresse (Zeile 1)",
    "address2": "Adresse (Zeile 2)",
    "address3": "Adresse (Zeile 3)",
    "city": "Stadt",
    "state": "Bundesland",
    "country": "Land",
    "zipCode": "Postleitzahl",
    "company": "Firma",
    "companyName": "Firmenname / Organisationsname",
    "domainName": "Domainname",
    "domainStatus": "Domainstatus",
    "enterContact": "Domain-Kontakt eingeben",
    "contactEntered": "Domain-Kontakt eingegeben",
    "myOwn": "Die von mir bestellte Domain gehört mir",
    "enterBio": "Kontakt eingeben",
    "publicBio": "Öffentlicher Kontakt / Domaininhaber",
    "personalBio": "Persönlicher Kontakt / Verantwortliche Domain",
    "domainPrice": "Domainpreis",
    "emptyList": "Keine Domain aufgeführt",
    "registrationDate": "Registrierungsdatum",
    "expirationDate": "Ablaufdatum",
    "transferLock": "Transfer-Sperre",
    "privacyLock": "Privatsphären-Sperre",
    "nameServers": "Nameserver",
    "checkHint": "Klicken Sie auf die Überprüfen-Taste",
    "checkFail": "Überprüfung der Domain-Verfügbarkeit fehlgeschlagen",
    "findDomain": "Domain finden",
    "findWait": "Überprüfen ...",
    "findUnavailable": "Domain ist derzeit nicht verfügbar.",
    "findNeedData": "Wir können Domainkäufe nicht bearbeiten, bis Sie die benötigten Daten ausfüllen.",
    "findNeedDataAction": "Jetzt ausfüllen",
    "verifyHint": "Sie müssen Ihre E-Mail innerhalb von 15 Tagen nach dem Kauf verifizieren, sonst wird unser Registrar Ihre Domain sperren!",
    "verifyBtn": "Verifizierungs-E-Mail an {0} erneut senden",
    "transferCode": "EPP / Transfercode",
    "showTransferCode": "EPP-Code anzeigen",
}
