<?php return [
	'emailAlreadyExist' => 'Diese E-Mail existiert bereits',
	'passwordNotLongEnough' => 'Dieses Passwort ist nicht lang genug',
	'passwordNotMatch' => 'Das bestehende Passwort stimmt nicht überein',
	'invalidCountry' => 'Ungültiger Ländercode',

	'accountAlreadyAttached' => 'Entschuldigung, dieses Social-Media-Konto ist bereits mit einem anderen Konto verknüpft.',
	'accountCreationExpired' => 'Entschuldigung, die Bestätigung der Kontoerstellung ist abgelaufen. Bitte melden Sie sich erneut an.',
	'accountPasswordlessRecovery' => 'Leider können Sie ein Konto ohne Passwort nicht wiederherstellen. Bitte verwenden Sie stattdessen ein Drittanbieter-Konto (Google oder GitHub).',
	'accountDeleteLastMethod' => 'Sie können Ihre einzige Anmeldemethode nicht löschen',
	'accountRecountTooFast' => 'Bitte warten Sie einen Moment, bevor Sie es erneut versuchen',
	'accountDeleteNotDangling' => 'Bitte löschen Sie zuerst alle Hosts, Domains und Backups',

	'inviteUserNotFound' => 'Dieser Benutzer wurde nicht gefunden',
	'inviteQuotaFull' => 'Die maximale Anzahl an Teammitgliedern wurde erreicht, bitte upgraden',
	'inviteNewFail' => 'Einladung fehlgeschlagen, wurden sie möglicherweise bereits hinzugefügt?',
	'inviteRemoveFail' => 'Entfernen des Mitglieds fehlgeschlagen, wurde es möglicherweise bereits entfernt?',

	'inviteCodeInvalid' => 'Ungültiger Einladungscode',
	'inviteCodeExpired' => 'Einladungscode abgelaufen',

	'unknownAction' => 'Unbekannte Aktion',
	'hostIsNotActive' => 'Die Aufgabe kann nicht ausgeführt werden, während dieser Host inaktiv ist',
	'needVerifyEmail' => 'Bitte überprüfen Sie zuerst Ihre E-Mail',
	'hostQuotaLimit' => 'Entschuldigung, Sie müssen Ihr Abonnement upgraden, um weitere Hosts zu erstellen. Wenn Sie dies bereits getan haben, überprüfen Sie Ihr Guthaben oder kontaktieren Sie den Support.',
	'usingInternalDomain' => 'Entschuldigung, Sie können unsere Domain hier nicht verwenden',
	'usingSubscibingDomain' => 'Entschuldigung, Sie müssen Ihr Abonnement upgraden, um diese Domain zu verwenden',
	'invalidUsername' => 'Ungültiger Benutzername',
	'invalidDomainname' => 'Ungültiger Domainname',
	'unchangedUsername' => 'Benutzername unverändert',
	'unchangedDomainname' => 'Domainname unverändert',
	'domainAlreadyExist' => 'Domainname existiert bereits',
	'tooShortUsername' => 'Benutzername ist zu kurz',
	'parentNotFound' => 'Elterndomain nicht gefunden',
	'invalidDeployYaml' => 'Ihr Bereitstellungsskript ist kein gültiges YAML: {0}',
	'deploymentFailedToReach' => 'Verbindung zum Server {0} für diese Bereitstellung nicht möglich: {1}',
	'hostRunnerProgressing' => 'Zu schnell! Kann nicht angewendet werden, während die Bereitstellungen noch laufen! Bitte warten Sie einen Moment.',
	'backupNeedSubscribe' => 'Entschuldigung, Sie müssen Ihr Abonnement upgraden, um Backups zu erstellen.',
	'backupIsNotActive' => 'Backup-Status ist inaktiv, möglicherweise wurde es bereits gelöscht',
];
