export default {
    'invoiceDomainPurchaseOf': 'Domainkauf von {0}',
    'invoiceDomainExtendOf': 'Domainverlängerung von {0}',
    'invoiceDomainTransferOf': 'Domaintransfer von {0}',
    'invoiceTeamPurchaseOf': 'Teampaketkauf von {0} Plan',
    'invoiceTeamAddons': 'Team-Erweiterungen',
    'invoiceForMonths': ' für {0, plural, =1{# Monat} other{# Monate}}',
    'invoiceForYears': ' für {0, plural, =1{# Jahr} other{# Jahre}}',
    'invoiceForYearsAndMonths': ' für {0, plural, =1{# Jahr} other{# Jahre}} und {1, plural, =1{# Monat} other{# Monate}}',
    'invoiceDataTransferAddonsFor': 'Zusätzlicher Datenverkehr für {0} GB',
    'invoiceTip': 'Komfortgebühr',
    "listTitle": "Webseitenliste",
    "newOrder": "Eine Webseite hinzufügen",
    "tabDetail": "Info",
    "tabSetup": "Setup",
    "tabManage": "Verwalten",
    "tabRunner": "Bereitstellen",
    "tabWebhook": "Webhook",
    "tabCheck": "Überprüfen",
    "tabConnection": "Verbindung prüfen",
    "tabFirewall": "Firewall prüfen",
    "tabNginx": "NGINX prüfen",
    "tabDns": "DNS prüfen",
    "tabLog": "Logs prüfen",
    "tabAdmin": "Admin",
    "tabRename": "Benutzernamen ändern",
    "tabCname": "Domain ändern",
    "tabPasswd": "Passwort ändern",
    "tabTransfer": "Webseite übertragen",
    "tabDelete": "Webseite löschen",
    "startFromTemplate": "Mit einer Vorlage beginnen",
    "uploadOrClone": "Hochladen oder aus dem Internet klonen",
    "seeMoreTemplates": "Mehr Webvorlagen sehen",
    "customTemplate": "Benutzerdefinierte Vorlage",
    "customDomain": "Benutzerdefinierte Domain",
    "mergeToParentDomain": "Mit übergeordneter Domain zusammenführen",
    "fetchingDomains": "...Domains werden abgerufen",
    "moreTemplates": "Weitere Vorlagen",
    "portalUsername": "Benutzername",
    "portalUsernameHint": "Nur alphanumerisch und Bindestrich",
    "portalPassword": "Passwort",
    "slaveServer": "Region",
    "scheme": "Plan",
    "usage": "Nutzung",
    "month": "Monate",
    "year": "Jahr(e)",
    "free": "Kostenlos",
    "database": "Datenbank",
    "additionalServices": "Zusätzliche Dienstleistungen",
    "softwareCompilers": "Software-Compiler",
    "enableNewFeatures": "Neue Funktionen aktivieren",
    "addHost": "Eine Webseite hinzufügen",
    "emptyList": "Keine Webseite aufgelistet",
    "waitForDataHint": "Die Ressourcennutzung wird hier angezeigt. Kommen Sie am nächsten Tag wieder, um die Daten zu sehen.",
    "slaveID": "Slave-ID",
    "IPAddress": "IP-Adresse",
    "openWebsite": "Webseite öffnen",
    "openPortal": "Portal öffnen",
    "hostStatus": "Host-Status",
    "creationDate": "Erstellungsdatum",
    "usernameHost": "Host-Benutzername",
    "domainHost": "Host-Domain",
    "manageHostLogin": "Host-Login verwalten",
    "total": "Gesamt",
    "used": "Verbraucht",
    "remainingMonthlyPlan": "Verbleibender monatlicher Plan",
    "remainingAddons": "Verbleibende Add-Ons",
    "planDetail": "{0} Plan, {1} Speicherplatz, {2} monatliche Bandbreite.",
    "emptyForDefaultCname": "Leer lassen für Standard ({0})",
    "redeploy": "Erneut bereitstellen",
    "debugManually": "Manuell debuggen",
    "startOver": "Von vorne beginnen",
    "deployScript": "Skript bereitstellen",
    "deployAdd": "Einen Bereitstellungsauftrag hinzufügen",
    "deployNow": "Ausführen!",
    "deployClearHint": "Alle Logs löschen?",
    "websiteReadyHint": "Ihre Seite ist fertig. Jetzt versuchen zu besuchen?",
    "deployByAdmin": "Vom System-Admin ausgeführt",
    "deployOverwriteBanner": "Dieses Skript wird alle Dateien dieser Webseite ersetzen!",
    "deployOverwriteWarn": "Sie haben den Parameter source erwähnt, was bedeutet, dass Ihre HOME-Datei DAUERHAFT ÜBERSCHRIEBEN wird. Diese Aktion kann nicht rückgängig gemacht werden. Sind Sie sicher?",
    "deployHelpBtn": "Bereitstellungskonfigurationsreferenz",
    "githubWebhook": "Webhook einrichten",
    "githubWebhookTitle": "GitHub-Action einrichten",
    "githubWebhookHelp": "Sie können diesen Webhook verwenden, um Ihre Webseite automatisch bereitzustellen, wenn Sie auf GitHub pushen.",
    "githubWebhookHelpBtn": "GitHub-Action-Webhooks-Hilfe",
    "noWebhook": "Es sind keine Webhooks für diesen Host konfiguriert.",
    "noGitHubApi": "GitHub-API ist nicht verfügbar",
    "noGitHubApiToken": "GitHub-API-Token nicht gefunden",
    "noGitHubApiHint": "Sie müssen zuerst ein GitHub-Konto mit vollem Repo-Zugriff verknüpfen.",
    "noGitHubApiLink": "Jetzt GitHub verknüpfen",
    "noRepo": "Kein Repository gefunden",
    "noRepoHint": "Versuchen Sie, Ihre Suche einzugrenzen",
}
