<?php return [
    'code' => 'de',
    'codename' => 'Deutsch',
    'login' => 'Anmelden',
    'register' => 'Registrieren',
    'email' => 'E-Mail',
    'enterToPortal' => 'Zum Portal',
    'registerToPortal' => 'Zum Portal registrieren',
    'registerWithEmail' => 'Mit E-Mail registrieren',
    'forgotPrompt' => 'Passwort vergessen?',
    'recoverYourPassword' => 'Passwort wiederherstellen',
    'recoverYourPasswordHint' => 'Geben Sie ein neues Passwort ein, um es zu ändern',
    'report' => 'Melden',
    'reportPrompt' => 'Melden Sie verdächtige Aktivitäten im DOM Cloud-Netzwerk. Inhalte werden sofort entfernt, wenn die gemeldete Website unsere Kriterien erfüllt.',
    'reportAbuse' => 'Missbrauch melden',
    'reportDomain' => 'Zu meldende Domain',
    'ok' => 'OK',
    'back' => 'Zurück',
    'or' => 'Oder',
    'signInWith' => 'Anmelden mit {0}',
    'wrongLogin' => 'Falsche E-Mail oder falsches Passwort',
    'registerAgreement' => 'Durch die Registrierung stimmen Sie unseren <a href="//domcloud.co/service" target="_blank">Nutzungsbedingungen</a> zu.',
    'emailSent' => 'Die Bestätigungs-E-Mail wurde gesendet, bitte überprüfen Sie Ihr Postfach (und den Spam-Ordner), bevor Sie sich anmelden.',
    'oAuthFail' => 'Es scheint, dass Ihr Versuch mit der Anmeldung über Drittanbieter fehlgeschlagen ist. Dies wird häufig durch eine Zeitüberschreitung oder eine nicht verifizierte primäre E-Mail-Adresse verursacht.',
    'passReset' => 'Ihr Passwort wurde erfolgreich zurückgesetzt. Bitte melden Sie sich mit Ihrem neuen Passwort an.',
    'thanksForVerify' => 'Danke, Ihre E-Mail wurde verifiziert',
    'password' => 'Passwort',
    'passwordAgain' => 'Passwort (nochmal)',
    'fullName' => 'Vollständiger Name',
    'activeEmail' => 'Aktive E-Mail',
];
