export default {
    "logout": "Abmelden",
    "profile": "Profil",
    "status": "Status",
    "verifyStatus": "Verifizierungsstatus",
    "bannedHint": "Dein Konto wurde gesperrt, Entschuldigung.",
    "hosting": "Webseite",
    "domain": "Domain",
    "backup": "Sicherung",
    "owner": "Eigentümer",
    "admin": "Admin",
    "member": "Mitglied",
    "team": "Team",
    "email": "E-Mail",
    "storage": "Speicher",
    "bandwidth": "Bandbreite",
    "instances": "Instanzen",
    "users": "Benutzer",
    "details": "Details",
    "members": "Mitglieder",
    "upgrade": "Upgrade",
    "otherTeams": "Andere Teams",
    "inviteCode": "Einladungscode",
    "hostname": "Hostname",
    "port": "Port",
    "username": "Benutzername",
    "password": "Passwort",
    "server": "Server",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "redis": "Redis",
    "mysql2": "MySQL (MariaDB)",
    "redis2": "Redis (Valkey)",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "phprdadmin": "phpRdAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    "help": "Hilfe",
    "helpDocs": "Dokumentation",
    "helpEmail": "E-Mail",
    "helpForum": "Forum",
    "helpChat": "Chat",
    "helpUpdates": "Updates",
    "country": "Land",
    "chooseCountry": "Land auswählen",
    "expiration": "Ablaufdatum",
    "resendConfirmationEmail": "Bestätigungs-E-Mail erneut senden",
    "learnMore": "Mehr erfahren",
    "passwordNotice": "Sie müssen sich dieses Passwort nicht merken",
    "lastUpdatedAt": "Zuletzt aktualisiert am",
    "language": "Sprache",
    "theme": "Thema",
    "themeDark": "Immer Dunkel",
    "themeLight": "Immer Hell",
    "themeSystem": "Systemstandard",
    "role": "Rolle",
    "action": "Aktion",
    "currencyInput": "Währung",
    "invoiceNoteInput": "Rechnungskontakt",
    "defaultServerInput": "Standardserver",
    "defaultServerInputNone": "Keiner (fragen Sie mich)",
    "name": "Name",
    "phone": "Telefonnummer",
    "phoneHint": "Vollständig qualifizierte Telefonnummer (beginnt mit +)",
    "phoneAlt": "Alternative Telefonnummer",
    "fullName": "Vollständiger Name",
    "companyName": "Firmenname",
    "activeEmail": "Aktive E-Mail",
    "newPassword": "Neues Passwort",
    "editProfile": "Profil bearbeiten",
    "saveProfile": "Profil speichern",
    "deleteAccount": "Konto löschen",
    "loginMethods": "Anmeldemethoden",
    "loginRemoveConfirm": "Möchten Sie diese Anmeldemethode wirklich entfernen?",
    "loginAdd": "Anmeldemethode hinzufügen oder ersetzen",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "E-Mail + Passwort",
    "loginVia": "über {0}",
    "passwordConfirm": "Aktuelles Konto-Passwort eingeben (falls vorhanden)",
    "passwordSetInput": "Neues Passwort eingeben, muss mindestens 8 Zeichen lang sein",
    "passwordSetCancel": "Passwort für dieses Konto wurde abgebrochen",
    "passwordSetCancelLength": "Passworteinstellung abgebrochen, muss mindestens 8 Zeichen lang sein",
    "yearDuration": "Dauer in Jahren",
    "monthDuration": "Dauer in Monaten",
    "annualSaving": "16% sparen",
    "totalPayment": "Gesamtzahlung",
    "expirationDate": "Ablaufdatum",
    "orderNow": "Jetzt bestellen",
    "invoice": "Rechnung",
    "pendingInvoices": "Ausstehende Rechnungen",
    "noPendingInvoices": "Sie haben derzeit keine ausstehenden Rechnungen.",
    "mixedCurrency": "Ausgewählte Rechnungen haben gemischte Währungen",
    "currentPlan": "Aktueller Plan",
    "currentPlanDescription": "Mit Kosten von <b>{0}</b> pro Monat mit Ablauf <b>{1}</b>",
    "priceDescription": "{0} / Monat",
    "monthlyLimits": "Monatliche Limits",
    "storageLimit": "{0} GB Speicher",
    "networkLimit": "{0} GB Netzwerk",
    "instanceLimit": "{0} {0, plural, one {Instanz} other {Instanzen}}",
    "userLimit": "{0} {0, plural, one {Benutzer} other {Benutzer}}",
    "autoStop": "Automatisches Stoppen bei Limits",
    "noFreeDomain": "Keine {0} Domain",
    "withFreeDomain": "Kostenlose {0} Domain",
    "withBackup": "Automatische serverseitige Sicherung",
    "withDocker": "Docker und langlaufende Anwendungen",
    "storageUsage": "Speichernutzung",
    "storageUsageCap": "von insgesamt {0}",
    "bandwidthUsed": "Verwendete Bandbreite",
    "bandwidthUsedCap": "von monatlich {0}",
    "instancesActive": "Aktive Instanzen",
    "instancesActiveCap": "von {0} Webseiten",
    "teamUsers": "Team-Benutzer",
    "teamUsersCap": "von maximal {0} Benutzern",
    "remainingAvailable": "Verbleibend verfügbar",
    "remainingStorage": "Freier Speicher",
    "remainingNetwork": "Netzwerkdaten",
    "remainingInstance": "Verbleibende Instanz",
    "dataTransfer": "Datenübertragung",
    "copy": "Kopieren",
    "copied": "Kopiert!",
    "reloading": "Wird neu geladen {0}",
    "expires": "Läuft ab {0}",
    "expiresAt": "Läuft ab am {0}",
    "expireFreeHint": `
Ablaufdaten werden automatisch verlängert (um 3 Monate verlängert) 
jedes Mal, wenn Sie sich einloggen oder Ihre Webseiten genügend Netzwerkverkehr haben (>50 MB)
am Monatsende.
`,
    "discountedAt": "Rabattiert bei {0}",
    "extendingCurrentExpiryDate": "Aktuelles Ablaufdatum verlängern",
    "usersLimitHint": "{0} {0, plural, one {Benutzer} other {Benutzer}} in diesem Team, {1} {1, plural, one {Benutzer} other {Benutzer}} können noch hinzugefügt werden",
    "emailToInvite": "E-Mail zum Einladen",
    "selectRole": "Rolle auswählen",
    "info": "Info",
    "total": "Gesamt",
    "back": "Zurück",
    "add": "Hinzufügen",
    "addMember": "Mitglied hinzufügen",
    "confirmRemoveMember": "Sind Sie sicher, dass Sie dieses Mitglied entfernen möchten?",
    "edit": "Bearbeiten",
    "apply": "Anwenden",
    "save": "Speichern",
    "clear": "Löschen",
    "update": "Aktualisieren",
    "updateUsage": "Nutzung aktualisieren",
    "change": "Ändern",
    "archives": "Archive",
    "renew": "Erneuern",
    "extend": "Verlängern",
    "topup": "Aufladen",
    "processing": "Wird verarbeitet",
    "cancel": "Abbrechen",
    "print": "Drucken",
    "delete": "Löschen",
    "why": "Warum?",
    "pay": "Bezahlen",
    "payAccept": "Wir akzeptieren Zahlungen über",
    "loading": "Daten werden gesammelt...",
    "fetchError": "Fehler beim Abrufen der Daten! Versuchen Sie es später noch einmal",
    "notFound": "Nicht gefunden",
    "notFoundDescription": "Die Seite, die Sie suchen, existiert nicht.",
    "notFoundLink": "Zurück zur Startseite"
}
