<?php return [
       'emailAlreadyExist' => 'Questa email esiste già',
	   'passwordNotLongEnough' => 'Questa password non è abbastanza lunga',
	   'passwordNotMatch' => 'La password esistente non corrisponde',
	   'invalidCountry' => 'Codice paese non valido',

	   'accountAlreadyAttached' => 'Spiacente, questo account social è già collegato a un altro account.',
	   'accountCreationExpired' => 'Spiacente, sembra che stiamo cercando di confermare la creazione del tuo account, ma la sessione è scaduta. Prova a effettuare nuovamente l\'accesso.',
	   'accountPasswordlessRecovery' => 'Purtroppo non è possibile recuperare un account senza password. Prova a utilizzare un account di terze parti (Google o GitHub).',
	   'accountDeleteLastMethod' => 'Non puoi eliminare il tuo unico metodo di accesso',
	   'accountRecountTooFast' => 'Attendi un momento prima di riprovare',
	   'accountDeleteNotDangling' => 'Elimina prima tutti gli host, i domini e i backup',

	   'inviteUserNotFound' => 'Questo utente non è stato trovato',
	   'inviteQuotaFull' => 'Il numero massimo di membri del team è stato raggiunto, aggiorna il piano',
	   'inviteNewFail' => 'Impossibile invitare, forse è già stato aggiunto?',
	   'inviteRemoveFail' => 'Impossibile rimuovere il membro, forse è già stato rimosso?',

	   'inviteCodeInvalid' => 'Codice di invito non valido',
	   'inviteCodeExpired' => 'Codice di invito scaduto',

	   'unknownAction' => 'Azione sconosciuta',
	   'hostIsNotActive' => 'Impossibile eseguire l\'attività mentre questo host non è attivo',
	   'needVerifyEmail' => 'Verifica prima la tua email',
	   'hostQuotaLimit' => 'Spiacente, devi aggiornare il tuo piano per creare più host. Se lo hai già fatto, controlla il saldo o contatta l\'assistenza.',
	   'usingInternalDomain' => 'Spiacente, non puoi utilizzare il nostro dominio qui',
	   'usingSubscibingDomain' => 'Spiacente, devi aggiornare il tuo piano per utilizzare questo dominio',
	   'invalidUsername' => 'Nome utente non valido',
	   'invalidDomainname' => 'Nome di dominio non valido',
	   'unchangedUsername' => 'Nome utente invariato',
	   'unchangedDomainname' => 'Nome di dominio invariato',
	   'domainAlreadyExist' => 'Il nome di dominio esiste già',
	   'tooShortUsername' => 'Nome utente troppo breve',
	   'parentNotFound' => 'Dominio genitore non trovato',
	   'invalidDeployYaml' => 'Il tuo script di distribuzione non è un YAML valido: {0}',
	   'deploymentFailedToReach' => 'Non siamo riusciti a contattare il server {0} per questa distribuzione: {1}',
	   'hostRunnerProgressing' => 'Troppo veloce! Impossibile applicare mentre sono in corso distribuzioni. Attendi un momento.',
	   'backupNeedSubscribe' => 'Spiacente, devi aggiornare il tuo piano per creare backup.',
	   'backupIsNotActive' => 'Lo stato del backup non è attivo, forse è già stato rimosso.',
];
