export default {
    "status": {
        "active": "Attivo",
        "starting": "In avvio",
        "suspended": "Sospeso",
        "moving": "In movimento",
        "removing": "Rimozione in corso",
        "removed": "Rimosso"
    },
    "listTitle": "Elenco dei siti web",
    "newOrder": "Aggiungi un sito web",
    "tabDetail": "Info",
    "tabSetup": "Configurazione",
    "tabManage": "Gestisci",
    "tabRunner": "Distribuisci",
    "tabDatabase": "Database",
    "tabSubdomain": "Sottodominio",
    "tabSoftware": "Software",
    "tabWebhook": "Webhook",
    "tabCheck": "Controlla",
    "tabConnection": "Controlla connessione",
    "tabFirewall": "Controlla firewall",
    "tabNginx": "Controlla NGINX",
    "tabDns": "Controlla DNS",
    "tabLog": "Controlla log",
    "tabUser": "Controlla Utente",
    "tabAdmin": "Admin",
    "tabRename": "Cambia nome utente",
    "tabCname": "Cambia dominio",
    "tabPasswd": "Cambia password",
    "tabServer": "Cambia regione",
    "tabTransfer": "Trasferisci sito web",
    "tabDelete": "Elimina sito web",
    "startFromTemplate": "Inizia da un modello",
    "uploadOrClone": "Carica o clona da Internet",
    "seeMoreTemplates": "Vedi più modelli web",
    "customTemplate": "Modello personalizzato",
    "customDomain": "Dominio personalizzato",
    "mergeToParentDomain": "Unisci al dominio principale",
    "fetchingDomains": "...Recupero dei domini",
    "moreTemplates": "Più modelli",
    "portalUsername": "Nome utente",
    "portalUsernameHint": "Solo alfanumerici e trattini",
    "portalPassword": "Password",
    "serverName": "Regione",
    "scheme": "Piano",
    "usage": "Utilizzo",
    "month": "Mesi",
    "year": "Anno/i",
    "free": "Gratuito",
    "database": "Database",
    "additionalServices": "Servizi aggiuntivi",
    "softwareCompilers": "Compilatori software",
    "enableNewFeatures": "Abilita nuove funzionalità",
    "addHost": "Aggiungi un sito web",
    "emptyList": "Nessun sito web elencato",
    "waitForDataHint": "L'utilizzo delle risorse apparirà qui",
    "IPAddress": "Indirizzo IP",
    "openWebsite": "Apri sito web",
    "openPortal": "Apri portale",
    "creationDate": "Data di creazione",
    "websiteStatus": "Stato del Sito Web",
    "websiteUsername": "Nome Utente del Sito Web",
    "websiteDomain": "Dominio del Sito Web",
    "manageHostLogin": "Gestisci login host",
    "total": "Totale",
    "used": "Utilizzato",
    "remainingMonthlyPlan": "Piano mensile rimanente",
    "remainingAddons": "Componenti aggiuntivi rimanenti", 
    "createDatabase": "Crea Database {0}",
    "createDatabaseHint": "Inserisci il nuovo nome del database {0}",
    "createDatabaseConfirm": "Verrà creato \"{0}\", continuare?",
    "dropDatabase": "Elimina Database {0}",
    "dropDatabaseConfirm": "Verrà eliminato \"{0}\", continuare?",
    "dropDatabaseConfirm2": "Sei sicuro di voler eseguire \"{0}\"? Questa azione non può essere annullata.",
    "tables": "{0} {0, plural, one {tabella} other {tabelle}}",
    "noSubdomain": "Si prega di utilizzare un dominio personalizzato per creare sottodomini",
    "createSubdomain": "Crea un nuovo sottodominio",
    "deleteSubdomain": "Elimina sottodominio {0}",
    "deleteSubdomainConfirm": "Verrà eliminato il sottodominio \"{0}\", continuare?",
    "deleteSubdomainConfirm2": "Sei sicuro di voler eseguire \"{0}\"? Questa azione non può essere annullata.",
    "enterFullDomainName": "Inserisci il nome completo del dominio",
    "useDefaultCname": "Usa il nome di dominio predefinito ({0})",
    "useDifferentPassword": "Usa una password diversa per {0}",
    "redeploy": "Ridispiega",
    "debugManually": "Debug manualmente",
    "startOver": "Ricomincia",
    "deployScript": "Deploy dello script",
    "deployAdd": "Aggiungi un'attività di distribuzione",
    "deployNow": "Esegui!",
    "deployClearHint": "Cancellare tutti i log?",
    "websiteReadyHint": "Il tuo sito è pronto. Prova a visitarlo ora?",
    "deployByAdmin": "Eseguito dal moderatore di sistema",
    "deployOverwriteBanner": "Questo script sostituirà tutti i file di questo sito web!",
    "deployOverwriteWarn": "Hai menzionato il parametro source, il che significa che il tuo file HOME sarà PERMANENTEMENTE SOVRASCRITTO. Questa azione non può essere annullata. Sei sicuro?",
    "deployHelpBtn": "Riferimento configurazione distribuzione",
    "githubWebhook": "Configura webhook",
    "githubWebhookTitle": "Configura azione GitHub",
    "githubWebhookHelp": "Puoi usare questo webhook per distribuire automaticamente il tuo sito web quando fai push su GitHub.",
    "githubWebhookHelpBtn": "Guida webhook azione GitHub",
    "noWebhook": "Non ci sono webhook configurati per questo host.",
    "noGitHubApi": "API GitHub non disponibile",
    "noGitHubApiToken": "Token API GitHub non trovato",
    "noGitHubApiHint": "Devi prima collegare un account GitHub con accesso completo al repo.",
    "noGitHubApiLink": "Collega GitHub ora",
    "noRepo": "Nessun repository trovato",
    "noRepoHint": "Prova a restringere la tua ricerca",
}
