export default {
    'invoiceDomainPurchaseOf': 'Acquisto di dominio di {0}',
    'invoiceDomainExtendOf': 'Estensione di dominio di {0}',
    'invoiceDomainTransferOf': 'Trasferimento di dominio di {0}',
    'invoiceTeamPurchaseOf': 'Acquisto del team del piano {0}',
    'invoiceTeamAddons': 'Componenti aggiuntivi del team',
    'invoiceForMonths': ' per {0, plural, =1{# mese} other{# mesi}}',
    'invoiceForYears': ' per {0, plural, =1{# anno} other{# anni}}',
    'invoiceForYearsAndMonths': ' per {0, plural, =1{# anno} other{# anni}} e {1, plural, =1{# mese} other{# mesi}}',
    'invoiceDataTransferAddonsFor': 'Trasferimento dati aggiuntivo per {0} GB',
    'invoiceTip': 'Commissione di convenienza',
    "listTitle": "Elenco dei siti web",
    "newOrder": "Aggiungi un sito web",
    "tabDetail": "Info",
    "tabSetup": "Configurazione",
    "tabManage": "Gestisci",
    "tabRunner": "Distribuisci",
    "tabWebhook": "Webhook",
    "tabCheck": "Controlla",
    "tabConnection": "Controlla connessione",
    "tabFirewall": "Controlla firewall",
    "tabNginx": "Controlla NGINX",
    "tabDns": "Controlla DNS",
    "tabLog": "Controlla log",
    "tabAdmin": "Admin",
    "tabRename": "Cambia nome utente",
    "tabCname": "Cambia dominio",
    "tabPasswd": "Cambia password",
    "tabServer": "Cambia regione",
    "tabTransfer": "Trasferisci sito web",
    "tabDelete": "Elimina sito web",
    "startFromTemplate": "Inizia da un modello",
    "uploadOrClone": "Carica o clona da Internet",
    "seeMoreTemplates": "Vedi più modelli web",
    "customTemplate": "Modello personalizzato",
    "customDomain": "Dominio personalizzato",
    "mergeToParentDomain": "Unisci al dominio principale",
    "fetchingDomains": "...Recupero dei domini",
    "moreTemplates": "Più modelli",
    "portalUsername": "Nome utente",
    "portalUsernameHint": "Solo alfanumerici e trattini",
    "portalPassword": "Password",
    "slaveServer": "Regione",
    "scheme": "Piano",
    "usage": "Utilizzo",
    "month": "Mesi",
    "year": "Anno/i",
    "free": "Gratuito",
    "database": "Database",
    "additionalServices": "Servizi aggiuntivi",
    "softwareCompilers": "Compilatori software",
    "enableNewFeatures": "Abilita nuove funzionalità",
    "addHost": "Aggiungi un sito web",
    "emptyList": "Nessun sito web elencato",
    "waitForDataHint": "L'utilizzo delle risorse apparirà qui. Torna il giorno successivo per visualizzare i dati.",
    "slaveID": "ID Slave",
    "IPAddress": "Indirizzo IP",
    "openWebsite": "Apri sito web",
    "openPortal": "Apri portale",
    "hostStatus": "Stato host",
    "creationDate": "Data di creazione",
    "usernameHost": "Nome utente host",
    "domainHost": "Dominio host",
    "manageHostLogin": "Gestisci login host",
    "total": "Totale",
    "used": "Utilizzato",
    "remainingMonthlyPlan": "Piano mensile rimanente",
    "remainingAddons": "Componenti aggiuntivi rimanenti",
    "planDetail": "Piano {0}, {1} spazio su disco, {2} larghezza di banda mensile.",
    "emptyForDefaultCname": "Lascia vuoto per impostazione predefinita ({0})",
    "redeploy": "Ridispiega",
    "debugManually": "Debug manualmente",
    "startOver": "Ricomincia",
    "deployScript": "Deploy dello script",
    "deployAdd": "Aggiungi un'attività di distribuzione",
    "deployNow": "Esegui!",
    "deployClearHint": "Cancellare tutti i log?",
    "websiteReadyHint": "Il tuo sito è pronto. Prova a visitarlo ora?",
    "deployByAdmin": "Eseguito dal moderatore di sistema",
    "deployOverwriteBanner": "Questo script sostituirà tutti i file di questo sito web!",
    "deployOverwriteWarn": "Hai menzionato il parametro source, il che significa che il tuo file HOME sarà PERMANENTEMENTE SOVRASCRITTO. Questa azione non può essere annullata. Sei sicuro?",
    "deployHelpBtn": "Riferimento configurazione distribuzione",
    "githubWebhook": "Configura webhook",
    "githubWebhookTitle": "Configura azione GitHub",
    "githubWebhookHelp": "Puoi usare questo webhook per distribuire automaticamente il tuo sito web quando fai push su GitHub.",
    "githubWebhookHelpBtn": "Guida webhook azione GitHub",
    "noWebhook": "Non ci sono webhook configurati per questo host.",
    "noGitHubApi": "API GitHub non disponibile",
    "noGitHubApiToken": "Token API GitHub non trovato",
    "noGitHubApiHint": "Devi prima collegare un account GitHub con accesso completo al repo.",
    "noGitHubApiLink": "Collega GitHub ora",
    "noRepo": "Nessun repository trovato",
    "noRepoHint": "Prova a restringere la tua ricerca",
}
