export default {
    "logout": "Disconnettersi",
    "profile": "Profilo",
    "status": "Stato",
    "verifyStatus": "Stato della verifica",
    "bannedHint": "Il tuo account è stato bloccato, mi dispiace.",
    "hosting": "Sito web",
    "domain": "Dominio",
    "backup": "Backup",
    "owner": "Proprietario",
    "admin": "Amministratore",
    "member": "Membro",
    "team": "Squadra",
    "email": "Email",
    "storage": "Archiviazione",
    "bandwidth": "Larghezza di banda",
    "instances": "Istanze",
    "users": "Utenti",
    "details": "Dettagli",
    "members": "Membri",
    "upgrade": "Aggiornamento",
    "otherTeams": "Altre squadre",
    "inviteCode": "Codice di Invito",
    "hostname": "Nome host",
    "port": "Porta",
    "username": "Nome utente",
    "password": "Password",
    "server": "Server",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "redis": "Redis",
    "mysql2": "MySQL (MariaDB)",
    "redis2": "Redis (Valkey)",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "phprdadmin": "phpRdAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    "help": "Aiuto",
    "helpDocs": "Documenti",
    "helpEmail": "Email",
    "helpForum": "Forum",
    "helpChat": "Chat",
    "helpUpdates": "Aggiornamenti",
    "country": "Paese",
    "chooseCountry": "Scegli un paese",
    "expiration": "Scadenza",
    "resendConfirmationEmail": "Invia di nuovo l'email di conferma",
    "learnMore": "Per saperne di più",
    "passwordNotice": "Non è necessario ricordare questa password",
    "lastUpdatedAt": "Ultimo aggiornamento a",
    "language": "Lingua",
    "theme": "Tema",
    "themeDark": "Sempre scuro",
    "themeLight": "Sempre chiaro",
    "themeSystem": "Predefinito di sistema",
    "role": "Ruolo",
    "action": "Azione",
    "currencyInput": "Valuta",
    "invoiceNoteInput": "Contatto fattura",
    "defaultServerInput": "Server predefinito",
    "defaultServerInputNone": "Nessuno (chiedimi)",
    "name": "Nome",
    "phone": "Numero di telefono",
    "phoneHint": "Numero di telefono completo (inizia con +)",
    "phoneAlt": "Numero di telefono alternativo",
    "fullName": "Nome completo",
    "companyName": "Nome dell'azienda",
    "activeEmail": "Email attiva",
    "newPassword": "Nuova password",
    "editProfile": "Modifica profilo",
    "saveProfile": "Salva profilo",
    "deleteAccount": "Elimina account",
    "loginMethods": "Metodi di accesso",
    "loginRemoveConfirm": "Sei sicuro di voler rimuovere questo metodo di accesso?",
    "loginAdd": "Aggiungi o sostituisci un metodo di accesso",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "Email + Password",
    "loginVia": "tramite {0}",
    "passwordConfirm": "Inserisci la password attuale dell'account (se presente)",
    "passwordSetInput": "Inserisci una nuova password, deve essere di almeno 8 caratteri",
    "passwordSetCancel": "L'impostazione della password per questo account è stata annullata",
    "passwordSetCancelLength": "L'impostazione della password annullata, deve essere di almeno 8 caratteri",
    "yearDuration": "Durata in anni",
    "monthDuration": "Durata in mesi",
    "annualSaving": "Risparmia il 16%",
    "totalPayment": "Pagamento totale",
    "expirationDate": "Data di scadenza",
    "orderNow": "Ordina ora",
    "invoice": "Fattura",
    "pendingInvoices": "Fatture in sospeso",
    "noPendingInvoices": "Attualmente non hai fatture in sospeso.",
    "mixedCurrency": "Le fatture selezionate hanno valute miste",
    "currentPlan": "Piano attuale",
    "currentPlanDescription": "Con un costo di <b>{0}</b> al mese con scadenza il <b>{1}</b>",
    "priceDescription": "{0} / mese",
    "monthlyLimits": "Limiti mensili",
    "storageLimit": "{0} GB di archiviazione",
    "networkLimit": "{0} GB di rete",
    "instanceLimit": "{0} {0, plural, one {Istanza} other {Istanze}}",
    "userLimit": "{0} {0, plural, one {Utente} other {Utenti}}",
    "autoStop": "Arresto automatico ai limiti",
    "noFreeDomain": "Nessun dominio *.domcloud.dev",
    "withFreeDomain": "Dominio gratuito *.domcloud.dev",
    "withBackup": "Backup automatico a livello di server",
    "withDocker": "Docker e applicazioni a lungo termine",
    "storageUsage": "Utilizzo di archiviazione",
    "storageUsageCap": "su {0} in totale",
    "bandwidthUsed": "Larghezza di banda utilizzata",
    "bandwidthUsedCap": "su {0} mensili",
    "instancesActive": "Istanze attive",
    "instancesActiveCap": "su {0} siti web",
    "teamUsers": "Utenti del team",
    "teamUsersCap": "su un massimo di {0} utenti",
    "remainingAvailable": "Rimanente disponibile",
    "remainingStorage": "Archiviazione libera",
    "remainingNetwork": "Dati di rete",
    "remainingInstance": "Istanza rimanente",
    "dataTransfer": "Trasferimento dati",
    "copy": "Copia",
    "copied": "Copiato!",
    "reloading": "Ricaricamento {0}",
    "expires": "Scade il {0}",
    "expiresAt": "Scade alle {0}",
    "expireFreeHint": `
Le date di scadenza vengono automaticamente rinnovate (estese di 3 mesi) 
ogni volta che accedi o i tuoi siti web hanno abbastanza traffico di rete (>50 MB)
alla fine del mese.
`,
    "discountedAt": "Scontato a {0}",
    "extendingCurrentExpiryDate": "Estensione della data di scadenza attuale",
    "usersLimitHint": "{0} {0, plural, one {utente} other {utenti}} in questa squadra, {1} {1, plural, one {utente} other {utenti}} possono ancora essere aggiunti",
    "emailToInvite": "Email per invitare",
    "selectRole": "Seleziona il ruolo",
    "info": "Informazioni",
    "total": "Totale",
    "back": "Indietro",
    "add": "Aggiungi",
    "addMember": "Aggiungi un membro",
    "confirmRemoveMember": "Sei sicuro di voler rimuovere questo membro?",
    "edit": "Modifica",
    "apply": "Applica",
    "save": "Salva",
    "clear": "Cancella",
    "update": "Aggiorna",
    "updateUsage": "Aggiorna utilizzo",
    "change": "Cambia",
    "archives": "Archivi",
    "renew": "Rinnova",
    "extend": "Estendi",
    "topup": "Ricarica",
    "processing": "Elaborazione",
    "cancel": "Annulla",
    "print": "Stampa",
    "delete": "Elimina",
    "why": "Perché?",
    "pay": "Paga",
    "payAccept": "Accettiamo pagamenti tramite",
    "loading": "Recupero dei dati...",
    "fetchError": "Errore nel recupero dei dati! Riprova più tardi",
    "notFound": "Non trovato",
    "notFoundDescription": "La pagina che stai cercando non esiste.",
    "notFoundLink": "Torna alla home page"
}
