<?php return [
    'code' => 'it',
    'codename' => 'Italiano',
    'codedir' => 'ltr',
    'login' => 'Accedi',
    'register' => 'Registrati',
    'email' => 'E-mail',
    'enterToPortal' => 'Entra nel Portale',
    'registerToPortal' => 'Registrati nel Portale',
    'registerWithEmail' => 'Registrati con E-mail',
    'forgotPrompt' => 'Password dimenticata?',
    'recoverYourPassword' => 'Recupera la tua password',
    'recoverYourPasswordHint' => 'Inserisci una nuova password per cambiare',
    'report' => 'Segnala',
    'reportPrompt' => 'Segnala attività sospette all’interno della rete DOM Cloud. Il contenuto verrà immediatamente rimosso se il sito segnalato soddisfa i nostri criteri.',
    'reportAbuse' => 'Segnala contenuto abusivo',
    'reportDomain' => 'Dominio da segnalare',
    'ok' => 'OK',
    'back' => 'Indietro',
    'or' => 'O',
    'signInWith' => 'Accedi con {0}',
    'wrongLogin' => 'E-mail o password errata',
    'registerAgreement' => 'Registrandoti accetti i nostri <a href="//domcloud.co/service" target="_blank">Termini di servizio</a>.',
    'emailSent' => 'L’e-mail di verifica è stata inviata, controlla la tua casella di posta (e la cartella spam) prima di accedere.',
    'oAuthFail' => 'Sembra che il tuo tentativo di accesso tramite terzi sia fallito. Questo è comunemente causato da un timeout o dall’indirizzo e-mail principale legato a quell’account non ancora verificato.',
    'passReset' => 'La tua password è stata reimpostata con successo. Effettua l’accesso con la tua nuova password.',
    'thanksForVerify' => 'Grazie, la tua e-mail è stata verificata',
    'password' => 'Password',
    'passwordAgain' => 'Password (di nuovo)',
    'fullName' => 'Nome completo',
    'activeEmail' => 'E-mail attiva',
];
