export default {
    'invoiceDomainPurchaseOf': '{0} का डोमेन खरीद',
    'invoiceDomainExtendOf': '{0} का डोमेन विस्तार',
    'invoiceDomainTransferOf': '{0} का डोमेन ट्रांसफर',
    'invoiceTeamPurchaseOf': '{0} योजना का टीम खरीद',
    'invoiceTeamAddons': 'टीम ऐड-ऑन',
    'invoiceForMonths': ' {0, plural, =1{# माह} other{# माह}} के लिए',
    'invoiceForYears': ' {0, plural, =1{# वर्ष} other{# वर्ष}} के लिए',
    'invoiceForYearsAndMonths': ' {0, plural, =1{# वर्ष} other{# वर्ष}} और {1, plural, =1{# माह} other{# माह}} के लिए',
    'invoiceDataTransferAddonsFor': '{0} GB के अतिरिक्त डेटा ट्रांसफर के लिए',
    'invoiceTip': 'सुविधा शुल्क',
    "listTitle": "वेबसाइट सूची",
    "newOrder": "एक वेबसाइट जोड़ें",
    "tabDetail": "जानकारी",
    "tabSetup": "सेटअप",
    "tabManage": "प्रबंधित करें",
    "tabRunner": "परिनियोजित करें",
    "tabWebhook": "Webhook",
    "tabCheck": "जाँच",
    "tabConnection": "कनेक्शन जाँचें",
    "tabFirewall": "फ़ायरवॉल जाँचें",
    "tabNginx": "NGINX जाँचें",
    "tabDns": "DNS जाँचें",
    "tabLog": "लॉग्स जाँचें",
    "tabAdmin": "प्रशासन",
    "tabRename": "उपयोगकर्ता नाम बदलें",
    "tabCname": "डोमेन बदलें",
    "tabPasswd": "पासवर्ड बदलें",
    "tabTransfer": "वेबसाइट ट्रांसफर करें",
    "tabDelete": "वेबसाइट हटाएं",
    "startFromTemplate": "एक टेम्पलेट से शुरू करें",
    "uploadOrClone": "इंटरनेट से अपलोड या क्लोन करें",
    "seeMoreTemplates": "अधिक वेब टेम्पलेट्स देखें",
    "customTemplate": "कस्टम टेम्पलेट",
    "customDomain": "कस्टम डोमेन",
    "mergeToParentDomain": "मूल डोमेन के साथ विलय करें",
    "fetchingDomains": "...डोमेनों को लाया जा रहा है",
    "moreTemplates": "अधिक टेम्पलेट्स",
    "portalUsername": "उपयोगकर्ता नाम",
    "portalUsernameHint": "केवल अल्फान्यूमेरिक और हाइफ़न",
    "portalPassword": "पासवर्ड",
    "slaveServer": "क्षेत्र",
    "scheme": "योजना",
    "usage": "उपयोग",
    "month": "माह",
    "year": "वर्ष",
    "free": "मुफ्त",
    "database": "डेटाबेस",
    "additionalServices": "अतिरिक्त सेवाएं",
    "softwareCompilers": "सॉफ्टवेयर कंपाइलर्स",
    "enableNewFeatures": "नई सुविधाओं को सक्षम करें",
    "addHost": "एक वेबसाइट जोड़ें",
    "emptyList": "कोई वेबसाइट सूचीबद्ध नहीं है",
    "waitForDataHint": "संसाधन उपयोग यहां दिखाई देगा। डेटा देखने के लिए अगले दिन वापस आएं।",
    "slaveID": "स्लेव आईडी",
    "IPAddress": "आईपी पता",
    "openWebsite": "वेबसाइट खोलें",
    "openPortal": "पोर्टल खोलें",
    "hostStatus": "होस्ट स्थिति",
    "creationDate": "निर्माण तिथि",
    "usernameHost": "होस्ट उपयोगकर्ता नाम",
    "domainHost": "होस्ट डोमेन",
    "manageHostLogin": "होस्ट लॉगिन प्रबंधित करें",
    "total": "कुल",
    "used": "उपयोग किया गया",
    "remainingMonthlyPlan": "शेष मासिक योजना",
    "remainingAddons": "शेष ऐड-ऑन",
    "planDetail": "{0} योजना, {1} डिस्क स्पेस, {2} मासिक बैंडविड्थ।",
    "emptyForDefaultCname": "डिफ़ॉल्ट के लिए खाली छोड़ें ({0})",
    "redeploy": "पुनः परिनियोजित करें",
    "deployAdd": "एक परिनियोजन कार्य जोड़ें",
    "deployNow": "निष्पादित करें!",
    "deployClearHint": "सभी लॉग्स साफ़ करें?",
    "websiteReadyHint": "आपकी साइट तैयार है। अब इसे आज़माएं?",
    "deployByAdmin": "सिस्टम मोड द्वारा चलाया गया",
    "deployOverwriteBanner": "यह स्क्रिप्ट इस वेबसाइट की सभी फ़ाइलों को बदल देगी!",
    "deployOverwriteWarn": "आपने स्रोत पैरामीटर का उल्लेख किया है, जिसका मतलब है कि आपकी HOME फ़ाइल स्थायी रूप से ओवरराइट हो जाएगी। इस कार्रवाई को उलटा नहीं जा सकता है। क्या आप सुनिश्चित हैं?",
    "deployHelpBtn": "परिनियोजन कॉन्फ़िगरेशन संदर्भ",
    "githubWebhook": "Webhook सेटअप करें",
    "githubWebhookTitle": "GitHub कार्रवाई सेटअप करें",
    "githubWebhookHelp": "आप इस webhook का उपयोग तब कर सकते हैं जब आप GitHub पर पुश करते हैं तो अपनी वेबसाइट को स्वचालित रूप से परिनियोजित करने के लिए।",
    "githubWebhookHelpBtn": "GitHub कार्रवाई Webhook सहायता",
    "noWebhook": "इस होस्ट के लिए कोई webhook कॉन्फ़िगर नहीं है।",
    "noGitHubApi": "GitHub API उपलब्ध नहीं है",
    "noGitHubApiToken": "GitHub API टोकन नहीं मिला",
    "noGitHubApiHint": "आपको पहले पूर्ण रेपो एक्सेस के साथ एक GitHub खाता लिंक करना होगा।",
    "noGitHubApiLink": "अब GitHub लिंक करें",
    "noRepo": "कोई रिपॉजिटरी नहीं मिला",
    "noRepoHint": "अपनी खोज को संकीर्ण करने का प्रयास करें",
}
