export default {
  "code": "hi",
  "codename": "हिन्दी",
  "appTitle": "DOM Cloud",
  "appTitleLong": "DOM Cloud Hosting",
  "logout": "साइन आउट करें",
  "profile": "प्रोफ़ाइल",
  "status": "स्थिति",
  "verifyStatus": "सत्यापन स्थिति",
  "hosting": "वेबसाइट",
  "domain": "डोमेन",
  "backup": "बैकअप",
  "owner": "मालिक",
  "admin": "व्यवस्थापक",
  "member": "सदस्य",
  "team": "टीम",
  "email": "ईमेल",
  "storage": "स्टोरेज",
  "bandwidth": "बैंडविड्थ",
  "instances": "इंस्टेंस",
  "users": "उपयोगकर्ता",
  "details": "विवरण",
  "members": "सदस्य",
  "upgrade": "अपग्रेड",
  "otherTeams": "अन्य टीमें",
  "hostname": "होस्टनाम",
  "port": "पोर्ट",
  "username": "उपयोगकर्ता नाम",
  "password": "पासवर्ड",
  "server": "सर्वर",
  "ipv4": "IPv4",
  "ipv6": "IPv6",
  "ssh": "SSH/SFTP",
  "webmin": "Webmin",
  "filestash": "Filestash",
  "mysql": "MySQL",
  "postgresql": "PostgreSQL",
  "phpmyadmin": "phpMyAdmin",
  "phppgadmin": "phpPgAdmin",
  "webssh": "WebSSH",
  "vscode": "Visual Studio Code",
  "help": "सहायता",
  "helpDocs": "दस्तावेज़",
  "helpDocsLink": "https://domcloud.co/docs/intro/",
  "helpEmail": "ईमेल",
  "helpEmailLink": "mailto:support@domcloud.co",
  "helpChat": "चैट",
  "helpChatLink": "https://t.me/WIIIN0DE",
  "helpUpdates": "अपडेट्स",
  "helpUpdatesLink": "https://twitter.com/domcloud_co",
  "country": "देश",
  "chooseCountry": "एक देश चुनें",
  "expiration": "समाप्ति",
  "resendConfirmationEmail": "पुष्टिकरण ईमेल फिर से भेजें",
  "learnMore": "अधिक जानें",
  "passwordNotice": "आपको इस पासवर्ड को याद रखने की आवश्यकता नहीं है",
  "lastUpdatedAt": "अंतिम अपडेट समय",
  "language": "भाषा",
  "theme": "थीम",
  "themeDark": "हमेशा डार्क",
  "themeLight": "हमेशा लाइट",
  "themeSystem": "सिस्टम डिफ़ॉल्ट",
  "role": "भूमिका",
  "action": "क्रिया",
  "currencyInput": "मुद्रा",
  "invoiceNoteInput": "इनवॉइस संपर्क",
  "defaultServerInput": "डिफ़ॉल्ट सर्वर",
  "defaultServerInputNone": "कोई नहीं (मुझसे पूछें)",
  "name": "नाम",
  "phone": "फ़ोन नंबर",
  "phoneHint": "पूरी तरह योग्य फ़ोन नंबर (प्रारंभ + से)",
  "phoneAlt": "वैकल्पिक फ़ोन नंबर",
  "fullName": "पूरा नाम",
  "companyName": "कंपनी का नाम",
  "activeEmail": "सक्रिय ईमेल",
  "newPassword": "नया पासवर्ड",
  "editProfile": "प्रोफ़ाइल संपादित करें",
  "saveProfile": "प्रोफ़ाइल सहेजें",
  "deleteAccount": "खाता हटाएं",
  "loginMethods": "लॉगिन विधियाँ",
  "loginRemoveConfirm": "क्या आप वाकई इस लॉगिन विधि को हटाना चाहते हैं?",
  "loginAdd": "लॉगिन विधि जोड़ें या बदलें",
  "loginGithub": "GitHub",
  "loginGoogle": "Google",
  "loginEmail": "ईमेल + पासवर्ड",
  "loginVia": "द्वारा {0}",
  "passwordConfirm": "वर्तमान खाता पासवर्ड दर्ज करें (यदि मौजूद है)",
  "passwordSetInput": "नया पासवर्ड दर्ज करें, कम से कम 8 वर्ण होना चाहिए",
  "passwordSetCancel": "इस खाते के लिए पासवर्ड सेटिंग रद्द की गई है",
  "passwordSetCancelLength": "पासवर्ड सेटिंग रद्द की गई, कम से कम 8 वर्ण होने चाहिए",
  "yearDuration": "वर्षों में अवधि",
  "monthDuration": "महीनों में अवधि",
  "annualSaving": "16% की बचत",
  "totalPayment": "कुल भुगतान",
  "expirationDate": "समाप्ति तिथि",
  "orderNow": "अभी ऑर्डर करें",
  "invoice": "चालान",
  "pendingInvoices": "लंबित चालान",
  "noPendingInvoices": "आपके पास वर्तमान में कोई लंबित चालान नहीं हैं।",
  "mixedCurrency": "चयनित चालानों में विभिन्न मुद्राएँ हैं",
  "currentPlan": "वर्तमान योजना",
  "currentPlanDescription": "<b>{0}</b> प्रति माह की लागत के साथ <b>{1}</b> समाप्ति के साथ",
  "priceDescription": "{0} / माह",
  "monthlyLimits": "मासिक सीमाएँ",
  "storageLimit": "{0} जीबी स्टोरेज",
  "networkLimit": "{0} जीबी नेटवर्क",
  "instanceLimit": "{0} {0, plural, one {इंस्टेंस} other {इंस्टेंस}}",
  "userLimit": "{0} {0, plural, one {उपयोगकर्ता} other {उपयोगकर्ता}}",
  "autoStop": "सीमाओं पर स्वचालित रूप से बंद करें",
  "noFreeDomain": "कोई *.domcloud.dev डोमेन नहीं",
  "withFreeDomain": "मुफ्त *.domcloud.dev डोमेन",
  "withBackup": "स्वचालित सर्वर-स्तरीय बैकअप",
  "withDocker": "डॉकर और लंबी चलने वाली ऐप्स",
  "storageUsage": "स्टोरेज उपयोग",
  "storageUsageCap": "कुल {0} में से",
  "bandwidthUsed": "उपयोग की गई बैंडविड्थ",
  "bandwidthUsedCap": "मासिक {0} में से",
  "instancesActive": "सक्रिय इंस्टेंस",
  "instancesActiveCap": "कुल {0} वेबसाइट्स में से",
  "teamUsers": "टीम उपयोगकर्ता",
  "teamUsersCap": "अधिकतम {0} उपयोगकर्ताओं में से",
  "remainingAvailable": "शेष उपलब्ध",
  "remainingStorage": "मुक्त स्टोरेज",
  "remainingNetwork": "नेटवर्क डेटा",
  "remainingInstance": "शेष इंस्टेंस",
  "dataTransfer": "डेटा ट्रांसफर",
  "expires": "{0} को समाप्त",
  "expiresAt": "{0} पर समाप्त",
  "expireFreeHint": `
समाप्ति तिथियां स्वचालित रूप से नवीनीकृत (3 महीने के लिए बढ़ाई गई) 
जब भी आप लॉगिन करते हैं या आपकी वेबसाइट्स में पर्याप्त नेटवर्क ट्रैफिक (>50 MB) 
महीने के अंत में होता है।
`,
  "discountedAt": "{0} पर छूट",
  "extendingCurrentExpiryDate": "वर्तमान समाप्ति तिथि बढ़ाई जा रही है",
  "usersLimitHint": "{0} {0, plural, one {उपयोगकर्ता} other {उपयोगकर्ता}} इस टीम में, {1} {1, plural, one {उपयोगकर्ता} other {उपयोगकर्ता}} और जोड़े जा सकते हैं",
  "emailToInvite": "आमंत्रित करने के लिए ईमेल",
  "selectRole": "भूमिका चुनें",
  "info": "जानकारी",
  "total": "कुल",
  "back": "वापस",
  "add": "जोड़ें",
  "addMember": "सदस्य जोड़ें",
  "edit": "संपादित करें",
  "apply": "लागू करें",
  "save": "सहेजें",
  "clear": "साफ करें",
  "update": "अपडेट करें",
  "updateUsage": "उपयोग अपडेट करें",
  "change": "बदलें",
  "archives": "पुरालेख",
  "renew": "नवीनीकृत करें",
  "extend": "बढ़ाएं",
  "topup": "टॉप अप",
  "processing": "प्रक्रिया में",
  "cancel": "रद्द करें",
  "print": "प्रिंट करें",
  "why": "क्यों?",
  "pay": "भुगतान करें",
  "payAccept": "हम इन माध्यमों से भुगतान स्वीकार करते हैं",
  "loading": "डेटा एकत्रित किया जा रहा है...",
  "fetchError": "डेटा प्राप्त करने में त्रुटि! बाद में पुनः प्रयास करें",
  "notFound": "नहीं मिला",
  "notFoundDescription": "आप जो पृष्ठ खोज रहे हैं वह मौजूद नहीं है।",
  "notFoundLink": "होमपेज पर वापस जाएं"
}
