export default {
    "check": "Consulte",
    "detail": "Detalle",
    "dns": "DNS",
    "renew": "Renovar",
    "renewDomain": "Renovar dominio",
    "listTitle": "Lista de dominios",
    "newOrder": "Comprar un dominio",
    "transferDomain": "Trasladar un dominio",
    "registerTitle": "Registro de cuentas de dominio",
    "administrationData": "Datos de la Administración",
    "addressData": "Dirección",
    "address": "Dirección",
    "address1": "Dirección (Línea 1)",
    "address2": "Dirección (Línea 2)",
    "address3": "Dirección (Línea 3)",
    "city": "Ciudad",
    "state": "Estado",
    "country": "País",
    "zipCode": "Código postal",
    "company": "Empresa",
    "companyName": "Empresa / Nombre de la organización",
    "domainName": "Dominio Nama",
    "domainStatus": "Estado Dominio",
    "formatInvoice": "Pago de dominio {0} a precio de {1}",
    "enterContact": "Rellenar los Biodatos de Dominio",
    "myOwn": "El dominio que pedí es mío",
    "enterBio": "Introducir datos personales",
    "publicBio": "Biodatos públicos / Propietario del dominio",
    "personalBio": "Biodatos personales / Dominio responsable",
    "domainPrice": "Precio del dominio",
    "emptyList": "No aparece ningún dominio",
    "registrationDate": "Registration Date",
    "expirationDate": "Fecha de expiración",
    "transferLock": "Cerradura de transferencia",
    "privacyLock": "Bloqueo de privacidad",
    "nameServers": "Servidores de nombres",
    "findDomain": "Buscar dominio",
    "findWait": "Comprobación de ...",
    "findUnavailable": "El dominio no está disponible.",
    "findNeedData": "No podemos procesar las compras de dominios hasta que rellene los datos que necesitamos.",
    "findNeedDataAction": "Rellenar ahora",
    "transferCode": "EPP / Código de transferencia",
    "showTransferCode": "Mostrar código EPP",
}
