export default {
    "check": "Comprobar",
    "detail": "Detalle",
    "dns": "DNS",
    "renew": "Renovar",
    "renewDomain": "Renovar Dominio",
    "listTitle": "Lista de Dominios",
    "newOrder": "Comprar un dominio",
    "transferDomain": "Transferir un dominio",
    "registerTitle": "Registro de Cuenta de Dominio",
    "administrationData": "Datos de Administración",
    "addressData": "Datos de Dirección",
    "address": "Dirección",
    "address1": "Dirección (Línea 1)",
    "address2": "Dirección (Línea 2)",
    "address3": "Dirección (Línea 3)",
    "city": "Ciudad",
    "state": "Estado",
    "country": "País",
    "zipCode": "Código Postal",
    "company": "Empresa",
    "companyName": "Nombre de la Empresa / Organización",
    "domainName": "Nombre del Dominio",
    "domainStatus": "Estado del Dominio",
    "formatInvoice": "Pago de dominio {0} con un precio de {1}",
    "enterContact": "Ingresar Contacto del Dominio",
    "contactEntered": "Contacto del Dominio ingresado",
    "myOwn": "El dominio que ordené es mío",
    "enterBio": "Ingresar Contacto",
    "publicBio": "Contacto Público / Propietario del Dominio",
    "personalBio": "Contacto Personal / Responsable del Dominio",
    "domainPrice": "Precio del Dominio",
    "emptyList": "No hay dominios listados",
    "registrationDate": "Fecha de Registro",
    "expirationDate": "Fecha de Expiración",
    "transferLock": "Bloqueo de Transferencia",
    "privacyLock": "Bloqueo de Privacidad",
    "nameServers": "Servidores de Nombre",
    "checkHint": "Haga clic en el botón de verificar",
    "checkFail": "No se pudo verificar la disponibilidad del dominio",
    "findDomain": "Encontrar Dominio",
    "findWait": "Verificando ...",
    "findUnavailable": "El dominio no está disponible actualmente.",
    "findNeedData": "No podemos procesar compras de dominios hasta que complete los datos necesarios.",
    "findNeedDataAction": "Completar ahora",
    "verifyHint": "¡Necesita verificar su correo electrónico dentro de 15 días después de la compra o nuestro registrador suspenderá su dominio!",
    "verifyBtn": "Reenviar correo electrónico de verificación a {0}",
    "transferCode": "Código EPP / de Transferencia",
    "showTransferCode": "Mostrar Código EPP",
}
