<?php return [
	'emailAlreadyExist' => 'Este correo electrónico ya existe',
	'passwordNotLongEnough' => 'Esta contraseña no es lo suficientemente larga',
	'passwordNotMatch' => 'La contraseña existente no coincide',
	'invalidCountry' => 'Código de país no válido',

	'accountAlreadyAttached' => 'Lo siento, esta cuenta social ya está vinculada a otra cuenta.',
	'accountCreationExpired' => 'Lo siento, parece que estamos intentando confirmar la creación de tu cuenta pero tu sesión ha expirado. Intenta iniciar sesión nuevamente.',
	'accountPasswordlessRecovery' => 'Desafortunadamente, no puedes recuperar una cuenta sin contraseña. Por favor, intenta usar un usuario de terceros (Google o GitHub) en su lugar.',
	'accountDeleteLastMethod' => 'No puedes eliminar tu único método de inicio de sesión',
	'accountRecountTooFast' => 'Por favor, espera un momento antes de volver a contar',
	'accountDeleteNotDangling' => 'Por favor, elimina todos los hosts, dominios y copias de seguridad primero',

	'inviteUserNotFound' => 'Usuario no encontrado',
	'inviteQuotaFull' => 'El equipo está lleno, por favor actualiza',
	'inviteNewFail' => 'Error al invitar, ¿tal vez ya han sido agregados?',
	'inviteRemoveFail' => 'Error al eliminar miembro, ¿tal vez ya han sido eliminados?',

	'inviteCodeInvalid' => 'Código de invitación no válido',
	'inviteCodeExpired' => 'Código de invitación vencido',

	'unknownAction' => 'Acción desconocida',
	'hostIsNotActive' => 'No se puede aplicar la tarea mientras este host no está activo',
	'needVerifyEmail' => 'Por favor, verifica tu correo electrónico primero',
	'hostQuotaLimit' => 'Lo siento, necesitas actualizar tu plan para crear más hosts. Si ya lo has hecho, revisa tu saldo o contacta al soporte.',
	'usingInternalDomain' => 'Lo siento, no puedes usar nuestro dominio aquí',
	'usingSubscibingDomain' => 'Lo siento, necesitas actualizar tu plan para usar este dominio',
	'invalidUsername' => 'Nombre de usuario no válido',
	'invalidDomainname' => 'Nombre de dominio no válido',
	'unchangedUsername' => 'Nombre de usuario sin cambios',
	'unchangedDomainname' => 'Nombre de dominio sin cambios',
	'domainAlreadyExist' => 'El nombre de dominio ya existe',
	'tooShortUsername' => 'El nombre de usuario es demasiado corto',
	'parentNotFound' => 'Dominio principal no encontrado',
	'invalidDeployYaml' => 'Tu script de implementación no es un YAML válido',
	'invalidDeleteState' => '¡No se puede eliminar mientras las implementaciones están en curso! Por favor, espera un momento.',
	'backupNeedSubscribe' => 'Lo siento, necesitas actualizar tu plan para crear copias de seguridad',
	'backupIsNotActive' => 'El estado de la copia de seguridad no está activo, tal vez ya se ha ido',
];
