<?php return [

	'invoiceDomainPurchaseOf' => 'Compra de dominio de {0}',
	'invoiceDomainExtendOf' => 'Renovación de dominio de {0}',
	'invoiceDomainTransferOf' => 'Transferencia de dominio de {0}',
	'invoiceTeamPurchaseOf' => 'Compra del plan web {0}',
	'invoiceTeamAddons' => 'Complementos del equipo',
	'invoiceForMonths' => ' durante {0}',
	'invoiceForYears' => ' durante {0}',
	'invoiceForYearsAndMonths' => ' durante {0} y {1}',
	'invoiceDataTransferAddonsFor' => 'Transferencia de datos adicional de {0} GB',
	'invoiceTip' => 'Tarifa de conveniencia',

	'repoOk' => 'El repositorio es accesible',
	'repoNoRefs' => 'El repositorio es accesible pero no hay referencias coincidentes',
	'repoNoAccess' => 'El repositorio no es accesible',
	'fileOk' => 'El archivo ZIP es accesible',
	'fileNoZip' => 'El archivo no es un archivo ZIP',
	'fileNoAccess' => 'El archivo no es accesible',
	'fileRequired' => 'Se requiere el archivo del repositorio',
	'uploadFileRequired' => 'Se requiere la carga de archivos',
	'uploadFileMustZip' => 'La carga de archivos debe ser un archivo ZIP',

	'head_violation_storage' => 'Violación de la Capacidad de Almacenamiento',
	'body_violation_storage' => 'Su cuenta ha superado 3 veces el límite de capacidad de almacenamiento. Lo sentimos, debemos tomar medidas. Hemos eliminado todos sus sitios web hasta que se alcance la capacidad de almacenamiento requerida.',
	'head_violation_expiry_paid' => 'Violación de la Fecha de Vencimiento',
	'body_violation_expiry_paid' => 'Su cuenta ha superado la fecha de vencimiento. Estamos volviendo su cuenta a una cuenta gratuita. Tenga en cuenta que si sus sitios web ya han superado el límite gratuito, puede que reciba otras notificaciones en los próximos días. Por favor, verifique los límites de su cuenta antes de que suceda.',
	'head_violation_expiry_free' => 'Violación de la Fecha de Vencimiento',
	'body_violation_expiry_free' => 'Su cuenta ha superado las dos semanas posteriores a la fecha de vencimiento. Lo sentimos, debemos tomar medidas. Hemos eliminado permanentemente todos sus sitios web para hacer espacio para otros.',
	
	'head_over_expiry_paid' => 'Fecha de Vencimiento Excedida',
	'body_over_expiry_paid' => 'Su cuenta ha superado la fecha de vencimiento. Por favor, renueve su suscripción de cuenta. Tenga en cuenta que si no renueva su cuenta dentro de las próximas 2 semanas, su cuenta se convertirá en una cuenta gratuita.',
	'head_over_expiry_free' => 'Fecha de Vencimiento Excedida',
	'body_over_expiry_free' => 'Su cuenta ha superado la fecha de vencimiento. Debemos desactivar sus sitios web para llamar su atención. Para activarlos nuevamente, simplemente inicie sesión. Tenga en cuenta que todos sus sitios web se eliminarán si no vuelve a iniciar sesión dentro de las próximas 2 semanas.',
	'head_over_storage' => 'Límite de Almacenamiento Excedido',
	'body_over_storage' => 'Su cuenta ha superado el límite de almacenamiento. Debemos desactivar sus sitios web para llamar su atención. Para recuperar su sitio web, libere espacio eliminando archivos innecesarios. Tenga en cuenta que si ignora este mensaje y continúa llenando el almacenamiento, podríamos eliminar sus sitios web de forma permanente.',
	'head_over_network' => 'Límite de Ancho de Banda Excedido',
	'body_over_network' => 'Su cuenta ha superado el límite de ancho de banda. Debemos desactivar sus sitios web para llamar su atención. Desafortunadamente, no hay una manera rápida de recuperar su sitio web instantáneamente, tendrá que esperar hasta el próximo mes.',
	'head_over_instance' => 'Límite de Instancias Excedido',
	'body_over_instance' => 'Su cuenta ha superado el límite de cantidad de instancias/sitios web. Esto es extraño (deberíamos haber evitado que lo hiciera). Sin embargo, debemos desactivar sus sitios web para llamar su atención. Por favor, elimine algunos sitios web no importantes para recuperar otros.',
	
	'head_warn_expiry_paid' => 'Advertencia de Fecha de Vencimiento',
	'body_warn_expiry_paid' => 'Su cuenta expirará en 3 días. Por favor, renueve su cuenta para mantenerla dentro del plan actual.',
	'head_warn_expiry_free' => 'Advertencia de Fecha de Vencimiento',
	'body_warn_expiry_free' => 'Su cuenta expirará en 3 días. Como está en un plan gratuito, por favor, renueve su cuenta iniciando sesión nuevamente. Su cuenta estará disponible durante otros 30 días.',
	'head_warn_storage' => 'Advertencia de Límite de Almacenamiento',
	'body_warn_storage' => 'Sus sitios web han alcanzado el límite de almacenamiento casi por completo. Por favor, libere espacio eliminando archivos innecesarios.',
	'head_warn_network' => 'Advertencia de Límite de Ancho de Banda',
	'body_warn_network' => 'Sus sitios web han agotado casi por completo los datos de la red. Desafortunadamente, no hay mucho que pueda hacer hasta que esté disponible nuevamente el próximo mes.'
];
