export default {
    'invoiceDomainPurchaseOf': 'Compra de dominio {0}',
    'invoiceDomainExtendOf': 'Renovación de dominio {0}',
    'invoiceDomainTransferOf': 'Transferencia de dominio {0}',
    'invoiceTeamPurchaseOf': 'Compra de equipo con plan {0}',
    'invoiceTeamAddons': 'Complementos de equipo',
    'invoiceForMonths': ' por {0, plural, =1{# mes} other{# meses}}',
    'invoiceForYears': ' por {0, plural, =1{# año} other{# años}}',
    'invoiceForYearsAndMonths': ' por {0, plural, =1{# año} other{# años}} y {1, plural, =1{# mes} other{# meses}}',
    'invoiceDataTransferAddonsFor': 'Transferencia de datos adicional por {0} GB',
    'invoiceTip': 'Tarifa de conveniencia',
    "listTitle": "Lista de sitios web",
    "newOrder": "Añadir un sitio web",
    "tabDetail": "Información",
    "tabSetup": "Configurar",
    "tabManage": "Gestione",
    "tabRunner": "Despliegue",
    "tabWebhook": "Webhook",
    "tabCheck": "Consulte",
    "tabConnection": "Comprobar conexión",
    "tabFirewall": "Comprobar cortafuegos",
    "tabNginx": "Compruebe NGINX",
    "tabScreend": "Comprobar tareas de fondo",
    "tabAdmin": "Admin",
    "tabEnvironment": "Secretos",
    "tabRename": "Cambiar nombre de usuario",
    "tabCname": "Cambiar dominio",
    "tabPasswd": "Cambiar contraseña",
    "tabTransfer": "Sitio web de transferencias",
    "tabDelete": "Borrar sitio web",
    "startFromTemplate": "Partir de una plantilla",
    "uploadOrClone": "Subir o clonar desde Internet",
    "customTemplate": "Plantilla personalizada",
    "customDomain": "Dominio personalizado",
    "mergeToParentDomain": "Fusión con el dominio principal",
    "fetchingDomains": "...Búsqueda de dominios",
    "moreTemplates": "Más plantillas",
    "portalUsername": "Nombre de usuario",
    "portalUsernameHint": "Sólo alfanumérico y guión",
    "portalPassword": "Contraseña",
    "slaveServer": "Región",
    "scheme": "Plan",
    "usage": "Utilización",
    "month": "Mes",
    "year": "Año(s)",
    "free": "Gratis",
    "addHost": "Añadir un sitio web",
    "emptyList": "No hay página web",
    "waitForDataHint": "El uso de recursos aparecerá aquí. Vuelva el próximo día para que aparezcan los datos.",
    "slaveID": "Slave ID",
    "IPAddress": "Dirección IP",
    "openWebsite": "Abrir el sitio web",
    "openPortal": "Portal abierto",
    "hostStatus": "Estado del Host",
    "creationDate": "Fecha de compra",
    "usernameHost": "Nombre de usuario del host",
    "domainHost": "Dominio anfitrión",
    "manageHostLogin": "Gestionar inicio de sesión de host",
    "total": "Total",
    "used": "Usado",
    "remainingMonthlyPlan": "Plan mensual restante",
    "remainingAddons": "Complementos restantes",
    "planDetail": "{0} Plan, {1} espacio en disco, {2} ancho de banda mensual.",
    "emptyForDefaultCname": "Dejar en blanco por defecto ({0})",
    "redeploy": "Redistribuya",
    "deployAdd": "Añadir una tarea de despliegue",
    "deployNow": "Ejecutar!",
    "deployClearHint": "¿Borrar todos los registros?",
    "deployOverwriteWarn": "Usted mencionó el parámetro fuente, lo que significa que su archivo HOME será PERMANENTEMENTE SOBREESCRITO. Esta acción no puede ser revertida. ¿Está usted seguro?",
    "deployHelpBtn": "Desplegar Config Referencia",
    "githubWebhook": "Configurar Webhook",
    "githubWebhookTitle": "Configurar la acción de GitHub",
    "githubWebhookHelp": "Puede utilizar este webhook para desplegar automáticamente su sitio web cuando se empuja a GitHub.",
    "githubWebhookHelpBtn": "Ayuda de GitHub Action Webhook",
    "noWebhook": "No hay webhooks configurados para este host.",
    "noGitHubApi": "La API de GitHub no está disponible",
    "noGitHubApiToken": "No se ha encontrado el token de la API de GitHub",
    "noGitHubApiHint": "Primero debe vincular una cuenta de GitHub con acceso completo al repositorio..",
    "noGitHubApiLink": "Vincular GitHub ahora",
    "noRepo": "No se ha encontrado ningún repositorio",
    "noRepoHint": "Intente limitar su búsqueda",
}
