export default {
    "logout": "Cerrar sesión",
    "profile": "Perfil",
    "status": "Estado",
    "verifyStatus": "Estado de verificación",
    "hosting": "Sitio web",
    "domain": "Dominio",
    "backup": "Respaldo",
    "owner": "Propietario",
    "admin": "Administrador",
    "member": "Miembro",
    "team": "Equipo",
    "email": "Correo electrónico",
    "storage": "Almacenamiento",
    "bandwidth": "Ancho de banda",
    "instances": "Instancias",
    "users": "Usuarios",
    "details": "Detalles",
    "members": "Miembros",
    "upgrade": "Actualizar",
    "otherTeams": "Otros Equipos",
    "inviteCode": "Código de invitación",
    "hostname": "Nombre de host",
    "port": "Puerto",
    "username": "Nombre de usuario",
    "password": "Contraseña",
    "server": "Servidor",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    // Sección de ayuda
    "help": "Ayuda",
    "helpDocs": "Documentos",
    "helpEmail": "Correo electrónico",
    "helpChat": "Chat",
    "helpUpdates": "Actualizaciones",
    // Sección de perfil
    "country": "País",
    "chooseCountry": "Elija un país",
    "expiration": "Vencimiento",
    "resendConfirmationEmail": "Reenviar correo de confirmación",
    "learnMore": "Más información",
    "passwordNotice": "No es necesario recordar esta contraseña",
    "lastUpdatedAt": "Última actualización en",
    "language": "Idioma",
    "theme": "Tema",
    "themeDark": "Siempre Oscuro",
    "themeLight": "Siempre Claro",
    "themeSystem": "Predeterminado del sistema",
    "role": "Rol",
    "action": "Acción",
    "currencyInput": "Moneda",
    "invoiceNoteInput": "Contacto de factura",
    "defaultServerInput": "Servidor predeterminado",
    "defaultServerInputNone": "Ninguno (preguntarme)",
    "name": "Nombre",
    "phone": "Número de teléfono",
    "phoneHint": "Número de teléfono completo (comienza con +)",
    "phoneAlt": "Número de teléfono alternativo",
    "fullName": "Nombre completo",
    "activeEmail": "Correo electrónico activo",
    "newPassword": "Nueva contraseña",
    "editProfile": "Editar perfil",
    "saveProfile": "Guardar perfil",
    "deleteAccount": "Eliminar cuenta",
    "loginMethods": "Métodos de inicio de sesión",
    "loginRemoveConfirm": "¿Estás seguro de que deseas eliminar este método de inicio de sesión?",
    "loginAdd": "Agregar o reemplazar un método de inicio de sesión",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "Correo electrónico + Contraseña",
    "loginVia": "a través de {0}",
    "passwordConfirm": "Ingrese la contraseña actual de la cuenta (si está presente)",
    "passwordSetInput": "Ingrese una nueva contraseña, debe tener al menos 8 caracteres",
    "passwordSetCancel": "La configuración de la contraseña para esta cuenta ha sido cancelada",
    "passwordSetCancelLength": "Configuración de contraseña cancelada, debe tener al menos 8 caracteres",
    // Gestión de equipos
    "yearDuration": "Duración en años",
    "monthDuration": "Duración en meses",
    "annualSaving": "Ahorro anual del 16%",
    "totalPayment": "Pago total",
    "expirationDate": "Fecha de vencimiento",
    "orderNow": "Ordenar ahora",
    "invoice": "Factura",
    "pendingInvoices": "Facturas pendientes",
    "noPendingInvoices": "Actualmente no tiene facturas pendientes.",
    "mixedCurrency": "Las facturas seleccionadas tienen monedas mixtas",
    "currentPlan": "Plan actual",
    "currentPlanDescription": "Con un costo de <b>{0}</b> por mes con vencimiento el <b>{1}</b>",
    "priceDescription": "{0} / mes",
    "monthlyLimits": "Límites mensuales",
    "storageLimit": "{0} GB de almacenamiento",
    "networkLimit": "{0} GB de red",
    "instanceLimit": "{0} {0, plural, one {Instancia} other {Instancias}}",
    "userLimit": "{0} {0, plural, one {Usuario} other {Usuarios}}",
    "autoStop": "Detención automática en los límites",
    "noFreeDomain": "Sin dominio *.domcloud.dev gratuito",
    "withFreeDomain": "Dominio gratuito *.domcloud.dev",
    "withBackup": "Copia de seguridad automática a nivel de servidor",
    "withDocker": "Docker y aplicaciones de larga duración",
    "storageUsage": "Uso de almacenamiento",
    "storageUsageCap": "de {0} en total",
    "bandwidthUsed": "Ancho de banda utilizado",
    "bandwidthUsedCap": "de {0} mensuales",
    "instancesActive": "Instancias activas",
    "instancesActiveCap": "de {0} sitios web",
    "teamUsers": "Usuarios del equipo",
    "teamUsersCap": "de un máximo de {0} usuarios",
    "remainingAvailable": "Disponible restante",
    "remainingStorage": "Almacenamiento gratuito",
    "remainingNetwork": "Datos de red restantes",
    "remainingInstance": "Instancia restante",
    "dataTransfer": "Transferencia de datos",
    "expires": "Vence {0}",
    "expiresAt": "Vence el {0}",
    "expireFreeHint": `
  Las fechas de vencimiento se renuevan automáticamente (se extienden por 3 meses)
  cada vez que inicia sesión o sus sitios web tienen suficiente tráfico de red (> 50 MB)
  al final del mes.
  `,
    "discountedAt": "Con descuento en {0}",
    "extendingCurrentExpiryDate": "Extendiendo la fecha de vencimiento actual",
    "usersLimitHint": "{0} {0, plural, one {usuario} other {usuarios}} en este equipo, se pueden agregar {1} {1, plural, one {usuario} other {usuarios}} más",
    "emailToInvite": "Correo electrónico para invitar",
    "selectRole": "Seleccionar rol",
    // Botones
    "info": "Información",
    "total": "Total",
    "back": "Atrás",
    "add": "Agregar",
    "addMember": "Agregar miembro",
    "confirmRemoveMember": "¿Estás seguro de que quieres eliminar a este miembro?",
    "edit": "Editar",
    "apply": "Aplicar",
    "save": "Guardar",
    "clear": "Limpiar",
    "update": "Actualizar",
    "updateUsage": "Actualizar uso",
    "change": "Cambiar",
    "archives": "Archivos",
    "renew": "Renovar",
    "extend": "Extender",
    "topup": "Recargar",
    "processing": "Procesando",
    "cancel": "Cancelar",
    "print": "Imprimir",
    "why": "¿Por qué?",
    "pay": "Pagar",
    "payAccept": "Aceptamos pagos a través de",
    // Errores
    "loading": "Recopilando datos...",
    "fetchError": "¡Error al buscar datos! Inténtelo de nuevo más tarde",
    "notFound": "No encontrado",
    "notFoundDescription": "La página que buscas no existe.",
    "notFoundLink": "Volver a la página de inicio",
}
