<?php return [
	'code' => 'es',
	'codename' => 'Spanish',
	'currency' => 'usd',
	'login' => 'Iniciar sesión',
	'register' => 'Registrarse',
	'email' => 'Correo electrónico',
	'enterToPortal' => 'Entrar al Portal',
	'registerToPortal' => 'Registrarse en el Portal',
	'registerWithEmail' => 'Registrarse con correo electrónico',
	'forgotPrompt' => '¿Olvidó su contraseña?',
	'recoverYourPassword' => 'Recuperar su contraseña',
	'recoverYourPasswordHint' => 'Ingrese una nueva contraseña para cambiar',

	'back' => 'Volver',
	'or' => 'O',
	'signInWith' => 'Iniciar sesión con',
	'wrongLogin' => 'Correo electrónico o contraseña incorrectos',
	'registerAgreement' => 'Al registrarte, aceptas nuestros <a href="//domcloud.co/service" target="_blank">Términos de servicio</a>.',
	'emailSent' => 'El correo electrónico de verificación ha sido enviado, por favor revisa tu bandeja de entrada (y la de correo no deseado) antes de iniciar sesión.',
	'oAuthFail' => 'Parece que su intento con el inicio de sesión de terceros falló. Esto suele deberse a que se agotó el tiempo de espera o al correo electrónico principal vinculado a esa cuenta que aún no se ha verificado.',
	'passReset' => 'Su contraseña se ha restablecido con éxito. Inicie sesión con su nueva contraseña.',
	'thanksForVerify' => 'Gracias, su correo electrónico ha sido verificado',

	'password' => 'Contraseña',
	'passwordAgain' => 'Contraseña (otra vez)',
	'fullName' => 'Nombre y apellidos',
	'activeEmail' => 'Correo electrónico activo',
];
