export default {
    "invalidFormat": "\"{0}\" no es un formato de fecha y hora válido",
    "invalidMonth": "Los meses deben estar comprendidos entre 1 y 12. Dado: {0}",
    "invalidDay": "Los días deben estar comprendidos entre 1 y 31. Dado: {0}",
    "invalidOverDay": "Los días deben estar comprendidos entre 1 y {0}. Dado: {1}",
    "invalidHours": "Las horas deben estar comprendidas entre 0 y 23. Dado: {0}",
    "invalidMinutes": "Los minutos deben estar comprendidos entre 0 y 59. Dado: {0}",
    "invalidSeconds": "Los segundos deben estar comprendidos entre 0 y 59. Dado: {0}",
    "years": "{0, plural, =1{# año} other{# años}}",
    "months": "{0, plural, =1{# mes} other{# meses}}",
    "weeks": "{0, plural, =1{# semana} other{# semanas}}",
    "days": "{0, plural, =1{# día} other{# días}}",
    "hours": "{0, plural, =1{# hora} other{# horas}}",
    "minutes": "{0, plural, =1{# minuto} other{# minutos}}",
    "seconds": "{0, plural, =1{# segundo} other{# segundos}}",
    "ago": "{0} ago",
    "inFuture": "en {0}",
    "yesterday": "Ayer",
    "tomorrow": "Mañana",
    "now": "Ahora mismo"
}
