export default {
    "check": "Controleren",
    "detail": "Detail",
    "dns": "DNS",
    "renew": "Vernieuwen",
    "renewDomain": "Domein vernieuwen",
    "listTitle": "Domeinlijst",
    "newOrder": "Koop een domein",
    "transferDomain": "Domein overdragen",
    "registerTitle": "Domeinaccount registratie",
    "administrationData": "Administratiegegevens",
    "addressData": "Adresgegevens",
    "address": "Adres",
    "address1": "Adres (regel 1)",
    "address2": "Adres (regel 2)",
    "address3": "Adres (regel 3)",
    "city": "Stad",
    "state": "Provincie",
    "country": "Land",
    "zipCode": "Postcode",
    "company": "Bedrijf",
    "companyName": "Bedrijfs- / organisatienaam",
    "domainName": "Domeinnaam",
    "domainStatus": "Domeinstatus",
    "enterContact": "Voer domeincontact in",
    "contactEntered": "Domeincontact ingevoerd",
    "myOwn": "Het domein dat ik heb besteld is van mij",
    "enterBio": "Voer contact in",
    "publicBio": "Publiek contact / Domeineigenaar",
    "personalBio": "Persoonlijk contact / Verantwoordelijk domein",
    "domainPrice": "Domeinprijs",
    "emptyList": "Geen domein vermeld",
    "registrationDate": "Registratiedatum",
    "expirationDate": "Vervaldatum",
    "transferLock": "Overdrachtsvergrendeling",
    "privacyLock": "Privacyvergrendeling",
    "nameServers": "Naamservers",
    "checkHint": "Klik op de controleknop",
    "checkFail": "Mislukt om domeinbeschikbaarheid te controleren",
    "findDomain": "Vind domein",
    "findWait": "Controleren...",
    "findUnavailable": "Domein is momenteel niet beschikbaar.",
    "findNeedData": "We kunnen domeinaankopen niet verwerken totdat u de benodigde gegevens invult.",
    "findNeedDataAction": "Nu invullen",
    "verifyHint": "U moet uw e-mail binnen 15 dagen na aankoop verifiëren, anders zal onze registrar uw domein opschorten!",
    "verifyBtn": "Verificatie-e-mail opnieuw verzenden naar {0}",
    "transferCode": "EPP / Overdrachtscode",
    "showTransferCode": "EPP-code weergeven",
}
