<?php return [
	'emailAlreadyExist' => 'Dit e-mailadres bestaat al',
	'passwordNotLongEnough' => 'Dit wachtwoord is niet lang genoeg',
	'passwordNotMatch' => 'Het bestaande wachtwoord komt niet overeen',
	'invalidCountry' => 'Ongeldige landcode',

	'accountAlreadyAttached' => 'Sorry, dit sociale account is al gekoppeld aan een ander account.',
	'accountCreationExpired' => 'Sorry, we proberen je accountaanmaak te bevestigen, maar je sessie is verlopen. Probeer opnieuw in te loggen.',
	'accountPasswordlessRecovery' => 'Helaas kun je een wachtwoordloos account niet herstellen. Probeer in plaats daarvan een derde partij (Google of GitHub) te gebruiken.',
	'accountDeleteLastMethod' => 'Je kunt je enige inlogmethode niet verwijderen',
	'accountRecountTooFast' => 'Even wachten voordat je opnieuw telt, alsjeblieft',
	'accountDeleteNotDangling' => 'Verwijder eerst alle hosts, domeinen en back-ups',

	'inviteUserNotFound' => 'Deze gebruiker is niet gevonden',
	'inviteQuotaFull' => 'Het maximum aantal teamleden is bereikt, upgrade alsjeblieft',
	'inviteNewFail' => 'Uitnodigen mislukt, misschien zijn ze al toegevoegd?',
	'inviteRemoveFail' => 'Verwijderen mislukt, misschien zijn ze al verwijderd?',

	'inviteCodeInvalid' => 'Ongeldige uitnodigingscode',
	'inviteCodeExpired' => 'Uitnodigingscode is verlopen',

	'unknownAction' => 'Onbekende actie',
	'hostIsNotActive' => 'Kan taak niet toepassen terwijl deze host niet actief is',
	'needVerifyEmail' => 'Verifieer eerst je e-mailadres',
	'hostQuotaLimit' => 'Sorry, je moet je abonnement upgraden om meer hosts aan te maken. Als je dit al hebt gedaan, controleer dan je saldo of neem contact op met de ondersteuning.',
	'usingInternalDomain' => 'Sorry, je kunt onze domeinnaam hier niet gebruiken',
	'usingSubscibingDomain' => 'Sorry, je moet je abonnement upgraden om dit domein te gebruiken',
	'invalidUsername' => 'Ongeldige gebruikersnaam',
	'invalidDomainname' => 'Ongeldige domeinnaam',
	'unchangedUsername' => 'Gebruikersnaam is ongewijzigd',
	'unchangedDomainname' => 'Domeinnaam is ongewijzigd',
	'domainAlreadyExist' => 'Domeinnaam bestaat al',
	'usernameAlreadyExist' => 'Gebruikersnaam bestaat al',
	'usernameTooShort' => 'Gebruikersnaam is te kort',
	'parentNotFound' => 'Hoofddomein is niet gevonden',
	'invalidDeployYaml' => 'Je implementatiescript is geen geldige YAML: {0}',
	'deploymentFailedToReach' => 'We konden geen contact opnemen met server {0} voor deze implementatie: {1}',
	'hostRunnerProgressing' => 'Te snel! Kan niet toepassen terwijl implementaties actief zijn! Even wachten, alsjeblieft.',
	'backupNeedSubscribe' => 'Sorry, je moet je abonnement upgraden om back-ups te maken',
	'backupIsNotActive' => 'Back-upstatus is niet actief, misschien is het al verwijderd',
];
