<?php return [
	'emailAlreadyExist' => 'This email is already exist',
	'passwordNotLongEnough' => 'This password is not long enough',
    'passwordNotMatch' => 'Existing password isn\'t match',
    'invalidCountry' => 'Invalid country code',

    'accountAlreadyAttached' => 'Sorry, this social account is already attached to another account.',
    'accountCreationExpired' => 'Sorry, it seems we\'re trying to confirm your account creation but your session runs out. Try logging in again.',
    'accountPasswordlessRecovery' => 'Unfornatunely you can\'t recover a passwordless account. Please try using third-party user (Google or GitHub) instead.',
    'accountDeleteLastMethod' => 'You can\'t delete your only login method',
    'accountRecountTooFast' => 'Please wait for a moment before recounting',
    'accountDeleteNotDangling' => 'Please delete all hosts, domains and backup first',

    'inviteUserNotFound' => 'User not found',
    'inviteQuotaFull' => 'Team is full, please upgrade',
    'inviteNewFail' => 'Failed to invite, maybe they already been added?',
    'inviteRemoveFail' => 'Failed to remove member, maybe they already been removed?',

    'unknownAction' => 'Unknown Action',
    'hostIsNotActive' => 'Unable to apply task while this host is not active',
    'needVerifyEmail' => 'Please verify your email first',
    'hostQuotaLimit' => 'Sorry, you need to upgrade your plan to create more hosts. If you already have, check your balance or contact support.',
    'usingInternalDomain' => 'Sorry, you can\'t use our domain here',
    'usingSubscibingDomain' => 'Sorry, you need to upgrade your plan to use this domain',
    'invalidUsername' => 'Invalid user name',
    'invalidDomainname' => 'Invalid domain name',
    'unchangedUsername' => 'User name unchanged',
    'unchangedDomainname' => 'Domain name unchanged',
    'domainAlreadyExist' => 'Domain name is already exists',
    'tooShortUsername' => 'User name is too short',
    'parentNotFound' => 'Parent domain is not found',
    'invalidDeployYaml' => 'Your deployment script is not a valid YAML',
    'invalidDeleteState' => 'Can\'t delete while deployments are currently running! Please wait for a moment.',
    'backupNeedSubscribe' => 'Sorry, you need to upgrade your plan to create backups',
    'backupIsNotActive' => 'Backup status is not active, maybe it\'s gone already',
];
