export default {
    "status": {
        "active": "Actief",
        "starting": "Starten",
        "suspended": "Opgeschort",
        "moving": "Verplaatsen",
        "removing": "Verwijderen",
        "removed": "Verwijderd"
    },
    "listTitle": "Websitelijst",
    "newOrder": "Voeg een website toe",
    "tabDetail": "Info",
    "tabSetup": "Instellen",
    "tabManage": "Beheren",
    "tabRunner": "Implementeren",
    "tabDatabase": "Database",
    "tabSubdomain": "Subdomein",
    "tabSoftware": "Software",
    "tabWebhook": "Webhook",
    "tabCheck": "Controleren",
    "tabConnection": "Controleer verbinding",
    "tabFirewall": "Controleer firewall",
    "tabNginx": "Controleer NGINX",
    "tabDns": "Controleer DNS",
    "tabLog": "Controleer logs",
    "tabUser": "Controleer Gebruiker",
    "tabAdmin": "Admin",
    "tabRename": "Wijzig gebruikersnaam",
    "tabCname": "Wijzig domein",
    "tabPasswd": "Wijzig wachtwoord",
    "tabServer": "Regio wijzigen",
    "tabTransfer": "Website overdragen",
    "tabDelete": "Website verwijderen",
    "startFromTemplate": "Begin met een sjabloon",
    "uploadOrClone": "Upload of kloon van internet",
    "seeMoreTemplates": "Zie meer websitetemplates",
    "customTemplate": "Aangepast sjabloon",
    "customDomain": "Aangepast domein",
    "mergeToParentDomain": "Samenvoegen met bovenliggend domein",
    "fetchingDomains": "...Domeinen ophalen",
    "moreTemplates": "Meer sjablonen",
    "portalUsername": "Gebruikersnaam",
    "portalUsernameHint": "Alleen alfanumeriek en streepje",
    "portalPassword": "Wachtwoord",
    "serverName": "Regio",
    "scheme": "Plan",
    "usage": "Gebruik",
    "month": "Maanden",
    "year": "Jaar/jaren",
    "free": "Gratis",
    "database": "Database",
    "additionalServices": "Aanvullende diensten",
    "softwareCompilers": "Softwarecompilers",
    "enableNewFeatures": "Nieuwe functies inschakelen",
    "addHost": "Voeg een website toe",
    "emptyList": "Geen websites vermeld",
    "waitForDataHint": "Gebruiksgegevens verschijnen hier",
    "IPAddress": "IP-adres",
    "openWebsite": "Website openen",
    "openPortal": "Portaal openen",
    "creationDate": "Aanmaakdatum",
    "websiteStatus": "Website Status",
    "websiteUsername": "Website Gebruikersnaam",
    "websiteDomain": "Website Domein",
    "manageHostLogin": "Beheer host login",
    "total": "Totaal",
    "used": "Gebruikt",
    "remainingMonthlyPlan": "Resterend maandelijks plan",
    "remainingAddons": "Resterende add-ons",
    "createDatabase": "Maak {0} Database aan",
    "createDatabaseHint": "Voer de nieuwe {0} databasenaam in",
    "createDatabaseConfirm": "\"{0}\" wordt aangemaakt, doorgaan?",
    "dropDatabase": "{0} Database verwijderen",
    "dropDatabaseConfirm": "\"{0}\" wordt verwijderd, doorgaan?",
    "dropDatabaseConfirm2": "Weet u zeker dat u \"{0}\" wilt uitvoeren? Dit kan niet ongedaan gemaakt worden.",
    "tables": "{0} {0, plural, one {tabel} other {tabellen}}",
    "noSubdomain": "Gebruik een aangepaste domeinnaam om subdomeinen te maken",
    "createSubdomain": "Maak een nieuw subdomein aan",
    "deleteSubdomain": "{0} Subdomein verwijderen",
    "deleteSubdomainConfirm": "\"{0}\" subdomein wordt verwijderd, doorgaan?",
    "deleteSubdomainConfirm2": "Weet u zeker dat u \"{0}\" wilt uitvoeren? Dit kan niet ongedaan gemaakt worden.",
    "enterFullDomainName": "Voer de volledige domeinnaam in",
    "useDefaultCname": "Gebruik de standaard domeinnaam ({0})",
    "useDifferentPassword": "Gebruik een ander wachtwoord voor {0}",
    "redeploy": "Opnieuw implementeren",
    "debugManually": "Handmatig debuggen",
    "startOver": "Opnieuw beginnen",
    "deployScript": "Script implementeren",
    "deployAdd": "Voeg een implementatietaak toe",
    "deployNow": "Uitvoeren!",
    "deployClearHint": "Alle logs wissen?",
    "websiteReadyHint": "Uw site is klaar. Probeer nu te bezoeken?",
    "deployByAdmin": "Uitgevoerd door systeembeheerder",
    "deployOverwriteBanner": "Dit script vervangt alle bestanden van deze website!",
    "deployOverwriteWarn": "U heeft de bronparameter genoemd, wat betekent dat uw HOME-bestand PERMANENT OVERSCHREVEN zal worden. Deze actie kan niet ongedaan worden gemaakt. Weet u het zeker?",
    "deployHelpBtn": "Implementatieconfiguratie referentie",
    "githubWebhook": "Stel webhook in",
    "githubWebhookTitle": "Stel GitHub-actie in",
    "githubWebhookHelp": "U kunt deze webhook gebruiken om uw website automatisch te implementeren wanneer u naar GitHub pusht.",
    "githubWebhookHelpBtn": "GitHub-actie webhook hulp",
    "noWebhook": "Er zijn geen webhooks geconfigureerd voor deze host.",
    "noGitHubApi": "GitHub API is niet beschikbaar",
    "noGitHubApiToken": "GitHub API-token niet gevonden",
    "noGitHubApiHint": "U moet eerst een GitHub-account koppelen met volledige repo-toegang.",
    "noGitHubApiLink": "Koppel nu GitHub",
    "noRepo": "Geen repository gevonden",
    "noRepoHint": "Probeer uw zoekopdracht te verfijnen",
}
