export default {
    'invoiceDomainPurchaseOf': 'Domaankoop van {0}',
    'invoiceDomainExtendOf': 'Domeinverlenging van {0}',
    'invoiceDomainTransferOf': 'Domeinoverdracht van {0}',
    'invoiceTeamPurchaseOf': 'Teamaankoop van {0} plan',
    'invoiceTeamAddons': 'Team Add-ons',
    'invoiceForMonths': ' voor {0, plural, =1{# maand} other{# maanden}}',
    'invoiceForYears': ' voor {0, plural, =1{# jaar} other{# jaren}}',
    'invoiceForYearsAndMonths': ' voor {0, plural, =1{# jaar} other{# jaren}} en {1, plural, =1{# maand} other{# maanden}}',
    'invoiceDataTransferAddonsFor': 'Extra gegevensoverdracht voor {0} GB',
    'invoiceTip': 'Gemaksvergoeding',
    "listTitle": "Websitelijst",
    "newOrder": "Voeg een website toe",
    "tabDetail": "Info",
    "tabSetup": "Instellen",
    "tabManage": "Beheren",
    "tabRunner": "Implementeren",
    "tabWebhook": "Webhook",
    "tabCheck": "Controleren",
    "tabConnection": "Controleer verbinding",
    "tabFirewall": "Controleer firewall",
    "tabNginx": "Controleer NGINX",
    "tabDns": "Controleer DNS",
    "tabLog": "Controleer logs",
    "tabAdmin": "Admin",
    "tabRename": "Wijzig gebruikersnaam",
    "tabCname": "Wijzig domein",
    "tabPasswd": "Wijzig wachtwoord",
    "tabRegion": "Regio wijzigen",
    "tabTransfer": "Website overdragen",
    "tabDelete": "Website verwijderen",
    "startFromTemplate": "Begin met een sjabloon",
    "uploadOrClone": "Upload of kloon van internet",
    "seeMoreTemplates": "Zie meer websitetemplates",
    "customTemplate": "Aangepast sjabloon",
    "customDomain": "Aangepast domein",
    "mergeToParentDomain": "Samenvoegen met bovenliggend domein",
    "fetchingDomains": "...Domeinen ophalen",
    "moreTemplates": "Meer sjablonen",
    "portalUsername": "Gebruikersnaam",
    "portalUsernameHint": "Alleen alfanumeriek en streepje",
    "portalPassword": "Wachtwoord",
    "slaveServer": "Regio",
    "scheme": "Plan",
    "usage": "Gebruik",
    "month": "Maanden",
    "year": "Jaar/jaren",
    "free": "Gratis",
    "database": "Database",
    "additionalServices": "Aanvullende diensten",
    "softwareCompilers": "Softwarecompilers",
    "enableNewFeatures": "Nieuwe functies inschakelen",
    "addHost": "Voeg een website toe",
    "emptyList": "Geen websites vermeld",
    "waitForDataHint": "Gebruiksgegevens verschijnen hier. Kom de volgende dag terug om de gegevens te zien.",
    "slaveID": "Slave ID",
    "IPAddress": "IP-adres",
    "openWebsite": "Website openen",
    "openPortal": "Portaal openen",
    "hostStatus": "Hoststatus",
    "creationDate": "Aanmaakdatum",
    "usernameHost": "Host gebruikersnaam",
    "domainHost": "Host domein",
    "manageHostLogin": "Beheer host login",
    "total": "Totaal",
    "used": "Gebruikt",
    "remainingMonthlyPlan": "Resterend maandelijks plan",
    "remainingAddons": "Resterende add-ons",
    "planDetail": "{0} plan, {1} schijfruimte, {2} maandelijkse bandbreedte.",
    "emptyForDefaultCname": "Laat leeg voor standaard ({0})",
    "redeploy": "Opnieuw implementeren",
    "debugManually": "Handmatig debuggen",
    "startOver": "Opnieuw beginnen",
    "deployScript": "Script implementeren",
    "deployAdd": "Voeg een implementatietaak toe",
    "deployNow": "Uitvoeren!",
    "deployClearHint": "Alle logs wissen?",
    "websiteReadyHint": "Uw site is klaar. Probeer nu te bezoeken?",
    "deployByAdmin": "Uitgevoerd door systeembeheerder",
    "deployOverwriteBanner": "Dit script vervangt alle bestanden van deze website!",
    "deployOverwriteWarn": "U heeft de bronparameter genoemd, wat betekent dat uw HOME-bestand PERMANENT OVERSCHREVEN zal worden. Deze actie kan niet ongedaan worden gemaakt. Weet u het zeker?",
    "deployHelpBtn": "Implementatieconfiguratie referentie",
    "githubWebhook": "Stel webhook in",
    "githubWebhookTitle": "Stel GitHub-actie in",
    "githubWebhookHelp": "U kunt deze webhook gebruiken om uw website automatisch te implementeren wanneer u naar GitHub pusht.",
    "githubWebhookHelpBtn": "GitHub-actie webhook hulp",
    "noWebhook": "Er zijn geen webhooks geconfigureerd voor deze host.",
    "noGitHubApi": "GitHub API is niet beschikbaar",
    "noGitHubApiToken": "GitHub API-token niet gevonden",
    "noGitHubApiHint": "U moet eerst een GitHub-account koppelen met volledige repo-toegang.",
    "noGitHubApiLink": "Koppel nu GitHub",
    "noRepo": "Geen repository gevonden",
    "noRepoHint": "Probeer uw zoekopdracht te verfijnen",
}
