<?php return [
    'code' => 'nl',
    'codename' => 'Nederlands',
    'codedir' => 'ltr',
    'login' => 'Inloggen',
    'register' => 'Registreren',
    'email' => 'E-mail',
    'enterToPortal' => 'Inloggen op portaal',
    'registerToPortal' => 'Registreren voor portaal',
    'registerWithEmail' => 'Registreren met e-mail',
    'forgotPrompt' => 'Wachtwoord vergeten?',
    'recoverYourPassword' => 'Herstel je wachtwoord',
    'recoverYourPasswordHint' => 'Voer een nieuw wachtwoord in om te wijzigen',
    'report' => 'Rapporteren',
    'reportPrompt' => 'Meld verdachte activiteiten binnen het DOM Cloud-netwerk. Inhoud wordt onmiddellijk verwijderd als de gerapporteerde website aan onze criteria voldoet.',
    'reportAbuse' => 'Misbruik melden',
    'reportDomain' => 'Domein om te melden',
    'ok' => 'OK',
    'back' => 'Terug',
    'or' => 'Of',
    'signInWith' => 'Inloggen met {0}',
    'wrongLogin' => 'Verkeerd e-mailadres of wachtwoord',
    'registerAgreement' => 'Door te registreren gaat u akkoord met onze <a href="//domcloud.co/service" target="_blank">Servicevoorwaarden</a>.',
    'emailSent' => 'De verificatiemail is verzonden, controleer uw inbox (en spambox) voordat u inlogt.',
    'oAuthFail' => 'Het lijkt erop dat uw poging om in te loggen via een derde partij is mislukt. Dit wordt meestal veroorzaakt door een time-out of een niet-geverifieerd primair e-mailadres dat aan dat account is gekoppeld.',
    'passReset' => 'Uw wachtwoord is succesvol gereset. Log in met uw nieuwe wachtwoord.',
    'thanksForVerify' => 'Bedankt, uw e-mail is geverifieerd',
    'password' => 'Wachtwoord',
    'passwordAgain' => 'Wachtwoord (nogmaals)',
    'fullName' => 'Volledige naam',
    'activeEmail' => 'Actieve e-mail',
];
