export default {
    "check": "Cek",
    "detail": "Detail",
    "dns": "DNS",
    "renew": "Renew",
    "renewDomain": "Renew Domain",
    "listTitle": "Daftar Domain",
    "newOrder": "Beli Domain",
    "transferDomain": "Transfer Domain",
    "registerTitle": "Registrasi Akun Domain",
    "administrationData": "Data Administrasi",
    "addressData": "Data Alamat",
    "address": "Alamat",
    "address1": "Alamat (Baris 1)",
    "address2": "Alamat (Baris 2)",
    "address3": "Alamat (Baris 3)",
    "city": "Kota",
    "state": "Provinsi",
    "country": "Negara",
    "zipCode": "Kode Zip",
    "company": "Company",
    "companyName": "Company / Organization Name",
    "domainName": "Domain name",
    "domainStatus": "Domain status",
    "formatInvoice": "Pembayaran domain {0} seharga {1}",
    "fillBiodata": "Isi Biodata Domain",
    "myOwn": "Domain yang saya pesan merupakan milik sendiri",
    "enterBio": "Masukkan Biodata",
    "publicBio": "Biodata Publik / Pemilik Domain",
    "personalBio": "Biodata Pribadi / Penanggung-jawab Domain",
    "domainPrice": "Domain Price",
    "emptyList": "Daftar domain kosong",
    "registrationDate": "Registration Date",
    "expirationDate": "Expiration Date",
    "transferLock": "Transfer Lock",
    "privacyLock": "Privacy Lock",
    "nameServers": "Name servers",
    "findDomain": "Find Domain",
    "findWait": "Checking ...",
    "findUnavailable": "Domain is currently unavailable.",
    "findNeedData": "We cannot process domain purchases until you fill in the data we need.",
    "findNeedDataAction": "Fill now",
    "transferCode": "EPP / Transfer Code",
    "showTransferCode": "Show EPP Code",
}
