<?php return [
    'emailAlreadyExist' => 'Email ini sudah ada',
    'passwordNotLongEnough' => 'Kata sandi ini tidak cukup panjang',
    'passwordNotMatch' => 'Kata sandi yang ada tidak cocok',
    'invalidCountry' => 'Kode negara tidak valid',

    'accountAlreadyAttached' => 'Maaf, akun sosial ini sudah terhubung ke akun lain.',
    'accountCreationExpired' => 'Maaf, sepertinya kami mencoba mengonfirmasi pembuatan akun Anda tetapi sesi Anda berakhir. Cobalah untuk masuk lagi.',
    'accountPasswordlessRecovery' => 'Sayangnya Anda tidak bisa memulihkan akun tanpa kata sandi. Silakan coba menggunakan pengguna pihak ketiga (Google atau GitHub) sebagai gantinya.',
    'accountDeleteLastMethod' => 'Anda tidak dapat menghapus satu-satunya metode login Anda',
    'accountRecountTooFast' => 'Harap tunggu sebentar sebelum menghitung ulang',
    'accountDeleteNotDangling' => 'Harap hapus semua host, domain, dan cadangan terlebih dahulu',

    'inviteUserNotFound' => 'Pengguna tidak ditemukan',
    'inviteQuotaFull' => 'Tim penuh, silakan tingkatkan',
    'inviteNewFail' => 'Gagal mengundang, mungkin mereka sudah ditambahkan?',
    'inviteRemoveFail' => 'Gagal menghapus anggota, mungkin mereka sudah dihapus?',

    'unknownAction' => 'Aksi tidak dikenal',
    'hostIsNotActive' => 'Tidak dapat menerapkan tugas saat host ini tidak aktif',
    'needVerifyEmail' => 'Harap verifikasi email Anda terlebih dahulu',
    'hostQuotaLimit' => 'Maaf, Anda perlu meningkatkan paket Anda untuk membuat lebih banyak host. Jika sudah, periksa saldo Anda atau hubungi dukungan.',
    'usingInternalDomain' => 'Maaf, Anda tidak bisa menggunakan domain kami di sini',
    'usingSubscibingDomain' => 'Maaf, Anda perlu meningkatkan paket Anda untuk menggunakan domain ini',
    'invalidUsername' => 'Nama pengguna tidak valid',
    'invalidDomainname' => 'Nama domain tidak valid',
    'unchangedUsername' => 'Nama pengguna tidak berubah',
    'unchangedDomainname' => 'Nama domain tidak berubah',
    'domainAlreadyExist' => 'Nama domain sudah ada',
    'tooShortUsername' => 'Nama pengguna terlalu pendek',
    'parentNotFound' => 'Domain induk tidak ditemukan',
    'invalidDeployYaml' => 'Skrip deployment Anda bukan YAML yang valid',
    'invalidDeleteState' => 'Tidak bisa menghapus saat deployment sedang berjalan! Harap tunggu sebentar.',
    'backupNeedSubscribe' => 'Maaf, Anda perlu meningkatkan paket Anda untuk membuat cadangan',
    'backupIsNotActive' => 'Status cadangan tidak aktif, mungkin sudah hilang',
];
