export default {
    'invoiceDomainPurchaseOf': 'Pembelian Domain {0}',
    'invoiceDomainExtendOf': 'Perpanjangan Domain {0}',
    'invoiceDomainTransferOf': 'Transfer Domain {0}',
    'invoiceTeamPurchaseOf': 'Pembelian Tim dengan Paket {0}',
    'invoiceTeamAddons': 'Add-ons Tim',
    'invoiceForMonths': ' selama {0, plural, =1{# bulan} other{# bulan}}',
    'invoiceForYears': ' selama {0, plural, =1{# tahun} other{# tahun}}',
    'invoiceForYearsAndMonths': ' selama {0, plural, =1{# tahun} other{# tahun}} dan {1, plural, =1{# bulan} other{# bulan}}',
    'invoiceDataTransferAddonsFor': 'Transfer Data Tambahan sebesar {0} GB',
    'invoiceTip': 'Biaya Admin',
    "listTitle": "Daftar Hosting",
    "newOrder": "Tambah Hosting",
    "tabDetail": "Info",
    "tabSetup": "Setup",
    "tabManage": "Kelola",
    "tabRunner": "Deploy",
    "tabWebhook": "Webhook",
    "tabCheck": "Cek",
    "tabConnection": "Cek Koneksi",
    "tabFirewall": "Cek Firewall",
    "tabNginx": "Cek NGINX",
    "tabDns": "Cek DNS",
    "tabLog": "Cek Log",
    "tabAdmin": "Admin",
    "tabRename": "Ubah Username",
    "tabCname": "Ubah Domain",
    "tabPasswd": "Ubah Password",
    "tabRegion": "Ubah Wilayah",
    "tabTransfer": "Transfer Website",
    "tabDelete": "Hapus Website",
    "startFromTemplate": "Mulai dari template",
    "uploadOrClone": "Upload atau klon dari Internet",
    "seeMoreTemplates": "See more web templates",
    "customTemplate": "Template kustom",
    "customDomain": "Domain kustom",
    "mergeToParentDomain": "Gabungkan ke domain induk",
    "fetchingDomains": "...Mengambil domain",
    "moreTemplates": "Lebih banyak template",
    "portalUsername": "Username",
    "portalUsernameHint": "Hanya huruf, digit, dan strip",
    "portalPassword": "Password",
    "slaveServer": "Wilayah",
    "scheme": "Paket",
    "usage": "Penggunaan",
    "month": "Bulan",
    "year": "Tahun",
    "free": "Kosong",
    "database": "Database",
    "additionalServices": "Layanan Tambahan",
    "softwareCompilers": "Kompiler Perangkat Lunak",
    "enableNewFeatures": "Aktifkan Fitur Baru",
    "addHost": "Tambah Hosting",
    "emptyList": "Daftar hosting kosong",
    "waitForDataHint": "Data penggunaan hosting akan muncul di sini. Tunggulah satu jam kemudian agar datanya muncul.",
    "slaveID": "ID Slave",
    "IPAddress": "Alamat IP",
    "openWebsite": "Buka Website",
    "openPortal": "Buka Portal",
    "hostStatus": "Status Hosting",
    "creationDate": "Tanggal Pembuatan",
    "usernameHost": "Username Hosting",
    "domainHost": "Domain Hosting",
    "manageHostLogin": "Atur Login Hosting",
    "total": "Total",
    "used": "Digunakan",
    "remainingMonthlyPlan": "Sisa Bulanan Paket",
    "remainingAddons": "Sisa Add-Ons",
    "planDetail": "Paket {0}, {1} kapasitas disk, {2} data bulanan.",
    "emptyForDefaultCname": "Biarkan kosong untuk default ({0})",
    "redeploy": "Deploy Ulang",
    "debugManually": "Debug Secara Manual",
    "startOver": "Mulai Dari Awal",
    "deployScript": "Deploy Script",
    "deployAdd": "Tambahkan tugas deploy",
    "deployNow": "Eksekusi!",
    "deployClearHint": "Hapus semua deploy?",
    "websiteReadyHint": "Situs Anda sudah siap. Coba kunjungi sekarang?",
    "deployByAdmin": "Dijalankan Oleh Mod Sistem",
    "deployOverwriteBanner": "Script ini akan menggantikan semua file dari situs web ini!",
    "deployOverwriteWarn": "Anda menyebutkan parameter sumber, yang berarti file HOME Anda akan di-OVERWRITE secara PERMANEN. Aksi ini tidak dapat dikembalikan. Apakah Anda yakin?",
    "deployHelpBtn": "Referensi Konfigurasi Deploy",
    "githubWebhook": "Setup Webhook",
    "githubWebhookTitle": "Setup Aksi GitHub",
    "githubWebhookHelp": "Anda dapat menggunakan webhook ini untuk secara otomatis mendeploy website Anda saat Anda melakukan push ke GitHub.",
    "githubWebhookHelpBtn": "Bantuan Webhook Aksi GitHub",
    "noWebhook": "Tidak ada webhook yang dikonfigurasi untuk host ini.",
    "noGitHubApi": "API GitHub tidak tersedia",
    "noGitHubApiToken": "Token API GitHub tidak ditemukan",
    "noGitHubApiHint": "Anda perlu menghubungkan akun GitHub terlebih dahulu dengan akses repo penuh.",
    "noGitHubApiLink": "Hubungkan GitHub Sekarang",
    "noRepo": "Tidak ada repositori yang ditemukan",
    "noRepoHint": "Coba mempersempit pencarian Anda",
}
