<?php return [

	'invoiceDomainPurchaseOf' => 'Pembelian Domain {0}',
	'invoiceDomainExtendOf' => 'Perpanjangan Domain {0}',
	'invoiceDomainTransferOf' => 'Transfer Domain {0}',
	'invoiceTeamPurchaseOf' => 'Pembelian Paket Web {0}',
	'invoiceTeamAddons' => 'Team Add-ons',
	'invoiceForMonths' => ' untuk {0}',
	'invoiceForYears' => ' untuk {0}',
	'invoiceForYearsAndMonths' => ' untuk {0} dan {1}',
	'invoiceDataTransferAddonsFor' => 'Tambahan data transfer sebanyak {0} GB',
	'invoiceTip' => 'Convenience Fee',
	
	'repoOk' => 'Repo dapat diakses',
	'repoNoRefs' => 'Repo dapat diakses tetapi tidak ada referensi yang cocok',
	'repoNoAccess' => 'Repo tidak dapat diakses',
	'fileOk' => 'File ZIP dapat diakses',
	'fileNoZip' => 'File bukan file ZIP',
	'fileNoAccess' => 'File tidak dapat diakses',
	'fileRequired' => 'File repositori dibutuhkan',
	'uploadFileRequired' => 'Upload file dibutuhkan',
	'uploadFileMustZip' => 'File yang diupload harus berupa file ZIP',

	'head_violation_storage' => 'Pelanggaran Kapasitas Penyimpanan',
	'body_violation_storage' => 'Akun Anda telah melampaui 3x batas kapasitas penyimpanan. Maaf, kami harus mengambil tindakan. Kami telah menghapus semua situs web Anda hingga kapasitas penyimpanan terpenuhi.',
	'head_violation_expiry_paid' => 'Pelanggaran Tanggal Kedaluwarsa',
	'body_violation_expiry_paid' => 'Akun Anda telah melampaui tanggal kedaluwarsa. Kami mengembalikan akun Anda menjadi akun gratis. Perhatikan bahwa jika situs web Anda sudah melebihi batas kuota gratis, mungkin ada pemberitahuan lain yang masuk dalam beberapa hari. Harap periksa batas akun Anda sebelum hal itu terjadi.',
	'head_violation_expiry_free' => 'Pelanggaran Tanggal Kedaluwarsa',
	'body_violation_expiry_free' => 'Akun Anda telah melampaui dua minggu setelah tanggal kedaluwarsa. Maaf, kami harus mengambil tindakan. Kami telah menghapus semua situs web Anda secara permanen untuk memberi ruang bagi yang lain.',
	
	'head_over_expiry_paid' => 'Tanggal Kedaluwarsa Terlampaui',
	'body_over_expiry_paid' => 'Akun Anda telah melampaui tanggal kedaluwarsa. Harap perbarui langganan akun Anda. Harap perhatikan jika Anda tidak memperbarui akun Anda dalam waktu 2 minggu, akun Anda akan diubah menjadi akun gratis.',
	'head_over_expiry_free' => 'Tanggal Kedaluwarsa Terlampaui',
	'body_over_expiry_free' => 'Akun Anda telah melampaui tanggal kedaluwarsa. Kami harus menonaktifkan situs web Anda untuk mendapatkan perhatian Anda. Untuk mengaktifkannya kembali, tinggal login kembali. Harap perhatikan bahwa semua situs web Anda akan dihapus jika Anda tidak masuk lagi dalam waktu 2 minggu.',
	'head_over_storage' => 'Batas Penyimpanan Terlampaui',
	'body_over_storage' => 'Akun Anda telah melampaui batas penyimpanan. Kami harus menonaktifkan situs web Anda untuk menarik perhatian Anda. Untuk mendapatkan kembali situs web Anda, kosongkan beberapa ruang dengan menghapus file yang tidak perlu. Perhatikan bahwa jika Anda mengabaikan pesan ini dan terus mengisi penyimpanan, kami dapat menghapus situs web Anda secara permanen.',
	'head_over_network' => 'Batas Bandwidth Terlampaui',
	'body_over_network' => 'Akun Anda telah melampaui batas lebar pita. Kami harus menonaktifkan situs web Anda untuk menarik perhatian Anda. Sayangnya, tidak ada cara cepat untuk mendapatkan kembali situs web Anda secara instan, Anda harus menunggu hingga bulan depan.',
	'head_over_instance' => 'Batas Mesin Terlampaui',
	'body_over_instance' => 'Akun Anda telah melampaui batas jumlah contoh/situs web. Ini aneh (kami harus mencegah Anda melakukan itu). Meskipun demikian, kami harus menonaktifkan situs web Anda untuk mendapatkan perhatian Anda. Harap hapus beberapa situs web yang tidak penting untuk mendapatkan kembali situs web Anda yang lain.',
	
	'head_warn_expiry_paid' => 'Peringatan Tanggal Kedaluwarsa',
	'body_warn_expiry_paid' => 'Akun Anda akan kedaluwarsa dalam 3 hari. Harap perbarui akun Anda agar akun Anda tetap dalam paket saat ini.',
	'head_warn_expiry_free' => 'Peringatan Tanggal Kedaluwarsa',
	'body_warn_expiry_free' => 'Akun Anda akan kedaluwarsa dalam 3 hari. Karena Anda menggunakan paket gratis, harap perbarui akun Anda dengan masuk lagi. Akun Anda akan tersedia selama 30 hari lagi.',
	'head_warn_storage' => 'Peringatan Batas Penyimpanan',
	'body_warn_storage' => 'Situs web Anda mengambil penyimpanan hingga mendekati batasnya. Harap kosongkan beberapa ruang dengan menghapus file yang tidak perlu.',
	'head_warn_network' => 'Peringatan Batas Bandwidth',
	'body_warn_network' => 'Situs web Anda mengambil data jaringan hingga mendekati batasnya. Sayangnya tidak banyak yang dapat Anda lakukan hingga tersedia lagi bulan depan.',
];
