<?php return [
	'code' => 'id',
	'codename' => 'Indonesia',
	'currency' => 'idr',
	'login' => 'Masuk',
	'register' => 'Daftar',
	'email' => 'Email',
	'enterToPortal' => 'Masuk ke Portal',
	'registerToPortal' => 'Daftar ke Portal',
	'registerWithEmail' => 'Daftar dengan Email',
	'forgotPrompt' => 'Lupa Password?',
	'recoverYourPassword' => 'Pulihkan Password Anda',
	'recoverYourPasswordHint' => 'Masukkan password baru untuk diganti',

	'back' => 'Kembali',
	'or' => 'Atau',
	'signInWith' => 'Masuk dengan {0}',
	'wrongLogin' => 'Salah email atau password',
	'wrongEmail' => 'Salah email?',
	'registerAgreement' => 'Dengan mendaftar anda menyetujui <a href="//domcloud.co/service" target="_blank">Kebijakan Layanan</a> Kami',
	'emailSent' => 'Email untuk verifikasi telah dikirim, mohon cek inbox (dan spam box) anda sebelum masuk.',
	'oAuthFail' => 'Tampaknya upaya Anda dengan user pihak ketiga gagal. Hal ini biasanya disebabkan karena waktunya habis atau email utama yang terikat dengan akun tersebut belum terverifikasi.',
	'passReset' => 'Password anda sudah disetel ulang. Mohon masuk dengan password baru anda.',
	'thanksForVerify' => 'Terima Kasih, email kamu sudah diverifikasi',

	'password' => 'Password',
	'passwordAgain' => 'Password (Lagi)',
	'fullName' => 'Nama Lengkap',
	'activeEmail' => 'Email Aktif',
];
