export default {
    "code": "id",
    "codename": "Bahasa Indonesia",
    "codedir":"ltr",
    "appTitle": "DOM Cloud",
    "appTitleLong": "DOM Cloud Hosting",
    // Kata-kata umum
    "logout": "Keluar",
    "profile": "Profil",
    "status": "Status",
    "verifyStatus": "Status verifikasi",
    "hosting": "Situs web",
    "domain": "Domain",
    "backup": "Cadangan",
    "owner": "Pemilik",
    "admin": "Admin",
    "member": "Anggota",
    "team": "Tim",
    "email": "Email",
    "storage": "Penyimpanan",
    "bandwidth": "Bandwidth",
    "instances": "Instance",
    "users": "Pengguna",
    "details": "Detail",
    "members": "Anggota",
    "upgrade": "Upgrade",
    "otherTeams": "Tim Lainnya",
    "hostname": "Hostname",
    "port": "Port",
    "username": "Nama pengguna",
    "password": "Kata sandi",
    "server": "Server",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    // Bagian Bantuan
    "help": "Bantuan",
    "helpDocs": "Dokumen",
    "helpEmail": "Email",
    "helpChat": "Obrolan",
    "helpUpdates": "Pembaruan",
    // Bagian Profil
    "country": "Negara",
    "chooseCountry": "Pilih negara",
    "expiration": "Kadaluarsa",
    "resendConfirmationEmail": "Kirim ulang Email Konfirmasi",
    "learnMore": "Pelajari lebih lanjut",
    "passwordNotice": "Anda tidak perlu mengingat kata sandi ini",
    "lastUpdatedAt": "Terakhir diperbarui pada",
    "language": "Bahasa",
    "theme": "Tema",
    "themeDark": "Selalu Gelap",
    "themeLight": "Selalu Terang",
    "themeSystem": "Pengaturan Sistem Default",
    "role": "Peran",
    "action": "Aksi",
    "currencyInput": "Mata Uang",
    "invoiceNoteInput": "Kontak Tagihan",
    "defaultServerInput": "Server Default",
    "defaultServerInputNone": "Tidak Ada (tanyakan kepada saya)",
    "name": "Nama",
    "phone": "Nomor Telepon",
    "phoneHint": "Nomor Telepon Lengkap (diawali dengan +)",
    "phoneAlt": "Nomor Telepon Alternatif",
    "fullName": "Nama Lengkap",
    "activeEmail": "Email Aktif",
    "newPassword": "Kata Sandi Baru",
    "editProfile": "Edit Profil",
    "saveProfile": "Simpan Profil",
    "deleteAccount": "Hapus Akun",
    "loginMethods": "Metode Login",
    "loginRemoveConfirm": "Apakah Anda yakin ingin menghapus metode login ini?",
    "loginAdd": "Tambahkan atau ganti metode login",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "Email + Kata Sandi",
    "loginVia": "melalui {0}",
    "passwordConfirm": "Masukkan kata sandi akun saat ini (jika ada)",
    "passwordSetInput": "Masukkan kata sandi baru, minimal 8 karakter",
    "passwordSetCancel": "Pengaturan kata sandi untuk akun ini telah dibatalkan",
    "passwordSetCancelLength": "Pengaturan kata sandi dibatalkan, minimal harus 8 karakter",
    // Manajemen Tim
    "yearDuration": "Durasi dalam tahun",
    "monthDuration": "Durasi dalam bulan",
    "annualSaving": "Simpan 16%",
    "totalPayment": "Total Pembayaran",
    "expirationDate": "Tanggal Kadaluarsa",
    "orderNow": "Pesan Sekarang",
    "invoice": "Faktur",
    "pendingInvoices": "Faktur yang Tertunda",
    "noPendingInvoices": "Anda tidak memiliki faktur tertunda saat ini.",
    "mixedCurrency": "Faktur yang dipilih memiliki mata uang yang berbeda",
    "currentPlan": "Rencana Saat Ini",
    "currentPlanDescription": "Dengan biaya <b>{0}</b> per bulan dengan masa berlaku <b>{1}</b>",
    "priceDescription": "{0} / bulan",
    "monthlyLimits": "Batas Bulanan",
    "storageLimit": "{0} GB Penyimpanan",
    "networkLimit": "{0} GB Jaringan",
    "instanceLimit": "{0} {0, plural, one {Instance} other {Instance}}",
    "userLimit": "{0} {0, plural, one {Pengguna} other {Pengguna}}",
    "autoStop": "Berhenti Otomatis saat mencapai batas",
    "noFreeDomain": "Tidak ada domain *.domcloud.dev",
    "withFreeDomain": "Domain gratis *.domcloud.dev",
    "withBackup": "Cadangan otomatis pada tingkat server",
    "withDocker": "Docker dan aplikasi yang berjalan lama",
    "storageUsage": "Penggunaan Penyimpanan",
    "storageUsageCap": "dari total {0}",
    "bandwidthUsed": "Pemakaian Lebar Pita",
    "bandwidthUsedCap": "dari {0} bulanan",
    "instancesActive": "Instance Aktif",
    "instancesActiveCap": "dari {0} situs web",
    "teamUsers": "Pengguna Tim",
    "teamUsersCap": "dari maksimum {0} pengguna",
    "remainingAvailable": "Tersedia Tersisa",
    "remainingStorage": "Penyimpanan Gratis",
    "remainingNetwork": "Data Jaringan Tersisa",
    "remainingInstance": "Instance Tersisa",
    "dataTransfer": "Transfer Data",
    "expires": "Kadaluarsa {0}",
    "expiresAt": "Kadaluarsa pada {0}",
    "expireFreeHint": `
    Tanggal kadaluarsa secara otomatis diperpanjang (diperpanjang selama 2 bulan) 
    setiap kali Anda login atau situs web Anda memiliki cukup lalu lintas jaringan (>50 MB)
    pada akhir bulan.
    `,
    "discountedAt": "Diskon {0}",
    "extendingCurrentExpiryDate": "Memperpanjang tanggal kadaluarsa saat ini",
    "usersLimitHint": "{0} {0, plural, one {pengguna} other {pengguna}} di tim ini, {1} {1, plural, one {pengguna} other {pengguna}} dapat ditambahkan lagi",
    "emailToInvite": "Email untuk diundang",
    "selectRole": "Pilih peran",
    // Tombol
    "info": "Info",
    "total": "Total",
    "back": "Kembali",
    "add": "Tambahkan",
    "addMember": "Tambahkan Anggota",
    "confirmRemoveMember": "Apakah Anda yakin ingin menghapus anggota ini?",
    "edit": "Sunting",
    "apply": "Terapkan",
    "save": "Simpan",
    "clear": "Bersihkan",
    "update": "Perbarui",
    "updateUsage": "Perbarui Penggunaan",
    "change": "Ubah",
    "archives": "Arsip",
    "renew": "Perbaharui",
    "extend": "Perpanjang",
    "topup": "Isi ulang",
    "processing": "Sedang diproses",
    "cancel": "Batal",
    "print": "Cetak",
    "why": "Mengapa?",
    "pay": "Bayar",
    "payAccept": "Kami menerima pembayaran melalui",
    // Kesalahan
    "loading": "Mengumpulkan data ...",
    "fetchError": "Kesalahan mengambil data! Coba lagi nanti",
    "notFound": "Tidak Ditemukan",
    "notFoundDescription": "Halaman yang Anda cari tidak ada.",
    "notFoundLink": "Kembali ke beranda",
}
