export default {
    "check": "확인",
    "detail": "세부 사항",
    "dns": "DNS",
    "renew": "갱신",
    "renewDomain": "도메인 갱신",
    "listTitle": "도메인 목록",
    "newOrder": "도메인 구매",
    "transferDomain": "도메인 이전",
    "registerTitle": "도메인 계정 등록",
    "administrationData": "관리 데이터",
    "addressData": "주소 데이터",
    "address": "주소",
    "address1": "주소 (1행)",
    "address2": "주소 (2행)",
    "address3": "주소 (3행)",
    "city": "도시",
    "state": "주",
    "country": "국가",
    "zipCode": "우편 번호",
    "company": "회사",
    "companyName": "회사 / 조직 이름",
    "domainName": "도메인 이름",
    "domainStatus": "도메인 상태",
    "enterContact": "도메인 연락처 입력",
    "contactEntered": "도메인 연락처 입력됨",
    "myOwn": "내가 주문한 도메인은 내 것입니다",
    "enterBio": "연락처 입력",
    "publicBio": "공개 연락처 / 도메인 소유자",
    "personalBio": "개인 연락처 / 책임 도메인",
    "domainPrice": "도메인 가격",
    "emptyList": "나열된 도메인이 없습니다",
    "registrationDate": "등록 날짜",
    "expirationDate": "만료 날짜",
    "transferLock": "이전 잠금",
    "privacyLock": "프라이버시 잠금",
    "nameServers": "네임 서버",
    "checkHint": "확인 버튼을 클릭하세요",
    "checkFail": "도메인 가용성 확인 실패",
    "findDomain": "도메인 찾기",
    "findWait": "확인 중...",
    "findUnavailable": "현재 도메인을 사용할 수 없습니다.",
    "findNeedData": "필요한 데이터를 입력할 때까지 도메인 구매를 처리할 수 없습니다.",
    "findNeedDataAction": "지금 입력",
    "verifyHint": "구매 후 15일 이내에 이메일을 확인해야 합니다. 그렇지 않으면 등록 기관이 도메인을 중지합니다!",
    "verifyBtn": "{0}으로 확인 이메일 다시 보내기",
    "transferCode": "EPP / 이전 코드",
    "showTransferCode": "EPP 코드 표시",
}
