<?php return [
	'emailAlreadyExist' => '이 이메일은 이미 존재합니다',
	'passwordNotLongEnough' => '비밀번호가 충분히 길지 않습니다',
	'passwordNotMatch' => '기존 비밀번호가 일치하지 않습니다',
	'invalidCountry' => '잘못된 국가 코드',

	'accountAlreadyAttached' => '죄송합니다. 이 소셜 계정은 다른 계정에 이미 연결되어 있습니다.',
	'accountCreationExpired' => '죄송합니다. 계정 생성을 확인하려고 했으나 세션이 만료되었습니다. 다시 로그인하세요.',
	'accountPasswordlessRecovery' => '비밀번호 없는 계정을 복구할 수 없습니다. 대신 Google 또는 GitHub과 같은 타사 계정을 사용해 보세요.',
	'accountDeleteLastMethod' => '로그인 방법을 하나만 남겨둘 수 없습니다',
	'accountRecountTooFast' => '잠시 후에 다시 시도하세요',
	'accountDeleteNotDangling' => '모든 호스트, 도메인 및 백업을 먼저 삭제하세요',

	'inviteUserNotFound' => '사용자를 찾을 수 없습니다',
	'inviteQuotaFull' => '팀 멤버 수가 최대치에 도달했습니다. 업그레이드하세요.',
	'inviteNewFail' => '초대에 실패했습니다. 이미 추가되었을 수 있습니다.',
	'inviteRemoveFail' => '멤버 제거에 실패했습니다. 이미 제거되었을 수 있습니다.',

	'inviteCodeInvalid' => '초대 코드가 유효하지 않습니다',
	'inviteCodeExpired' => '초대 코드가 만료되었습니다',

	'unknownAction' => '알 수 없는 작업',
	'hostIsNotActive' => '호스트가 활성 상태가 아닐 때 작업을 적용할 수 없습니다',
	'needVerifyEmail' => '이메일을 먼저 확인하세요',
	'hostQuotaLimit' => '죄송합니다. 더 많은 호스트를 생성하려면 요금제를 업그레이드해야 합니다. 이미 업그레이드했다면 잔액을 확인하거나 지원 팀에 문의하세요.',
	'usingInternalDomain' => '죄송합니다. 여기에서 도메인을 사용할 수 없습니다',
	'usingSubscibingDomain' => '죄송합니다. 이 도메인을 사용하려면 요금제를 업그레이드해야 합니다',
	'invalidUsername' => '잘못된 사용자 이름',
	'invalidDomainname' => '잘못된 도메인 이름',
	'unchangedUsername' => '사용자 이름이 변경되지 않았습니다',
	'unchangedDomainname' => '도메인 이름이 변경되지 않았습니다',
	'domainAlreadyExist' => '도메인 이름이 이미 존재합니다',
	'usernameAlreadyExist' => '사용자 이름이 이미 존재합니다',
	'usernameTooShort' => '사용자 이름이 너무 짧습니다',
	'parentNotFound' => '상위 도메인을 찾을 수 없습니다',
	'invalidDeployYaml' => '배포 스크립트가 유효한 YAML이 아닙니다: {0}',
	'deploymentFailedToReach' => '이 배포를 위해 서버 {0}에 연결하지 못했습니다: {1}',
	'hostRunnerProgressing' => '너무 빠릅니다! 배포가 현재 실행 중일 때 적용할 수 없습니다! 잠시만 기다려주세요.',
	'backupNeedSubscribe' => '죄송합니다. 백업을 생성하려면 요금제를 업그레이드해야 합니다.',
	'backupIsNotActive' => '백업 상태가 비활성화되었습니다. 이미 삭제되었을 수 있습니다.',
];
