export default {
    'invoiceDomainPurchaseOf': '{0}의 도메인 구매',
    'invoiceDomainExtendOf': '{0}의 도메인 연장',
    'invoiceDomainTransferOf': '{0}의 도메인 이전',
    'invoiceTeamPurchaseOf': '{0} 플랜의 팀 구매',
    'invoiceTeamAddons': '팀 추가 기능',
    'invoiceForMonths': ' {0, plural, =1{# 달} other{# 달}} 동안',
    'invoiceForYears': ' {0, plural, =1{# 년} other{# 년}} 동안',
    'invoiceForYearsAndMonths': ' {0, plural, =1{# 년} other{# 년}} 동안 및 {1, plural, =1{# 달} other{# 달}} 동안',
    'invoiceDataTransferAddonsFor': '{0} GB의 추가 데이터 전송',
    'invoiceTip': '편의 수수료',
    "listTitle": "웹사이트 목록",
    "newOrder": "웹사이트 추가",
    "tabDetail": "정보",
    "tabSetup": "설정",
    "tabManage": "관리",
    "tabRunner": "배포",
    "tabWebhook": "웹훅",
    "tabCheck": "체크",
    "tabConnection": "연결 체크",
    "tabFirewall": "방화벽 체크",
    "tabNginx": "NGINX 체크",
    "tabDns": "DNS 체크",
    "tabLog": "로그 체크",
    "tabAdmin": "관리",
    "tabRename": "사용자 이름 변경",
    "tabCname": "도메인 변경",
    "tabPasswd": "비밀번호 변경",
    "tabRegion": "지역 변경",
    "tabTransfer": "웹사이트 이전",
    "tabDelete": "웹사이트 삭제",
    "startFromTemplate": "템플릿에서 시작",
    "uploadOrClone": "인터넷에서 업로드 또는 클론",
    "seeMoreTemplates": "더 많은 웹 템플릿 보기",
    "customTemplate": "커스텀 템플릿",
    "customDomain": "커스텀 도메인",
    "mergeToParentDomain": "상위 도메인으로 병합",
    "fetchingDomains": "...도메인 가져오는 중",
    "moreTemplates": "더 많은 템플릿",
    "portalUsername": "사용자 이름",
    "portalUsernameHint": "알파벳, 숫자 및 하이픈만 사용",
    "portalPassword": "비밀번호",
    "slaveServer": "지역",
    "scheme": "플랜",
    "usage": "사용량",
    "month": "개월",
    "year": "년",
    "free": "무료",
    "database": "데이터베이스",
    "additionalServices": "추가 서비스",
    "softwareCompilers": "소프트웨어 컴파일러",
    "enableNewFeatures": "새 기능 활성화",
    "addHost": "웹사이트 추가",
    "emptyList": "목록에 웹사이트 없음",
    "waitForDataHint": "자원 사용량이 여기에 표시됩니다. 데이터가 나타나기 위해 다음 날 다시 오십시오.",
    "slaveID": "슬레이브 ID",
    "IPAddress": "IP 주소",
    "openWebsite": "웹사이트 열기",
    "openPortal": "포털 열기",
    "hostStatus": "호스트 상태",
    "creationDate": "생성 날짜",
    "usernameHost": "호스트 사용자 이름",
    "domainHost": "호스트 도메인",
    "manageHostLogin": "호스트 로그인 관리",
    "total": "총계",
    "used": "사용된",
    "remainingMonthlyPlan": "남은 월간 플랜",
    "remainingAddons": "남은 추가 기능",
    "planDetail": "{0} 플랜, {1} 디스크 공간, {2} 월간 대역폭.",
    "emptyForDefaultCname": "기본값을 위해 비워 두기 ({0})",
    "redeploy": "재배포",
    "debugManually": "수동으로 디버그",
    "startOver": "다시 시작",
    "deployScript": "배포 스크립트",
    "deployAdd": "배포 작업 추가",
    "deployNow": "실행!",
    "deployClearHint": "모든 로그를 지우시겠습니까?",
    "websiteReadyHint": "사이트가 준비되었습니다. 지금 방문하시겠습니까?",
    "deployByAdmin": "시스템 관리자에 의해 실행됨",
    "deployOverwriteBanner": "이 스크립트는 이 웹사이트의 모든 파일을 대체합니다!",
    "deployOverwriteWarn": "소스 매개 변수를 언급했으므로 HOME 파일이 영구적으로 덮어쓰여질 것입니다. 이 작업은 되돌릴 수 없습니다. 확실합니까?",
    "deployHelpBtn": "배포 구성 참조",
    "githubWebhook": "웹훅 설정",
    "githubWebhookTitle": "GitHub 액션 설정",
    "githubWebhookHelp": "이 웹훅을 사용하여 GitHub에 푸시할 때 웹사이트를 자동으로 배포할 수 있습니다.",
    "githubWebhookHelpBtn": "GitHub 액션 웹훅 도움말",
    "noWebhook": "이 호스트에 구성된 웹훅이 없습니다.",
    "noGitHubApi": "GitHub API를 사용할 수 없습니다",
    "noGitHubApiToken": "GitHub API 토큰을 찾을 수 없습니다",
    "noGitHubApiHint": "전체 리포지토리 접근 권한으로 먼저 GitHub 계정을 연결해야 합니다.",
    "noGitHubApiLink": "지금 GitHub 연결",
    "noRepo": "저장소를 찾을 수 없음",
    "noRepoHint": "검색 범위를 좁혀보세요",
}
