<?php return [
	'code' => 'ko',
	'codename' => '한국어',
	'codedir' => 'ltr',
	'login' => '로그인',
	'register' => '가입하기',
	'email' => '이메일',
	'enterToPortal' => '포털에 들어가기',
	'registerToPortal' => '포털에 가입하기',
	'registerWithEmail' => '이메일로 가입하기',
	'forgotPrompt' => '비밀번호를 잊으셨나요?',
	'recoverYourPassword' => '비밀번호 복구',
	'recoverYourPasswordHint' => '새 비밀번호를 입력하여 변경하세요',
	"report" => "신고",
	"reportPrompt" => "{0} 네트워크 내에서 의심스러운 활동을 신고하세요. 신고된 웹사이트가 당사의 기준을 충족하면 콘텐츠가 즉시 제거됩니다.",
	"reportAbuse" => "부적절한 콘텐츠 신고",
	"reportDomain" => "신고할 도메인",

	'ok' => '확인',
	'back' => '뒤로',
	'or' => '또는',
	'signInWith' => '로그인 방법 {0}',
	'wrongLogin' => '잘못된 이메일 또는 비밀번호입니다',
	'registerAgreement' => '가입함으로써 귀하는 당사의 <a href="{0}" target="_blank">이용약관</a>에 동의하게 됩니다.',
	'emailSent' => '확인 이메일이 발송되었습니다. 로그인 전에 받은 편지함(및 스팸 편지함)을 확인해 주세요.',
	'oAuthFail' => '제3자 로그인 시도가 실패한 것 같습니다. 이는 일반적으로 타임아웃 또는 해당 계정에 연결된 주 이메일이 아직 확인되지 않았기 때문입니다.',
	'passReset' => '비밀번호가 성공적으로 재설정되었습니다. 새로운 비밀번호로 로그인해 주세요.',
	'thanksForVerify' => '감사합니다, 이메일이 확인되었습니다',

	'password' => '비밀번호',
	'passwordAgain' => '비밀번호 (다시 입력)',
	'fullName' => '전체 이름',
	'activeEmail' => '활성 이메일',

];
