<?php return [
	'emailAlreadyExist' => 'Este e-mail já existe',
	'passwordNotLongEnough' => 'Esta senha não é longa o suficiente',
	'passwordNotMatch' => 'A senha existente não corresponde',
	'invalidCountry' => 'Código de país inválido',

	'accountAlreadyAttached' => 'Desculpe, esta conta social já está vinculada a outra conta.',
	'accountCreationExpired' => 'Desculpe, parece que estamos tentando confirmar a criação da sua conta, mas sua sessão expirou. Tente fazer login novamente.',
	'accountPasswordlessRecovery' => 'Infelizmente, você não pode recuperar uma conta sem senha. Tente usar um usuário de terceiros (Google ou GitHub).',
	'accountDeleteLastMethod' => 'Você não pode excluir seu único método de login',
	'accountRecountTooFast' => 'Por favor, aguarde um momento antes de tentar novamente',
	'accountDeleteNotDangling' => 'Exclua todos os hosts, domínios e backups primeiro',

	'inviteUserNotFound' => 'Este usuário não foi encontrado',
	'inviteQuotaFull' => 'O número máximo de membros da equipe foi atingido. Atualize seu plano.',
	'inviteNewFail' => 'Falha ao convidar, talvez já tenham sido adicionados?',
	'inviteRemoveFail' => 'Falha ao remover o membro, talvez já tenha sido removido?',

	'inviteCodeInvalid' => 'Código de convite inválido',
	'inviteCodeExpired' => 'Código de convite expirado',

	'unknownAction' => 'Ação desconhecida',
	'hostIsNotActive' => 'Não é possível aplicar a tarefa enquanto este host não estiver ativo',
	'needVerifyEmail' => 'Por favor, verifique seu e-mail primeiro',
	'hostQuotaLimit' => 'Desculpe, você precisa atualizar seu plano para criar mais hosts. Se já atualizou, verifique seu saldo ou entre em contato com o suporte.',
	'usingInternalDomain' => 'Desculpe, você não pode usar nosso domínio aqui',
	'usingSubscibingDomain' => 'Desculpe, você precisa atualizar seu plano para usar este domínio',
	'invalidUsername' => 'Nome de usuário inválido',
	'invalidDomainname' => 'Nome de domínio inválido',
	'unchangedUsername' => 'Nome de usuário não alterado',
	'unchangedDomainname' => 'Nome de domínio não alterado',
	'domainAlreadyExist' => 'O nome de domínio já existe',
	'usernameAlreadyExist' => 'O nome de usuário já existe',
	'usernameTooShort' => 'O nome de usuário é muito curto',
	'parentNotFound' => 'Domínio pai não encontrado',
	'invalidDeployYaml' => 'Seu script de implantação não é um YAML válido: {0}',
	'deploymentFailedToReach' => 'Falha ao contactar o servidor {0} para esta implantação: {1}',
	'hostRunnerProgressing' => 'Rápido demais! Não é possível aplicar enquanto as implantações estão em andamento! Aguarde um momento.',
	'backupNeedSubscribe' => 'Desculpe, você precisa atualizar seu plano para criar backups',
	'backupIsNotActive' => 'O status do backup não está ativo, talvez já tenha sido excluído',
];
