export default {
    'invoiceDomainPurchaseOf': 'Compra de domínio de {0}',
    'invoiceDomainExtendOf': 'Extensão de domínio de {0}',
    'invoiceDomainTransferOf': 'Transferência de domínio de {0}',
    'invoiceTeamPurchaseOf': 'Compra da equipe do plano {0}',
    'invoiceTeamAddons': 'Complementos da equipe',
    'invoiceForMonths': ' por {0, plural, =1{# mês} other{# meses}}',
    'invoiceForYears': ' por {0, plural, =1{# ano} other{# anos}}',
    'invoiceForYearsAndMonths': ' por {0, plural, =1{# ano} other{# anos}} e {1, plural, =1{# mês} other{# meses}}',
    'invoiceDataTransferAddonsFor': 'Transferência de dados adicional por {0} GB',
    'invoiceTip': 'Taxa de conveniência',
    "listTitle": "Lista de sites",
    "newOrder": "Adicionar um site",
    "tabDetail": "Informações",
    "tabSetup": "Configuração",
    "tabManage": "Gerenciar",
    "tabRunner": "Implementar",
    "tabWebhook": "Webhook",
    "tabCheck": "Verificar",
    "tabConnection": "Verificar conexão",
    "tabFirewall": "Verificar firewall",
    "tabNginx": "Verificar NGINX",
    "tabDns": "Verificar DNS",
    "tabLog": "Verificar logs",
    "tabAdmin": "Admin",
    "tabRename": "Renomear usuário",
    "tabCname": "Alterar domínio",
    "tabPasswd": "Alterar senha",
    "tabTransfer": "Transferir site",
    "tabDelete": "Excluir site",
    "startFromTemplate": "Começar a partir de um modelo",
    "uploadOrClone": "Carregar ou clonar da Internet",
    "seeMoreTemplates": "Ver mais modelos de sites",
    "customTemplate": "Modelo personalizado",
    "customDomain": "Domínio personalizado",
    "mergeToParentDomain": "Mesclar com domínio principal",
    "fetchingDomains": "...Buscando domínios",
    "moreTemplates": "Mais modelos",
    "portalUsername": "Nome de usuário",
    "portalUsernameHint": "Apenas alfanuméricos e hífens",
    "portalPassword": "Senha",
    "slaveServer": "Região",
    "scheme": "Plano",
    "usage": "Uso",
    "month": "Mês",
    "year": "Ano",
    "free": "Gratuito",
    "database": "Banco de dados",
    "additionalServices": "Serviços adicionais",
    "softwareCompilers": "Compiladores de software",
    "enableNewFeatures": "Ativar novos recursos",
    "addHost": "Adicionar um site",
    "emptyList": "Nenhum site listado",
    "waitForDataHint": "O uso de recursos aparecerá aqui. Volte no dia seguinte para visualizar os dados.",
    "slaveID": "ID do Slave",
    "IPAddress": "Endereço IP",
    "openWebsite": "Abrir site",
    "openPortal": "Abrir portal",
    "hostStatus": "Status do host",
    "creationDate": "Data de criação",
    "usernameHost": "Nome de usuário do host",
    "domainHost": "Domínio do host",
    "manageHostLogin": "Gerenciar login do host",
    "total": "Total",
    "used": "Usado",
    "remainingMonthlyPlan": "Plano mensal restante",
    "remainingAddons": "Addons restantes",
    "planDetail": "Plano {0}, {1} de espaço em disco, {2} de largura de banda mensal.",
    "emptyForDefaultCname": "Deixe em branco para o padrão ({0})",
    "redeploy": "Reimplantar",
    "deployAdd": "Adicionar uma tarefa de implantação",
    "deployNow": "Executar!",
    "deployClearHint": "Apagar todos os logs?",
    "websiteReadyHint": "Seu site está pronto. Gostaria de visitá-lo agora?",
    "deployByAdmin": "Executado pelo moderador do sistema",
    "deployOverwriteBanner": "Este script substituirá todos os arquivos deste site!",
    "deployOverwriteWarn": "Você mencionou o parâmetro de origem, o que significa que seu arquivo HOME será PERMANENTEMENTE SOBRESCRITO. Esta ação não pode ser desfeita. Tem certeza?",
    "deployHelpBtn": "Referência de configuração de implantação",
    "githubWebhook": "Configurar webhook",
    "githubWebhookTitle": "Configurar ação do GitHub",
    "githubWebhookHelp": "Você pode usar este webhook para implantar automaticamente seu site quando fizer push no GitHub.",
    "githubWebhookHelpBtn": "Ajuda do webhook de ação do GitHub",
    "noWebhook": "Não há webhooks configurados para este host.",
    "noGitHubApi": "API do GitHub não disponível",
    "noGitHubApiToken": "Token da API do GitHub não encontrado",
    "noGitHubApiHint": "Você deve primeiro vincular uma conta do GitHub com acesso total ao repositório.",
    "noGitHubApiLink": "Vincular GitHub agora",
    "noRepo": "Nenhum repositório encontrado",
    "noRepoHint": "Tente restringir sua pesquisa",
}
