export default {
    "logout": "Sair",
    "profile": "Perfil",
    "status": "Status",
    "verifyStatus": "Status de Verificação",
    "bannedHint": "Sua conta foi banida, desculpe.",
    "hosting": "Website",
    "domain": "Domínio",
    "backup": "Backup",
    "owner": "Proprietário",
    "admin": "Admin",
    "member": "Membro",
    "team": "Equipe",
    "email": "E-mail",
    "storage": "Armazenamento",
    "bandwidth": "Largura de Banda",
    "instances": "Instâncias",
    "users": "Usuários",
    "details": "Detalhes",
    "members": "Membros",
    "upgrade": "Atualizar",
    "otherTeams": "Outras Equipes",
    "inviteCode": "Código de Convite",
    "hostname": "Nome do Host",
    "port": "Porta",
    "username": "Nome de Usuário",
    "password": "Senha",
    "server": "Servidor",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "redis": "Redis",
    "mysql2": "MySQL (MariaDB)",
    "redis2": "Redis (Valkey)",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "phprdadmin": "phpRdAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    "help": "Ajuda",
    "helpDocs": "Documentação",
    "helpEmail": "E-mail",
    "helpForum": "Fórum",
    "helpChat": "Chat",
    "helpUpdates": "Atualizações",
    "country": "País",
    "chooseCountry": "Escolha um país",
    "expiration": "Expiração",
    "resendConfirmationEmail": "Reenviar E-mail de Confirmação",
    "learnMore": "Saiba Mais",
    "passwordNotice": "Você não precisa lembrar dessa senha",
    "lastUpdatedAt": "Última Atualização em",
    "language": "Idioma",
    "theme": "Tema",
    "themeDark": "Sempre Escuro",
    "themeLight": "Sempre Claro",
    "themeSystem": "Padrão do Sistema",
    "role": "Função",
    "action": "Ação",
    "currencyInput": "Moeda",
    "invoiceNoteInput": "Contato para Fatura",
    "defaultServerInput": "Servidor Padrão",
    "defaultServerInputNone": "Nenhum (perguntar para mim)",
    "name": "Nome",
    "phone": "Número de Telefone",
    "phoneHint": "Número de telefone completo (começa com +)",
    "phoneAlt": "Número de Telefone Alternativo",
    "fullName": "Nome Completo",
    "companyName": "Nome da Empresa",
    "activeEmail": "E-mail Ativo",
    "newPassword": "Nova Senha",
    "editProfile": "Editar Perfil",
    "saveProfile": "Salvar Perfil",
    "deleteAccount": "Excluir Conta",
    "loginMethods": "Métodos de Login",
    "loginRemoveConfirm": "Tem certeza de que deseja remover este método de login?",
    "loginAdd": "Adicionar ou substituir um método de login",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "E-mail + Senha",
    "loginVia": "via {0}",
    "passwordConfirm": "Digite a senha atual da conta (se presente)",
    "passwordSetInput": "Digite a nova senha, deve ter pelo menos 8 caracteres",
    "passwordSetCancel": "A definição da senha para esta conta foi cancelada",
    "passwordSetCancelLength": "Definição de senha cancelada, deve ter pelo menos 8 caracteres",
    "yearDuration": "Duração em anos",
    "monthDuration": "Duração em meses",
    "annualSaving": "Economize 16%",
    "totalPayment": "Pagamento Total",
    "expirationDate": "Data de Expiração",
    "orderNow": "Encomendar Agora",
    "invoice": "Fatura",
    "pendingInvoices": "Faturas Pendentes",
    "noPendingInvoices": "Você não tem faturas pendentes no momento.",
    "mixedCurrency": "As faturas selecionadas têm moedas mistas",
    "currentPlan": "Plano Atual",
    "currentPlanDescription": "Com custo de <b>{0}</b> por mês com expiração em <b>{1}</b>",
    "priceDescription": "{0} / mês",
    "monthlyLimits": "Limites Mensais",
    "storageLimit": "{0} GB de Armazenamento",
    "networkLimit": "{0} GB de Rede",
    "instanceLimit": "{0} {0, plural, one {Instância} other {Instâncias}}",
    "userLimit": "{0} {0, plural, one {Usuário} other {Usuários}}",
    "autoStop": "Parar automaticamente nos limites",
    "noFreeDomain": "Nenhum domínio {0} gratuito",
    "withFreeDomain": "Domínio gratuito {0}",
    "withBackup": "Backup automático no nível do servidor",
    "withDocker": "Docker e aplicativos de longa duração",
    "storageUsage": "Uso de Armazenamento",
    "storageUsageCap": "de {0} total",
    "bandwidthUsed": "Largura de Banda Usada",
    "bandwidthUsedCap": "de {0} mensal",
    "instancesActive": "Instâncias Ativas",
    "instancesActiveCap": "de {0} websites",
    "teamUsers": "Usuários da Equipe",
    "teamUsersCap": "de um máximo de {0} usuários",
    "remainingAvailable": "Disponível Restante",
    "remainingStorage": "Armazenamento Livre",
    "remainingNetwork": "Dados de Rede Restantes",
    "remainingInstance": "Instância Restante",
    "dataTransfer": "Transferência de Dados",
    "copy": "Copiar",
    "copied": "Copiado!",
    "reloading": "Recarregando {0}",
    "expires": "Expira {0}",
    "expiresAt": "Expira em {0}",
    "expireFreeHint": `
  As datas de expiração são renovadas automaticamente (estendidas por 3 meses) 
  toda vez que você faz login ou seus sites têm tráfego de rede suficiente (> 50 MB) 
  no final do mês.` ,
    "discountedAt": "Com desconto de {0}",
    "extendingCurrentExpiryDate": "Estendendo a data de expiração atual",
    "usersLimitHint": "{0} {0, plural, one {usuário} other {usuários}} nesta equipe, {1} {1, plural, one {usuário} other {usuários}} podem ser adicionados",
    "emailToInvite": "E-mail para convidar",
    "selectRole": "Selecione a função",
    "info": "Informação",
    "total": "Total",
    "back": "Voltar",
    "add": "Adicionar",
    "addMember": "Adicionar Membro",
    "confirmRemoveMember": "Tem certeza de que deseja remover este membro?",
    "edit": "Editar",
    "apply": "Aplicar",
    "save": "Salvar",
    "clear": "Limpar",
    "update": "Atualizar",
    "updateUsage": "Atualizar Uso",
    "change": "Mudar",
    "archives": "Arquivos",
    "renew": "Renovar",
    "extend": "Estender",
    "topup": "Recarregar",
    "processing": "Processando",
    "cancel": "Cancelar",
    "print": "Imprimir",
    "delete": "Excluir",
    "why": "Porquê?",
    "pay": "Pagar",
    "payAccept": "Aceitamos pagamentos por meio de",
    "loading": "Reunindo dados...",
    "fetchError": "Erro ao buscar dados! Tente novamente mais tarde",
    "notFound": "Não Encontrado",
    "notFoundDescription": "A página que você está procurando não existe.",
    "notFoundLink": "Voltar para a página inicial"
}