<?php return [
    'code' => 'pt',
    'codename' => 'Português',
    'login' => 'Entrar',
    'register' => 'Registrar',
    'email' => 'E-mail',
    'enterToPortal' => 'Entrar no Portal',
    'registerToPortal' => 'Registrar no Portal',
    'registerWithEmail' => 'Registrar com E-mail',
    'forgotPrompt' => 'Esqueceu a senha?',
    'recoverYourPassword' => 'Recupere sua senha',
    'recoverYourPasswordHint' => 'Insira uma nova senha para alterar',
    'report' => 'Relatar',
    'reportPrompt' => 'Denuncie atividades suspeitas na rede DOM Cloud. O conteúdo será removido imediatamente se o site denunciado atender aos nossos critérios.',
    'reportAbuse' => 'Denunciar conteúdo abusivo',
    'reportDomain' => 'Domínio a ser denunciado',
    'ok' => 'OK',
    'back' => 'Voltar',
    'or' => 'Ou',
    'signInWith' => 'Entrar com {0}',
    'wrongLogin' => 'E-mail ou senha incorretos',
    'registerAgreement' => 'Ao se registrar, você concorda com nossos <a href="//domcloud.co/service" target="_blank">Termos de Serviço</a>.',
    'emailSent' => 'O e-mail de verificação foi enviado, verifique sua caixa de entrada (e a caixa de spam) antes de fazer login.',
    'oAuthFail' => 'Parece que sua tentativa de login com terceiros falhou. Isso é comumente causado por tempo limite ou e-mail principal vinculado a essa conta ainda não verificado.',
    'passReset' => 'Sua senha foi redefinida com sucesso. Faça login com sua nova senha.',
    'thanksForVerify' => 'Obrigado, seu e-mail foi verificado',
    'password' => 'Senha',
    'passwordAgain' => 'Senha (novamente)',
    'fullName' => 'Nome completo',
    'activeEmail' => 'E-mail ativo',
];
