export default {
    "check": "Vérifier",
    "detail": "Détail",
    "dns": "DNS",
    "renew": "Renouveler",
    "renewDomain": "Renouveler le domaine",
    "listTitle": "Liste des domaines",
    "newOrder": "Acheter un domaine",
    "transferDomain": "Transférer un domaine",
    "registerTitle": "Inscription au compte de domaine",
    "administrationData": "Données administratives",
    "addressData": "Données d'adresse",
    "address": "Adresse",
    "address1": "Adresse (ligne 1)",
    "address2": "Adresse (ligne 2)",
    "address3": "Adresse (ligne 3)",
    "city": "Ville",
    "state": "État",
    "country": "Pays",
    "zipCode": "Code postal",
    "company": "Entreprise",
    "companyName": "Nom de l'entreprise / organisation",
    "domainName": "Nom de domaine",
    "domainStatus": "Statut du domaine",
    "enterContact": "Entrer le contact de domaine",
    "contactEntered": "Contact de domaine entré",
    "myOwn": "Le domaine que j'ai commandé m'appartient",
    "enterBio": "Entrer le contact",
    "publicBio": "Contact public / Propriétaire du domaine",
    "personalBio": "Contact personnel / Responsable du domaine",
    "domainPrice": "Prix du domaine",
    "emptyList": "Aucun domaine répertorié",
    "registrationDate": "Date d'inscription",
    "expirationDate": "Date d'expiration",
    "transferLock": "Verrouillage du transfert",
    "privacyLock": "Verrouillage de la confidentialité",
    "nameServers": "Serveurs de noms",
    "checkHint": "Cliquez sur le bouton de vérification",
    "checkFail": "Échec de la vérification de la disponibilité du domaine",
    "findDomain": "Trouver un domaine",
    "findWait": "Vérification en cours...",
    "findUnavailable": "Le domaine est actuellement indisponible.",
    "findNeedData": "Nous ne pouvons pas traiter les achats de domaines tant que vous n'avez pas rempli les données nécessaires.",
    "findNeedDataAction": "Remplir maintenant",
    "verifyHint": "Vous devez vérifier votre email dans les 15 jours suivant l'achat ou notre registraire suspendra votre domaine!",
    "verifyBtn": "Renvoyer l'email de vérification à {0}",
    "transferCode": "Code EPP / de transfert",
    "showTransferCode": "Afficher le code EPP",
}
