<?php return [
	'emailAlreadyExist' => 'Cet email existe déjà',
	'passwordNotLongEnough' => 'Ce mot de passe n\'est pas assez long',
	'passwordNotMatch' => 'Le mot de passe actuel ne correspond pas',
	'invalidCountry' => 'Code pays invalide',

	'accountAlreadyAttached' => 'Désolé, ce compte social est déjà attaché à un autre compte.',
	'accountCreationExpired' => 'Désolé, il semble que nous essayions de confirmer la création de votre compte, mais votre session a expiré. Réessayez de vous connecter.',
	'accountPasswordlessRecovery' => 'Malheureusement, vous ne pouvez pas récupérer un compte sans mot de passe. Veuillez utiliser un compte tiers (Google ou GitHub) à la place.',
	'accountDeleteLastMethod' => 'Vous ne pouvez pas supprimer votre seule méthode de connexion',
	'accountRecountTooFast' => 'Veuillez patienter un instant avant de recommencer',
	'accountDeleteNotDangling' => 'Veuillez supprimer d\'abord tous les hôtes, domaines et sauvegardes',

	'inviteUserNotFound' => 'Cet utilisateur est introuvable',
	'inviteQuotaFull' => 'Le nombre maximal de membres d\'équipe a été atteint, veuillez mettre à niveau',
	'inviteNewFail' => 'Échec de l\'invitation, peut-être ont-ils déjà été ajoutés ?',
	'inviteRemoveFail' => 'Échec de la suppression du membre, peut-être a-t-il déjà été supprimé ?',

	'inviteCodeInvalid' => 'Code d\'invitation invalide',
	'inviteCodeExpired' => 'Code d\'invitation expiré',

	'unknownAction' => 'Action inconnue',
	'hostIsNotActive' => 'Impossible d\'appliquer la tâche tant que cet hôte n\'est pas actif',
	'needVerifyEmail' => 'Veuillez d\'abord vérifier votre email',
	'hostQuotaLimit' => 'Désolé, vous devez mettre à jour votre abonnement pour créer plus d\'hôtes. Si vous l\'avez déjà fait, vérifiez votre solde ou contactez le support.',
	'usingInternalDomain' => 'Désolé, vous ne pouvez pas utiliser notre domaine ici',
	'usingSubscibingDomain' => 'Désolé, vous devez mettre à jour votre abonnement pour utiliser ce domaine',
	'invalidUsername' => 'Nom d\'utilisateur invalide',
	'invalidDomainname' => 'Nom de domaine invalide',
	'unchangedUsername' => 'Nom d\'utilisateur inchangé',
	'unchangedDomainname' => 'Nom de domaine inchangé',
	'domainAlreadyExist' => 'Le nom de domaine existe déjà',
	'tooShortUsername' => 'Nom d\'utilisateur trop court',
	'parentNotFound' => 'Domaine parent introuvable',
	'invalidDeployYaml' => 'Votre script de déploiement n\'est pas un YAML valide : {0}',
	'deploymentFailedToReach' => 'Échec de la connexion au serveur {0} pour ce déploiement : {1}',
	'hostRunnerProgressing' => 'Trop rapide ! Impossible d\'appliquer pendant que des déploiements sont en cours ! Veuillez patienter un instant.',
	'backupNeedSubscribe' => 'Désolé, vous devez mettre à jour votre abonnement pour créer des sauvegardes.',
	'backupIsNotActive' => 'L\'état de la sauvegarde est inactif, peut-être a-t-elle déjà été supprimée.',
];
