export default {
    'invoiceDomainPurchaseOf': 'Achat de domaine de {0}',
    'invoiceDomainExtendOf': 'Extension de domaine de {0}',
    'invoiceDomainTransferOf': 'Transfert de domaine de {0}',
    'invoiceTeamPurchaseOf': 'Achat d\'équipe de {0} plan',
    'invoiceTeamAddons': 'Add-ons d\'équipe',
    'invoiceForMonths': ' pour {0, plural, =1{# mois} other{# mois}}',
    'invoiceForYears': ' pour {0, plural, =1{# an} other{# ans}}',
    'invoiceForYearsAndMonths': ' pour {0, plural, =1{# an} other{# ans}} et {1, plural, =1{# mois} other{# mois}}',
    'invoiceDataTransferAddonsFor': 'Transfert de données supplémentaires pour {0} GB',
    'invoiceTip': 'Frais de commodité',
    "listTitle": "Liste des sites web",
    "newOrder": "Ajouter un site web",
    "tabDetail": "Infos",
    "tabSetup": "Configuration",
    "tabManage": "Gérer",
    "tabRunner": "Déployer",
    "tabWebhook": "Webhook",
    "tabCheck": "Vérifier",
    "tabConnection": "Vérifier la connexion",
    "tabFirewall": "Vérifier le pare-feu",
    "tabNginx": "Vérifier NGINX",
    "tabDns": "Vérifier DNS",
    "tabLog": "Vérifier les journaux",
    "tabAdmin": "Admin",
    "tabRename": "Changer le nom d'utilisateur",
    "tabCname": "Changer le domaine",
    "tabPasswd": "Changer le mot de passe",
    "tabTransfer": "Transférer le site web",
    "tabDelete": "Supprimer le site web",
    "startFromTemplate": "Commencer par un modèle",
    "uploadOrClone": "Télécharger ou cloner depuis Internet",
    "seeMoreTemplates": "Voir plus de modèles de sites web",
    "customTemplate": "Modèle personnalisé",
    "customDomain": "Domaine personnalisé",
    "mergeToParentDomain": "Fusionner avec le domaine parent",
    "fetchingDomains": "...Récupération des domaines",
    "moreTemplates": "Plus de modèles",
    "portalUsername": "Nom d'utilisateur",
    "portalUsernameHint": "Alphanumérique et tiret uniquement",
    "portalPassword": "Mot de passe",
    "slaveServer": "Région",
    "scheme": "Plan",
    "usage": "Utilisation",
    "month": "Mois",
    "year": "An(s)",
    "free": "Gratuit",
    "database": "Base de données",
    "additionalServices": "Services supplémentaires",
    "softwareCompilers": "Compilateurs de logiciels",
    "enableNewFeatures": "Activer de nouvelles fonctionnalités",
    "addHost": "Ajouter un site web",
    "emptyList": "Aucun site web répertorié",
    "waitForDataHint": "L'utilisation des ressources apparaîtra ici. Revenez le lendemain pour voir les données.",
    "slaveID": "ID Esclave",
    "IPAddress": "Adresse IP",
    "openWebsite": "Ouvrir le site web",
    "openPortal": "Ouvrir le portail",
    "hostStatus": "Statut de l'hôte",
    "creationDate": "Date de création",
    "usernameHost": "Nom d'utilisateur de l'hôte",
    "domainHost": "Domaine de l'hôte",
    "manageHostLogin": "Gérer la connexion de l'hôte",
    "total": "Total",
    "used": "Utilisé",
    "remainingMonthlyPlan": "Plan mensuel restant",
    "remainingAddons": "Add-ons restants",
    "planDetail": "{0} Plan, {1} espace disque, {2} bande passante mensuelle.",
    "emptyForDefaultCname": "Laisser vide pour par défaut ({0})",
    "redeploy": "Redéployer",
    "deployAdd": "Ajouter une tâche de déploiement",
    "deployNow": "Exécuter!",
    "deployClearHint": "Effacer tous les journaux?",
    "websiteReadyHint": "Votre site est prêt. Essayer de visiter maintenant?",
    "deployByAdmin": "Exécuté par le modérateur du système",
    "deployOverwriteBanner": "Ce script remplacera tous les fichiers de ce site web!",
    "deployOverwriteWarn": "Vous avez mentionné le paramètre source, ce qui signifie que votre fichier HOME sera DÉFINITIVEMENT ÉCRASÉ. Cette action ne peut pas être annulée. Êtes-vous sûr?",
    "deployHelpBtn": "Référence de configuration du déploiement",
    "githubWebhook": "Configurer le webhook",
    "githubWebhookTitle": "Configurer l'action GitHub",
    "githubWebhookHelp": "Vous pouvez utiliser ce webhook pour déployer automatiquement votre site web lorsque vous poussez sur GitHub.",
    "githubWebhookHelpBtn": "Aide sur le webhook GitHub Action",
    "noWebhook": "Aucun webhook configuré pour cet hôte.",
    "noGitHubApi": "API GitHub non disponible",
    "noGitHubApiToken": "Token API GitHub non trouvé",
    "noGitHubApiHint": "Vous devez d'abord lier un compte GitHub avec un accès complet au repo.",
    "noGitHubApiLink": "Lier GitHub maintenant",
    "noRepo": "Aucun dépôt trouvé",
    "noRepoHint": "Essayez de restreindre votre recherche",
}
