<?php return [
	'code' => 'fr',
	'codename' => 'Français',
	'codedir' => 'ltr',
	'login' => 'Se connecter',
	'register' => 'S’inscrire',
	'email' => 'E-mail',
	'enterToPortal' => 'Entrer dans le portail',
	'registerToPortal' => 'S’inscrire au portail',
	'registerWithEmail' => 'S’inscrire avec un e-mail',
	'forgotPrompt' => 'Mot de passe oublié?',
	'recoverYourPassword' => 'Récupérer votre mot de passe',
	'recoverYourPasswordHint' => 'Entrez un nouveau mot de passe pour le changer',
	'report' => 'Signaler',
	'reportPrompt' => 'Signalez une activité suspecte dans le réseau DOM Cloud. Le contenu sera immédiatement supprimé si le site signalé remplit nos critères.',
	'reportAbuse' => 'Signaler un abus',
	'reportDomain' => 'Domaine à signaler',
	'ok' => 'OK',
	'back' => 'Retour',
	'or' => 'Ou',
	'signInWith' => 'Se connecter avec {0}',
	'wrongLogin' => 'E-mail ou mot de passe incorrect',
	'registerAgreement' => 'En vous inscrivant, vous acceptez nos <a href="//domcloud.co/service" target="_blank">Conditions de service</a>.',
	'emailSent' => 'L’e-mail de vérification a été envoyé, veuillez vérifier votre boîte de réception (et la boîte de spam) avant de vous connecter.',
	'oAuthFail' => 'Il semble que votre tentative de connexion via un tiers ait échoué. Cela est généralement dû à un délai d’attente ou à une adresse e-mail principale non vérifiée.',
	'passReset' => 'Votre mot de passe a été réinitialisé avec succès. Veuillez vous connecter avec votre nouveau mot de passe.',
	'thanksForVerify' => 'Merci, votre e-mail a été vérifié',
	'password' => 'Mot de passe',
	'passwordAgain' => 'Mot de passe (encore)',
	'fullName' => 'Nom complet',
	'activeEmail' => 'E-mail actif',
];
