export default {
    "check": "Check",
    "detail": "Detail",
    "dns": "DNS",
    "renew": "Renew",
    "renewDomain": "Renew Domain",
    "listTitle": "Domain List",
    "newOrder": "Buy a domain",
    "transferDomain": "Transfer a domain",
    "registerTitle": "Domain Account Registration",
    "administrationData": "Administration Data",
    "addressData": "Address Data",
    "address": "Address",
    "address1": "Address (Line 1)",
    "address2": "Address (Line 2)",
    "address3": "Address (Line 3)",
    "city": "City",
    "state": "State",
    "country": "Country",
    "zipCode": "Zip Code",
    "company": "Company",
    "companyName": "Company / Organization Name",
    "domainName": "Domain name",
    "domainStatus": "Domain status",
    "formatInvoice": "Domain payment {0} priced at {1}",
    "enterContact": "Fill Domain Contact",
    "myOwn": "The domain I ordered is my own",
    "enterBio": "Enter Contact",
    "publicBio": "Public Contact / Domain Owner",
    "personalBio": "Personal Contact / Responsible Domain",
    "domainPrice": "Domain Price",
    "emptyList": "No domain listed",
    "registrationDate": "Registration Date",
    "expirationDate": "Expiration Date",
    "transferLock": "Transfer Lock",
    "privacyLock": "Privacy Lock",
    "nameServers": "Name servers",
    "findDomain": "Find Domain",
    "findWait": "Checking ...",
    "findUnavailable": "Domain is currently unavailable.",
    "findNeedData": "We cannot process domain purchases until you fill in the data we need.",
    "findNeedDataAction": "Fill now",
    "transferCode": "EPP / Transfer Code",
    "showTransferCode": "Show EPP Code",
}
