<?php return [
	'emailAlreadyExist' => 'このメールアドレスはすでに存在しています',
	'passwordNotLongEnough' => 'このパスワードは十分な長さではありません',
	'passwordNotMatch' => '既存のパスワードが一致しません',
	'invalidCountry' => '無効な国コード',

	'accountAlreadyAttached' => '申し訳ありませんが、このソーシャルアカウントはすでに他のアカウントに紐付けられています。',
	'accountCreationExpired' => '申し訳ありませんが、アカウント作成を確認しようとしていますが、セッションが終了しました。再度ログインしてください。',
	'accountPasswordlessRecovery' => 'パスワードなしのアカウントを復元することはできません。GoogleやGitHubなどのサードパーティアカウントを使用してください。',
	'accountDeleteLastMethod' => '唯一のログイン方法を削除することはできません',
	'accountRecountTooFast' => '再計算する前に少しお待ちください',
	'accountDeleteNotDangling' => 'ホスト、ドメイン、バックアップをすべて削除してください',

	'inviteUserNotFound' => 'このユーザーは見つかりません',
	'inviteQuotaFull' => 'チームメンバーの最大数に達しました。アップグレードしてください',
	'inviteNewFail' => '招待に失敗しました。既に追加されている可能性があります。',
	'inviteRemoveFail' => 'メンバーの削除に失敗しました。既に削除されている可能性があります。',

	'inviteCodeInvalid' => '招待コードが無効です',
	'inviteCodeExpired' => '招待コードの有効期限が切れました',

	'unknownAction' => '不明なアクション',
	'hostIsNotActive' => 'このホストがアクティブでない間はタスクを適用できません',
	'needVerifyEmail' => '最初にメールアドレスを確認してください',
	'hostQuotaLimit' => '申し訳ありませんが、より多くのホストを作成するにはプランをアップグレードする必要があります。既にアップグレードしている場合は、残高を確認するかサポートに連絡してください。',
	'usingInternalDomain' => '申し訳ありませんが、ここで弊社のドメインを使用することはできません',
	'usingSubscibingDomain' => '申し訳ありませんが、このドメインを使用するにはプランをアップグレードする必要があります',
	'invalidUsername' => '無効なユーザー名',
	'invalidDomainname' => '無効なドメイン名',
	'unchangedUsername' => 'ユーザー名は変更されていません',
	'unchangedDomainname' => 'ドメイン名は変更されていません',
	'domainAlreadyExist' => 'ドメイン名は既に存在しています',
	'usernameAlreadyExist' => 'ユーザー名は既に存在しています',
	'usernameTooShort' => 'ユーザー名が短すぎます',
	'parentNotFound' => '親ドメインが見つかりません',
	'invalidDeployYaml' => 'デプロイスクリプトが有効なYAMLではありません: {0}',
	'deploymentFailedToReach' => 'このデプロイのためにサーバー{0}に連絡できませんでした: {1}',
	'hostRunnerProgressing' => '速すぎます！現在デプロイ中のため適用できません！少々お待ちください。',
	'backupNeedSubscribe' => '申し訳ありませんが、バックアップを作成するにはプランをアップグレードする必要があります',
	'backupIsNotActive' => 'バックアップステータスがアクティブではありません。既に削除された可能性があります。',
];
