<?php return [
	'invoiceDomainPurchaseOf' => 'Domain Purchase of {0}',
	'invoiceDomainExtendOf' => 'Domain Extend of {0}',
	'invoiceDomainTransferOf' => 'Domain Transfer of {0}',
	'invoiceTeamPurchaseOf' => 'Team Purchase of {0} plan',
	'invoiceTeamAddons' => 'Team Add-ons',
	'invoiceForMonths' => ' for {0} months',
	'invoiceForYears' => ' for {0} years',
	'invoiceForYearsAndMonths' => ' for {0} years and {1} months',
	'invoiceDataTransferAddonsFor' => 'Additional Data transfer for {0} GB',
	'invoiceTip' => 'Convenience Fee',

	'repoOk' => 'Repo is accessible',
	'repoNoRefs' => 'Repo is accessible but no matching refs',
	'repoNoAccess' => 'Repo is not accessible',
	'fileOk' => 'ZIP file is accessible',
	'fileNoZip' => 'File is not a ZIP file',
	'fileNoAccess' => 'File is not accessible',
	'fileRequired' => 'Repo file is required',
	'uploadFileRequired' => 'File upload is required',
	'uploadFileMustZip' => 'File upload must be a ZIP file',

	'head_violation_storage' => 'Storage Capacity Violation',
	'body_violation_storage' => 'Your account has exceeded 3x the storage capacity limit. We\'re sorry, we have to take action. We have removed all your websites until storage capacity is met.',
	'head_violation_expiry_paid' => 'Expiration Date Violation',
	'body_violation_expiry_paid' => 'Your account has exceeded the expiration date. We turning your account back into a free account. Note that if your websites already exceeded the free quota limit there maybe other notice incoming in couple of days. Please check your account limits before it happens.',
	'head_violation_expiry_free' => 'Expiration Date Violation',
	'body_violation_expiry_free' => 'Your account has exceeded beyond two weeks after the expiration date. We\'re sorry, we have to take action. We have removed all your websites permanently to make room for others.',

	'head_over_expiry_paid' => 'Expiration Date Exceeded',
	'body_over_expiry_paid' => 'Your account has exceeded the expiration date. Please renew your account subscription. Please note if you don\'t renew your account within 2 weeks your account will be turned into a free account.',
	'head_over_expiry_free' => 'Expiration Date Exceeded',
	'body_over_expiry_free' => 'Your account has exceeded the expiration date. We have to disable your websites to get your attention. To activate it back, just login again. Please note that all your websites will be deleted if you don\'t login again within 2 weeks.',
	'head_over_storage' => 'Storage Limit Exceeded',
	'body_over_storage' => 'Your account has exceeded the storage limit. We have to disable your websites to get your attention. To gain back your website, please free some room by deleting unnecessary files. Please note that if you ignore this message and keep filling the storage, we could delete your websites permanently.',
	'head_over_network' => 'Bandwidth Limit Exceeded',
	'body_over_network' => 'Your account has exceeded the bandwidth limit. We have to disable your websites to get your attention. Unfortunately, there\'s no quick way to gain back your website instantly, you have to wait until next month.',
	'head_over_instance' => 'Instance Limit Exceeded',
	'body_over_instance' => 'Your account has exceeded the instance/website count limit. This is weird (we should prevent you from doing that). Nonetheless, we have to disable your websites to get your attention.Please delete some not important websites to gain back your other websites.',
	
	'head_warn_expiry_paid' => 'Expiration Date Warning',
	'body_warn_expiry_paid' => 'Your account will expire in 3 days. Please renew your account to keep your account within current plan.',	
	'head_warn_expiry_free' => 'Expiration Date Warning',
	'body_warn_expiry_free' => 'Your account will expire in 3 days. Because you\'re in free plan, please renew your account by logging in again. Your account will be available for another 30 days.',
	'head_warn_storage' => 'Storage Limit Warning',
	'body_warn_storage' => 'Your websites took the storage until near the limit. Please free some room by deleting unnecessary files.',
	'head_warn_network' => 'Bandwidth Limit Warning',
	'body_warn_network' => 'Your websites took the network data until near the limit. Unfornatunely nothing much you can do until it\'s available again by next month.',
];
