export default {
    'invoiceDomainPurchaseOf': '{0} のドメイン購入',
    'invoiceDomainExtendOf': '{0} のドメイン延長',
    'invoiceDomainTransferOf': '{0} のドメイン転送',
    'invoiceTeamPurchaseOf': '{0} プランのチーム購入',
    'invoiceTeamAddons': 'チームアドオン',
    'invoiceForMonths': ' {0, plural, =1{# か月} other{# か月}} の間',
    'invoiceForYears': ' {0, plural, =1{# 年} other{# 年}} の間',
    'invoiceForYearsAndMonths': ' {0, plural, =1{# 年} other{# 年}} と {1, plural, =1{# か月} other{# か月}} の間',
    'invoiceDataTransferAddonsFor': '{0} GBの追加データ転送',
    'invoiceTip': '手数料',
    "listTitle": "ウェブサイトリスト",
    "newOrder": "ウェブサイトを追加",
    "tabDetail": "情報",
    "tabSetup": "セットアップ",
    "tabManage": "管理",
    "tabRunner": "デプロイ",
    "tabWebhook": "Webhook",
    "tabCheck": "チェック",
    "tabConnection": "接続を確認",
    "tabFirewall": "ファイアウォールを確認",
    "tabNginx": "NGINXを確認",
    "tabDns": "DNSを確認",
    "tabLog": "ログを確認",
    "tabAdmin": "管理",
    "tabRename": "ユーザー名を変更",
    "tabCname": "ドメインを変更",
    "tabPasswd": "パスワードを変更",
    "tabTransfer": "ウェブサイトを転送",
    "tabDelete": "ウェブサイトを削除",
    "startFromTemplate": "テンプレートから始める",
    "uploadOrClone": "インターネットからアップロードまたはクローン",
    "seeMoreTemplates": "もっとウェブテンプレートを見る",
    "customTemplate": "カスタムテンプレート",
    "customDomain": "カスタムドメイン",
    "mergeToParentDomain": "親ドメインにマージ",
    "fetchingDomains": "...ドメインを取得中",
    "moreTemplates": "さらにテンプレート",
    "portalUsername": "ユーザー名",
    "portalUsernameHint": "英数字とハイフンのみ",
    "portalPassword": "パスワード",
    "slaveServer": "地域",
    "scheme": "プラン",
    "usage": "使用量",
    "month": "か月",
    "year": "年",
    "free": "無料",
    "database": "データベース",
    "additionalServices": "追加サービス",
    "softwareCompilers": "ソフトウェアコンパイラ",
    "enableNewFeatures": "新機能を有効にする",
    "addHost": "ウェブサイトを追加",
    "emptyList": "ウェブサイトがリストされていません",
    "waitForDataHint": "リソースの使用量はここに表示されます。データが表示されるのを次の日に再確認してください。",
    "slaveID": "スレーブID",
    "IPAddress": "IPアドレス",
    "openWebsite": "ウェブサイトを開く",
    "openPortal": "ポータルを開く",
    "hostStatus": "ホストの状態",
    "creationDate": "作成日",
    "usernameHost": "ホストのユーザー名",
    "domainHost": "ホストのドメイン",
    "manageHostLogin": "ホストログインを管理",
    "total": "合計",
    "used": "使用済み",
    "remainingMonthlyPlan": "残りの月間プラン",
    "remainingAddons": "残りのアドオン",
    "planDetail": "{0} プラン、{1} ディスクスペース、{2} 月間帯域幅。",
    "emptyForDefaultCname": "デフォルト ({0}) の場合は空白のままにしてください",
    "redeploy": "再デプロイ",
    "debugManually": "手動デバッグ",
    "startOver": "最初からやり直す",
    "deployScript": "スクリプトをデプロイ",
    "deployAdd": "デプロイタスクを追加",
    "deployNow": "実行する!",
    "deployClearHint": "すべてのログをクリアしますか?",
    "websiteReadyHint": "あなたのサイトは準備ができました。今すぐ訪問してみますか?",
    "deployByAdmin": "システムモデレータによって実行",
    "deployOverwriteBanner": "このスクリプトはこのウェブサイトのすべてのファイルを上書きします！",
    "deployOverwriteWarn": "sourceパラメータを指定しました、つまりHOMEファイルが永久に上書きされます。この操作は取り消せません。よろしいですか?",
    "deployHelpBtn": "デプロイメント設定リファレンス",
    "githubWebhook": "Webhookを設定",
    "githubWebhookTitle": "GitHubアクションを設定",
    "githubWebhookHelp": "GitHubにプッシュするときにこのWebhookを使用して自動的にウェブサイトをデプロイできます。",
    "githubWebhookHelpBtn": "GitHubアクションWebhookヘルプ",
    "noWebhook": "このホストに設定されたWebhookはありません。",
    "noGitHubApi": "GitHub APIが利用できません",
    "noGitHubApiToken": "GitHub APIトークンが見つかりません",
    "noGitHubApiHint": "まず、フルリポジトリアクセスを持つGitHubアカウントをリンクする必要があります。",
    "noGitHubApiLink": "今すぐGitHubをリンク",
    "noRepo": "リポジトリが見つかりません",
    "noRepoHint": "検索を絞り込んでみてください",
}
