<?php return [
    'code' => 'ja',
    'codename' => '日本語',
    'login' => 'サインイン',
    'register' => '登録',
    'email' => 'メール',
    'enterToPortal' => 'ポータルに入る',
    'registerToPortal' => 'ポータルに登録する',
    'registerWithEmail' => 'メールで登録する',
    'forgotPrompt' => 'パスワードをお忘れですか？',
    'recoverYourPassword' => 'パスワードを回復する',
    'recoverYourPasswordHint' => '変更するために新しいパスワードを入力してください',
    'report' => '報告する',
    'reportPrompt' => 'DOM Cloudネットワーク内の疑わしい活動を報告します。報告されたウェブサイトが私たちの基準を満たしている場合、コンテンツは直ちに削除されます。',
    'reportAbuse' => '不正コンテンツを報告する',
    'reportDomain' => '報告するドメイン',
    'ok' => 'OK',
    'back' => '戻る',
    'or' => 'または',
    'signInWith' => 'でサインイン',
    'wrongLogin' => '間違ったメールまたはパスワード',
    'registerAgreement' => '登録することにより、あなたは私たちの<a href="//domcloud.co/service" target="_blank">サービス規約</a>に同意したことになります。',
    'emailSent' => '確認のためのメールが送信されました。ログインする前に受信箱（およびスパムボックス）を確認してください。',
    'oAuthFail' => 'サードパーティのログインに失敗したようです。これは通常、タイムアウトまたはそのアカウントに関連付けられた主要なメールがまだ確認されていないことが原因です。',
    'passReset' => 'パスワードが正常にリセットされました。新しいパスワードでログインしてください。',
    'thanksForVerify' => 'ありがとう、あなたのメールは確認されました',
    'password' => 'パスワード',
    'passwordAgain' => 'パスワード（もう一度）',
    'fullName' => 'フルネーム',
    'activeEmail' => 'アクティブなメール',
];
