<?php return [
	'emailAlreadyExist' => '此电子邮件已存在',
	'passwordNotLongEnough' => '此密码长度不足',
	'passwordNotMatch' => '现有密码不匹配',
	'invalidCountry' => '无效的国家代码',

	'accountAlreadyAttached' => '抱歉，此社交账户已绑定到另一个账户。',
	'accountCreationExpired' => '抱歉，我们尝试确认您的账户创建，但您的会话已过期。请再次尝试登录。',
	'accountPasswordlessRecovery' => '很遗憾，您无法恢复无密码账户。请尝试使用第三方账户（如Google或GitHub）。',
	'accountDeleteLastMethod' => '您不能删除唯一的登录方式',
	'accountRecountTooFast' => '请稍等片刻再重试',
	'accountDeleteNotDangling' => '请先删除所有主机、域名和备份',

	'inviteUserNotFound' => '未找到该用户',
	'inviteQuotaFull' => '团队成员数量已达上限，请升级计划',
	'inviteNewFail' => '邀请失败，可能已添加?',
	'inviteRemoveFail' => '移除失败，可能已被移除?',

	'inviteCodeInvalid' => '邀请代码无效',
	'inviteCodeExpired' => '邀请代码已过期',

	'unknownAction' => '未知操作',
	'hostIsNotActive' => '此主机未激活，无法执行任务',
	'needVerifyEmail' => '请先验证您的电子邮件',
	'hostQuotaLimit' => '抱歉，您需要升级计划以创建更多主机。如果您已经升级，请检查余额或联系支持。',
	'usingInternalDomain' => '抱歉，您不能在此使用我们的域名',
	'usingSubscibingDomain' => '抱歉，您需要升级计划才能使用此域名',
	'invalidUsername' => '用户名无效',
	'invalidDomainname' => '域名无效',
	'unchangedUsername' => '用户名未更改',
	'unchangedDomainname' => '域名未更改',
	'domainAlreadyExist' => '域名已存在',
	'usernameAlreadyExist' => '用户名已存在',
	'usernameTooShort' => '用户名太短',
	'parentNotFound' => '未找到父域名',
	'invalidDeployYaml' => '您的部署脚本不是有效的YAML: {0}',
	'deploymentFailedToReach' => '我们未能联系到服务器 {0} 来执行此部署: {1}',
	'hostRunnerProgressing' => '太快了！当前部署运行中，无法应用！请稍候再试。',
	'backupNeedSubscribe' => '抱歉，您需要升级计划才能创建备份',
	'backupIsNotActive' => '备份状态未激活，可能已删除',
];
