export default {
    'invoiceDomainPurchaseOf': '购买域名 {0}',
    'invoiceDomainExtendOf': '延长域名 {0}',
    'invoiceDomainTransferOf': '转移域名 {0}',
    'invoiceTeamPurchaseOf': '团队购买 {0} 计划',
    'invoiceTeamAddons': '团队附加组件',
    'invoiceForMonths': ' 为期 {0, plural, =1{# 个月} other{# 个月}}',
    'invoiceForYears': ' 为期 {0, plural, =1{# 年} other{# 年}}',
    'invoiceForYearsAndMonths': ' 为期 {0, plural, =1{# 年} other{# 年}} 和 {1, plural, =1{# 个月} other{# 个月}}',
    'invoiceDataTransferAddonsFor': '额外数据传输 {0} GB',
    'invoiceTip': '便捷费',
    "listTitle": "网站列表",
    "newOrder": "添加一个网站",
    "tabDetail": "信息",
    "tabSetup": "设置",
    "tabManage": "管理",
    "tabRunner": "部署",
    "tabWebhook": "Webhook",
    "tabCheck": "检查",
    "tabConnection": "检查连接",
    "tabFirewall": "检查防火墙",
    "tabNginx": "检查 NGINX",
    "tabDns": "检查 DNS",
    "tabLog": "检查日志",
    "tabAdmin": "管理员",
    "tabRename": "更改用户名",
    "tabCname": "更改域名",
    "tabPasswd": "更改密码",
    "tabServer": "更改地区",
    "tabTransfer": "转移网站",
    "tabDelete": "删除网站",
    "startFromTemplate": "从模板开始",
    "uploadOrClone": "上传或从互联网克隆",
    "seeMoreTemplates": "查看更多网站模板",
    "customTemplate": "自定义模板",
    "customDomain": "自定义域名",
    "mergeToParentDomain": "合并到父域名",
    "fetchingDomains": "...正在获取域名",
    "moreTemplates": "更多模板",
    "portalUsername": "用户名",
    "portalUsernameHint": "仅限字母数字和连字符",
    "portalPassword": "密码",
    "slaveServer": "地区",
    "scheme": "计划",
    "usage": "使用情况",
    "month": "月",
    "year": "年",
    "free": "免费",
    "database": "数据库",
    "additionalServices": "附加服务",
    "softwareCompilers": "软件编译器",
    "enableNewFeatures": "启用新功能",
    "addHost": "添加一个网站",
    "emptyList": "没有列出网站",
    "waitForDataHint": "资源使用情况将出现在这里。请在第二天返回查看数据。",
    "slaveID": "从属ID",
    "IPAddress": "IP 地址",
    "openWebsite": "打开网站",
    "openPortal": "打开门户",
    "hostStatus": "主机状态",
    "creationDate": "创建日期",
    "usernameHost": "主机用户名",
    "domainHost": "主机域名",
    "manageHostLogin": "管理主机登录",
    "total": "总计",
    "used": "已用",
    "remainingMonthlyPlan": "剩余月度计划",
    "remainingAddons": "剩余附加组件",
    "planDetail": "{0} 计划，{1} 磁盘空间，{2} 月度带宽。",
    "emptyForDefaultCname": "留空为默认 ({0})",
    "redeploy": "重新部署",
    "debugManually": "手动调试",
    "startOver": "重新开始",
    "deployScript": "部署脚本",
    "deployAdd": "添加一个部署任务",
    "deployNow": "执行！",
    "deployClearHint": "清除所有日志？",
    "websiteReadyHint": "您的网站已经准备好了。现在尝试访问？",
    "deployByAdmin": "由系统管理员运行",
    "deployOverwriteBanner": "此脚本将替换此网站的所有文件！",
    "deployOverwriteWarn": "您提到了源参数，这意味着您的 HOME 文件将被永久覆盖。此操作无法撤销。你确定吗？",
    "deployHelpBtn": "部署配置参考",
    "githubWebhook": "设置 Webhook",
    "githubWebhookTitle": "设置 GitHub Action",
    "githubWebhookHelp": "您可以使用此 Webhook 在推送到 GitHub 时自动部署您的网站。",
    "githubWebhookHelpBtn": "GitHub Action Webhook 帮助",
    "noWebhook": "此主机未配置 Webhooks。",
    "noGitHubApi": "GitHub API 不可用",
    "noGitHubApiToken": "未找到 GitHub API 令牌",
    "noGitHubApiHint": "您需要首先将 GitHub 帐户链接到具有完全存储库访问权限。",
    "noGitHubApiLink": "立即链接 GitHub",
    "noRepo": "未找到存储库",
    "noRepoHint": "尝试缩小搜索范围",
}
