<?php return [
	'code' => 'zh',
	'codename' => '中文',
	'codedir' => 'ltr',
	'login' => '登录',
	'register' => '注册',
	'email' => '电子邮件',
	'enterToPortal' => '进入门户',
	'registerToPortal' => '注册门户',
	'registerWithEmail' => '用电子邮件注册',
	'forgotPrompt' => '忘记密码？',
	'recoverYourPassword' => '找回密码',
	'recoverYourPasswordHint' => '输入新密码以更改',
	'report' => '举报',
	'reportPrompt' => '举报DOM云网络中的可疑活动。如果举报的网站符合我们的标准，内容将立即删除。',
	'reportAbuse' => '举报滥用内容',
	'reportDomain' => '要举报的域名',
	'ok' => '好的',
	'back' => '返回',
	'or' => '或',
	'signInWith' => '登录方式 {0}',
	'wrongLogin' => '错误的电子邮件或密码',
	'registerAgreement' => '注册即表示您同意我们的<a href="{0}" target="_blank">服务条款</a>。',
	'emailSent' => '验证邮件已发送，请在登录前检查您的收件箱（和垃圾邮件箱）。',
	'oAuthFail' => '看起来您使用第三方登录的尝试失败了。通常是由于超时或该帐户关联的主要电子邮件尚未验证。',
	'passReset' => '您的密码已成功重置。请使用新密码登录。',
	'thanksForVerify' => '谢谢，您的电子邮件已验证',
	'password' => '密码',
	'passwordAgain' => '密码（再次输入）',
	'fullName' => '全名',
	'activeEmail' => '活跃的电子邮件',
];
