export default {
    "code": "zh",
    "codename": "中文",
    "appTitle": "DOM云",
    "appTitleLong": "DOM云托管",
    "logout": "登出",
    "profile": "个人资料",
    "status": "状态",
    "verifyStatus": "验证状态",
    "hosting": "网站",
    "domain": "域名",
    "backup": "备份",
    "owner": "拥有者",
    "admin": "管理员",
    "member": "成员",
    "team": "团队",
    "email": "邮箱",
    "storage": "存储",
    "bandwidth": "带宽",
    "instances": "实例",
    "users": "用户",
    "details": "详情",
    "members": "成员",
    "upgrade": "升级",
    "otherTeams": "其他团队",
    "hostname": "主机名",
    "port": "端口",
    "username": "用户名",
    "password": "密码",
    "server": "服务器",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    "help": "帮助",
    "helpDocs": "文档",
    "helpDocsLink": "https://domcloud.co/docs/intro/",
    "helpEmail": "电子邮件",
    "helpEmailLink": "mailto:support@domcloud.co",
    "helpChat": "聊天",
    "helpChatLink": "https://t.me/WIIIN0DE",
    "helpUpdates": "更新",
    "helpUpdatesLink": "https://twitter.com/domcloud_co",
    "country": "国家",
    "chooseCountry": "选择国家",
    "expiration": "到期日",
    "resendConfirmationEmail": "重新发送确认邮件",
    "learnMore": "了解更多",
    "passwordNotice": "您不需要记住这个密码",
    "lastUpdatedAt": "上次更新于",
    "language": "语言",
    "theme": "主题",
    "themeDark": "始终暗色",
    "themeLight": "始终亮色",
    "themeSystem": "系统主题",
    "role": "角色",
    "action": "操作",
    "currencyInput": "货币",
    "invoiceNoteInput": "发票备注",
    "defaultServerInput": "默认服务器",
    "defaultServerInputNone": "无（向我询问）",
    "name": "姓名",
    "phone": "电话号码",
    "phoneHint": "完整电话号码（以+开头）",
    "phoneAlt": "备用电话号码",
    "fullName": "全名",
    "companyName": "公司名称",
    "activeEmail": "活动邮箱",
    "newPassword": "新密码",
    "editProfile": "编辑个人资料",
    "saveProfile": "保存个人资料",
    "deleteAccount": "删除帐户",
    "loginMethods": "登录方式",
    "loginRemoveConfirm": "您确定要删除此登录方式吗？",
    "loginAdd": "添加或更改登录方式",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "电子邮件 + 密码",
    "loginVia": "通过 {0}",
    "passwordConfirm": "输入当前帐户密码（如果有）",
    "passwordSetInput": "输入新密码，必须至少包含8个字符",
    "passwordSetCancel": "已取消设置此帐户的密码",
    "passwordSetCancelLength": "已取消设置密码，必须至少包含8个字符",
    "yearDuration": "年限",
    "monthDuration": "月限",
    "annualSaving": "节省 16%",
    "totalPayment": "总付款额",
    "expirationDate": "到期日期",
    "orderNow": "立即订购",
    "invoice": "发票",
    "pendingInvoices": "待处理发票",
    "noPendingInvoices": "您当前没有待处理的发票。",
    "mixedCurrency": "所选发票具有混合货币",
    "currentPlan": "当前计划",
    "currentPlanDescription": "每月费用为 <b>{0}</b>，到期日为 <b>{1}</b>",
    "priceDescription": "{0} / 月",
    "monthlyLimits": "每月限制",
    "storageLimit": "{0} GB 存储空间",
    "networkLimit": "{0} GB 网络",
    "instanceLimit": "{0} {0, plural, one {实例} other {实例}}",
    "userLimit": "{0} {0, plural, one {用户} other {用户}}",
    "autoStop": "达到限制后自动停止",
    "noFreeDomain": "没有免费的 *.domcloud.dev 域名",
    "withFreeDomain": "免费的 *.domcloud.dev 域名",
    "withBackup": "服务器级别的自动备份",
    "withDocker": "Docker 和长期运行的应用程序",
    "storageUsage": "存储使用情况",
    "storageUsageCap": "总共 {0}",
    "bandwidthUsed": "已使用的带宽",
    "bandwidthUsedCap": "每月 {0}",
    "instancesActive": "活动实例",
    "instancesActiveCap": "网站总数 {0}",
    "teamUsers": "团队用户",
    "teamUsersCap": "最多 {0} 个用户",
    "remainingAvailable": "剩余可用",
    "remainingStorage": "剩余存储空间",
    "remainingNetwork": "剩余网络数据",
    "remainingInstance": "剩余实例",
    "dataTransfer": "数据传输",
    "expires": "到期时间 {0}",
    "expiresAt": "到期时间 {0}",
    "expireFreeHint": `
  到期日期会自动延长（每次您登录时或您的网站具有足够的网络流量（> 50 MB）时）
  每月末。
  `,
    "discountedAt": "享受折扣 {0}",
    "extendingCurrentExpiryDate": "延长当前到期日期",
    "usersLimitHint": "此团队中有 {0} {0, plural, one {用户} other {用户}}，还可以添加 {1} {1, plural, one {用户} other {用户}}",
    "emailToInvite": "邀请的邮箱地址",
    "selectRole": "选择角色",
    "info": "信息",
    "total": "总计",
    "back": "返回",
    "add": "添加",
    "addMember": "添加成员",
    "confirmRemoveMember": "您确定要删除此成员吗？",
    "edit": "编辑",
    "apply": "应用",
    "save": "保存",
    "clear": "清除",
    "update": "更新",
    "updateUsage": "更新使用情况",
    "change": "更改",
    "archives": "存档",
    "renew": "续费",
    "extend": "延长",
    "topup": "充值",
    "processing": "处理中",
    "cancel": "取消",
    "print": "打印",
    "why": "为什么？",
    "pay": "支付",
    "payAccept": "我们接受以下支付方式",
    "loading": "正在获取数据...",
    "fetchError": "获取数据时出错！请稍后重试",
    "notFound": "未找到",
    "notFoundDescription": "您正在寻找的页面不存在。",
    "notFoundLink": "返回首页"
}
