export default {
    "status": {
        "active": "Активен",
        "starting": "Запуск",
        "suspended": "Приостановлен",
        "moving": "Перемещение",
        "removing": "Удаление",
        "removed": "Удалён"
    },
    "listTitle": "Список сайтов",
    "newOrder": "Добавить сайт",
    "tabDetail": "Информация",
    "tabSetup": "Настройка",
    "tabManage": "Управление",
    "tabRunner": "Деплой",
    "tabDatabase": "База данных",
    "tabSubdomain": "Поддомен",
    "tabSoftware": "Программное обеспечение",
    "tabWebhook": "Веб-хуки",
    "tabCheck": "Проверка",
    "tabConnection": "Проверка подключения",
    "tabFirewall": "Проверка брандмауэра",
    "tabNginx": "Проверка NGINX",
    "tabDns": "Проверка DNS",
    "tabLog": "Просмотр логов",
    "tabUser": "Проверить пользователя",
    "tabAdmin": "Администратор",
    "tabRename": "Переименовать пользователя",
    "tabCname": "Изменить домен",
    "tabPasswd": "Изменить пароль",
    "tabServer": "Изменить регион",
    "tabTransfer": "Перенос сайта",
    "tabDelete": "Удалить сайт",
    "startFromTemplate": "Начать с шаблона",
    "uploadOrClone": "Загрузить или клонировать из интернета",
    "seeMoreTemplates": "Посмотреть больше шаблонов сайтов",
    "customTemplate": "Пользовательский шаблон",
    "customDomain": "Пользовательский домен",
    "mergeToParentDomain": "Объединить с родительским доменом",
    "fetchingDomains": "...получение доменов",
    "moreTemplates": "Больше шаблонов",
    "portalUsername": "Имя пользователя",
    "portalUsernameHint": "Только буквы, цифры и дефисы",
    "portalPassword": "Пароль",
    "serverName": "Регион",
    "scheme": "Тариф",
    "usage": "Использование",
    "month": "Месяц",
    "year": "Год",
    "free": "Бесплатно",
    "database": "База данных",
    "additionalServices": "Дополнительные услуги",
    "softwareCompilers": "Компиляторы ПО",
    "enableNewFeatures": "Включить новые функции",
    "addHost": "Добавить сайт",
    "emptyList": "Список пуст",
    "waitForDataHint": "Использование ресурсов будет отображаться здесь",
    "IPAddress": "IP-адрес",
    "openWebsite": "Открыть сайт",
    "openPortal": "Открыть портал",
    "creationDate": "Дата создания",
    "websiteStatus": "Статус сайта",
    "websiteUsername": "Имя пользователя сайта",
    "websiteDomain": "Домен сайта",
    "manageHostLogin": "Управление входом на хост",
    "total": "Всего",
    "used": "Использовано",
    "remainingMonthlyPlan": "Остаток месячного плана",
    "remainingAddons": "Оставшиеся дополнения",
    "createDatabase": "Создать базу данных {0}",
    "createDatabaseHint": "Введите имя новой базы данных {0}",
    "createDatabaseConfirm": "\"{0}\" будет создан, продолжить?",
    "dropDatabase": "Удалить базу данных {0}",
    "dropDatabaseConfirm": "\"{0}\" будет удалён, продолжить?",
    "dropDatabaseConfirm2": "Вы уверены, что хотите выполнить \"{0}\"? Это действие нельзя отменить.",
    "tables": "{0} {0, plural, one {таблица} other {таблицы}}",
    "noSubdomain": "Используйте собственный домен для создания поддоменов",
    "createSubdomain": "Создать новый поддомен",
    "deleteSubdomain": "Удалить поддомен {0}",
    "deleteSubdomainConfirm": "Поддомен \"{0}\" будет удалён, продолжить?",
    "deleteSubdomainConfirm2": "Вы уверены, что хотите выполнить \"{0}\"? Это действие нельзя отменить.",
    "enterFullDomainName": "Введите полное имя домена",
    "useDefaultCname": "Использовать домен по умолчанию ({0})",
    "useDifferentPassword": "Использовать другой пароль для {0}",
    "redeploy": "Повторный деплой",
    "debugManually": "Отладить вручную",
    "startOver": "Начать заново",
    "deployScript": "Развернуть скрипт",
    "deployAdd": "Добавить задачу деплоя",
    "deployNow": "Выполнить!",
    "deployClearHint": "Очистить все логи?",
    "websiteReadyHint": "Ваш сайт готов. Хотите посетить его сейчас?",
    "deployByAdmin": "Выполнено системным модератором",
    "deployOverwriteBanner": "Этот скрипт перезапишет все файлы на этом сайте!",
    "deployOverwriteWarn": "Вы указали параметр source, что означает, что ваш HOME файл будет ПЕРЕЗАПИСАН НАВСЕГДА. Это действие не может быть отменено. Вы уверены?",
    "deployHelpBtn": "Справка по настройке деплоя",
    "githubWebhook": "Настроить веб-хук",
    "githubWebhookTitle": "Настроить действие GitHub",
    "githubWebhookHelp": "Вы можете использовать этот веб-хук для автоматического деплоя вашего сайта при push в GitHub.",
    "githubWebhookHelpBtn": "Помощь по веб-хукам GitHub",
    "noWebhook": "Нет настроенных веб-хуков для этого хоста.",
    "noGitHubApi": "API GitHub недоступен",
    "noGitHubApiToken": "Токен API GitHub не найден",
    "noGitHubApiHint": "Сначала необходимо связать аккаунт GitHub с полным доступом к репозиторию.",
    "noGitHubApiLink": "Связать GitHub сейчас",
    "noRepo": "Репозиторий не найден",
    "noRepoHint": "Попробуйте уточнить поиск",
}
