export default {
    'invoiceDomainPurchaseOf': 'Покупка домена {0}',
    'invoiceDomainExtendOf': 'Продление домена {0}',
    'invoiceDomainTransferOf': 'Трансфер домена {0}',
    'invoiceTeamPurchaseOf': 'Покупка команды по тарифу {0}',
    'invoiceTeamAddons': 'Дополнения команды',
    'invoiceForMonths': ' на {0, plural, =1{# месяц} other{# месяцев}}',
    'invoiceForYears': ' на {0, plural, =1{# год} other{# года}}',
    'invoiceForYearsAndMonths': ' на {0, plural, =1{# год} other{# лет}} и {1, plural, =1{# месяц} other{# месяцев}}',
    'invoiceDataTransferAddonsFor': 'Дополнительный перенос данных на {0} ГБ',
    'invoiceTip': 'Плата за обслуживание',
    "listTitle": "Список сайтов",
    "newOrder": "Добавить сайт",
    "tabDetail": "Информация",
    "tabSetup": "Настройка",
    "tabManage": "Управление",
    "tabRunner": "Деплой",
    "tabWebhook": "Веб-хуки",
    "tabCheck": "Проверка",
    "tabConnection": "Проверка подключения",
    "tabFirewall": "Проверка брандмауэра",
    "tabNginx": "Проверка NGINX",
    "tabDns": "Проверка DNS",
    "tabLog": "Просмотр логов",
    "tabAdmin": "Администратор",
    "tabRename": "Переименовать пользователя",
    "tabCname": "Изменить домен",
    "tabPasswd": "Изменить пароль",
    "tabServer": "Изменить регион",
    "tabTransfer": "Перенос сайта",
    "tabDelete": "Удалить сайт",
    "startFromTemplate": "Начать с шаблона",
    "uploadOrClone": "Загрузить или клонировать из интернета",
    "seeMoreTemplates": "Посмотреть больше шаблонов сайтов",
    "customTemplate": "Пользовательский шаблон",
    "customDomain": "Пользовательский домен",
    "mergeToParentDomain": "Объединить с родительским доменом",
    "fetchingDomains": "...получение доменов",
    "moreTemplates": "Больше шаблонов",
    "portalUsername": "Имя пользователя",
    "portalUsernameHint": "Только буквы, цифры и дефисы",
    "portalPassword": "Пароль",
    "slaveServer": "Регион",
    "scheme": "Тариф",
    "usage": "Использование",
    "month": "Месяц",
    "year": "Год",
    "free": "Бесплатно",
    "database": "База данных",
    "additionalServices": "Дополнительные услуги",
    "softwareCompilers": "Компиляторы ПО",
    "enableNewFeatures": "Включить новые функции",
    "addHost": "Добавить сайт",
    "emptyList": "Список пуст",
    "waitForDataHint": "Использование ресурсов будет отображаться здесь. Повторите попытку на следующий день.",
    "slaveID": "ID региона",
    "IPAddress": "IP-адрес",
    "openWebsite": "Открыть сайт",
    "openPortal": "Открыть портал",
    "hostStatus": "Статус хоста",
    "creationDate": "Дата создания",
    "usernameHost": "Имя пользователя хоста",
    "domainHost": "Домен хоста",
    "manageHostLogin": "Управление входом на хост",
    "total": "Всего",
    "used": "Использовано",
    "remainingMonthlyPlan": "Остаток месячного плана",
    "remainingAddons": "Оставшиеся дополнения",
    "planDetail": "Тариф {0}, {1} дискового пространства, {2} месячный трафик.",
    "emptyForDefaultCname": "Оставьте пустым для значения по умолчанию ({0})",
    "redeploy": "Повторный деплой",
    "debugManually": "Отладить вручную",
    "startOver": "Начать заново",
    "deployScript": "Развернуть скрипт",
    "deployAdd": "Добавить задачу деплоя",
    "deployNow": "Выполнить!",
    "deployClearHint": "Очистить все логи?",
    "websiteReadyHint": "Ваш сайт готов. Хотите посетить его сейчас?",
    "deployByAdmin": "Выполнено системным модератором",
    "deployOverwriteBanner": "Этот скрипт перезапишет все файлы на этом сайте!",
    "deployOverwriteWarn": "Вы указали параметр source, что означает, что ваш HOME файл будет ПЕРЕЗАПИСАН НАВСЕГДА. Это действие не может быть отменено. Вы уверены?",
    "deployHelpBtn": "Справка по настройке деплоя",
    "githubWebhook": "Настроить веб-хук",
    "githubWebhookTitle": "Настроить действие GitHub",
    "githubWebhookHelp": "Вы можете использовать этот веб-хук для автоматического деплоя вашего сайта при push в GitHub.",
    "githubWebhookHelpBtn": "Помощь по веб-хукам GitHub",
    "noWebhook": "Нет настроенных веб-хуков для этого хоста.",
    "noGitHubApi": "API GitHub недоступен",
    "noGitHubApiToken": "Токен API GitHub не найден",
    "noGitHubApiHint": "Сначала необходимо связать аккаунт GitHub с полным доступом к репозиторию.",
    "noGitHubApiLink": "Связать GitHub сейчас",
    "noRepo": "Репозиторий не найден",
    "noRepoHint": "Попробуйте уточнить поиск",
}
