export default {
    "logout": "Выйти",
    "profile": "Профиль",
    "status": "Статус",
    "verifyStatus": "Статус проверки",
    "bannedHint": "Ваш аккаунт заблокирован, извините.",
    "hosting": "Веб-сайт",
    "domain": "Домен",
    "backup": "Резервная копия",
    "owner": "Владелец",
    "admin": "Администратор",
    "member": "Участник",
    "team": "Команда",
    "email": "Электронная почта",
    "storage": "Хранилище",
    "bandwidth": "Пропускная способность",
    "instances": "Экземпляры",
    "users": "Пользователи",
    "details": "Детали",
    "members": "Участники",
    "upgrade": "Обновить",
    "otherTeams": "Другие команды",
    "inviteCode": "Код приглашения",
    "hostname": "Имя хоста",
    "port": "Порт",
    "username": "Имя пользователя",
    "password": "Пароль",
    "server": "Сервер",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "ssh": "SSH/SFTP",
    "webmin": "Webmin",
    "filestash": "Filestash",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "phpmyadmin": "phpMyAdmin",
    "phppgadmin": "phpPgAdmin",
    "webssh": "WebSSH",
    "vscode": "Visual Studio Code",
    "help": "Помощь",
    "helpDocs": "Документация",
    "helpEmail": "Электронная почта",
    "helpForum": "Форум",
    "helpChat": "Чат",
    "helpUpdates": "Обновления",
    "country": "Страна",
    "chooseCountry": "Выберите страну",
    "expiration": "Истечение срока действия",
    "resendConfirmationEmail": "Повторно отправить письмо с подтверждением",
    "learnMore": "Узнать больше",
    "passwordNotice": "Вам не нужно запоминать этот пароль",
    "lastUpdatedAt": "Последнее обновление в",
    "language": "Язык",
    "theme": "Тема",
    "themeDark": "Всегда темно",
    "themeLight": "Всегда светло",
    "themeSystem": "Системная тема",
    "role": "Роль",
    "action": "Действие",
    "currencyInput": "Валюта",
    "invoiceNoteInput": "Контакт для счета",
    "defaultServerInput": "Сервер по умолчанию",
    "defaultServerInputNone": "Нет (спросите у меня)",
    "name": "Имя",
    "phone": "Номер телефона",
    "phoneHint": "Полный номер телефона (начинается с +)",
    "phoneAlt": "Альтернативный номер телефона",
    "fullName": "Полное имя",
    "companyName": "Название компании",
    "activeEmail": "Активный адрес электронной почты",
    "newPassword": "Новый пароль",
    "editProfile": "Редактировать профиль",
    "saveProfile": "Сохранить профиль",
    "deleteAccount": "Удалить аккаунт",
    "loginMethods": "Методы входа",
    "loginRemoveConfirm": "Вы уверены, что хотите удалить этот метод входа?",
    "loginAdd": "Добавить или заменить метод входа",
    "loginGithub": "GitHub",
    "loginGoogle": "Google",
    "loginEmail": "Электронная почта + Пароль",
    "loginVia": "через {0}",
    "passwordConfirm": "Введите текущий пароль учетной записи (при наличии)",
    "passwordSetInput": "Введите новый пароль, должен состоять минимум из 8 символов",
    "passwordSetCancel": "Установка пароля для этой учетной записи отменена",
    "passwordSetCancelLength": "Установка пароля отменена, должен состоять минимум из 8 символов",
    "yearDuration": "Продолжительность в годах",
    "monthDuration": "Продолжительность в месяцах",
    "annualSaving": "Сохранить 16%",
    "totalPayment": "Общая сумма к оплате",
    "expirationDate": "Дата истечения срока действия",
    "orderNow": "Заказать сейчас",
    "invoice": "Счет-фактура",
    "pendingInvoices": "Ожидающие счета-фактуры",
    "noPendingInvoices": "У вас в настоящее время нет ожидающих счетов-фактур.",
    "mixedCurrency": "Выбранные счета имеют смешанные валюты",
    "currentPlan": "Текущий план",
    "currentPlanDescription": "Стоимость <b>{0}</b> в месяц с истечением срока <b>{1}</b>",
    "priceDescription": "{0} / месяц",
    "monthlyLimits": "Ежемесячные лимиты",
    "storageLimit": "{0} ГБ хранилища",
    "networkLimit": "{0} ГБ сети",
    "instanceLimit": "{0} {0, plural, one {Инстанс} other {Инстансы}}",
    "userLimit": "{0} {0, plural, one {Пользователь} other {Пользователи}}",
    "autoStop": "Автоматическая остановка при достижении лимита",
    "noFreeDomain": "Нет бесплатного домена *.domcloud.dev",
    "withFreeDomain": "Бесплатный домен *.domcloud.dev",
    "withBackup": "Автоматическое резервное копирование на уровне сервера",
    "withDocker": "Docker и долгосрочные приложения",
    "storageUsage": "Использование хранилища",
    "storageUsageCap": "из {0} всего",
    "bandwidthUsed": "Использованная полоса пропускания",
    "bandwidthUsedCap": "из {0} в месяц",
    "instancesActive": "Активные инстансы",
    "instancesActiveCap": "из {0} веб-сайтов",
    "teamUsers": "Пользователи команды",
    "teamUsersCap": "из максимум {0} пользователей",
    "remainingAvailable": "Оставшиеся доступные",
    "remainingStorage": "Свободное хранилище",
    "remainingNetwork": "Оставшиеся сетевые данные",
    "remainingInstance": "Оставшийся экземпляр",
    "dataTransfer": "Передача данных",

    "copy": "Копировать",
    "copied": "Скопировано!",
    "reloading": "Перезагрузка {0}",
    "expires": "Истекает {0}",
    "expiresAt": "Истекает {0}",
    "expireFreeHint": `
  Даты истечения срока автоматически продляются (на 3 месяца) 
  каждый раз, когда вы входите в систему или ваши сайты имеют достаточный сетевой трафик (> 50 МБ)
  в конце месяца.
  `,
    "discountedAt": "Со скидкой {0}",
    "extendingCurrentExpiryDate": "Продление текущей даты истечения срока",
    "usersLimitHint": "{0} {0, plural, one {пользователь} other {пользователи}} в этой команде, еще {1} {1, plural, one {пользователь} other {пользователи}} могут быть добавлены",
    "emailToInvite": "Электронная почта для приглашения",
    "selectRole": "Выберите роль",
    "info": "Информация",
    "total": "Всего",
    "back": "Назад",
    "add": "Добавить",
    "addMember": "Добавить участника",
    "confirmRemoveMember": "Вы уверены, что хотите удалить этого участника?",
    "edit": "Редактировать",
    "apply": "Применить",
    "save": "Сохранить",
    "clear": "Очистить",
    "update": "Обновить",
    "updateUsage": "Обновить использование",
    "change": "Изменить",
    "archives": "Архивы",
    "renew": "Продлить",
    "extend": "Расширить",
    "topup": "Пополнить",
    "processing": "Обработка",
    "cancel": "Отмена",
    "print": "Печать",
    "delete": "Удалить",
    "why": "Почему?",
    "pay": "Оплатить",
    "payAccept": "Мы принимаем оплату через",
    "loading": "Сбор данных...",
    "fetchError": "Ошибка при получении данных! Попробуйте еще раз позже",
    "notFound": "Не найдено",
    "notFoundDescription": "Страница, которую вы ищете, не существует.",
    "notFoundLink": "Вернуться на главную страницу"
}